<?php

namespace BB\DurianBundle\Tests\Entity;

use BB\DurianBundle\Tests\DurianTestCase;
use BB\DurianBundle\Entity\StatCashRebate;

/**
 * 測試現金返點統計
 *
 * @author Sweet 2014.11.14
 */
class StatCashRebateTest extends DurianTestCase
{
    /**
     * 測試基本
     */
    public function testBasic()
    {
        $at = new \DateTime('2013-01-10 12:00:00');
        $stat = new StatCashRebate($at, 8, 156);

        $this->assertEquals($at, $stat->getAt());
        $this->assertEquals(8, $stat->getUserId());
        $this->assertEquals(156, $stat->getCurrency());
        $this->assertEquals(0, $stat->getRebateBallAmount());
        $this->assertEquals(0, $stat->getRebateBallCount());
        $this->assertEquals(0, $stat->getRebateKenoAmount());
        $this->assertEquals(0, $stat->getRebateKenoCount());
        $this->assertEquals(0, $stat->getRebateVideoAmount());
        $this->assertEquals(0, $stat->getRebateVideoCount());
        $this->assertEquals(0, $stat->getRebateSportAmount());
        $this->assertEquals(0, $stat->getRebateSportCount());
        $this->assertEquals(0, $stat->getRebateProbAmount());
        $this->assertEquals(0, $stat->getRebateProbCount());
        $this->assertEquals(0, $stat->getRebateLotteryAmount());
        $this->assertEquals(0, $stat->getRebateLotteryCount());
        $this->assertEquals(0, $stat->getRebateBBplayAmount());
        $this->assertEquals(0, $stat->getRebateBBplayCount());
        $this->assertEquals(0, $stat->getRebateOfferAmount());
        $this->assertEquals(0, $stat->getRebateOfferCount());
        $this->assertEquals(0, $stat->getRebateBBVideoAmount());
        $this->assertEquals(0, $stat->getRebateBBVideoCount());
        $this->assertEquals(0, $stat->getRebateTTVideoAmount());
        $this->assertEquals(0, $stat->getRebateTTVideoCount());
        $this->assertEquals(0, $stat->getRebateArmVideoAmount());
        $this->assertEquals(0, $stat->getRebateArmVideoCount());
        $this->assertEquals(0, $stat->getRebateXpjVideoAmount());
        $this->assertEquals(0, $stat->getRebateXpjVideoCount());
        $this->assertEquals(0, $stat->getRebateYfVideoAmount());
        $this->assertEquals(0, $stat->getRebateYfVideoCount());
        $this->assertEquals(0, $stat->getRebate3dAmount());
        $this->assertEquals(0, $stat->getRebate3dCount());
        $this->assertEquals(0, $stat->getRebateBattleAmount());
        $this->assertEquals(0, $stat->getRebateBattleCount());
        $this->assertEquals(0, $stat->getRebateVirtualAmount());
        $this->assertEquals(0, $stat->getRebateVirtualCount());
        $this->assertEquals(0, $stat->getRebateVipVideoAmount());
        $this->assertEquals(0, $stat->getRebateVipVideoCount());
        $this->assertEquals(0, $stat->getRebateAgVideoAmount());
        $this->assertEquals(0, $stat->getRebateAgVideoCount());
        $this->assertEquals(0, $stat->getRebatePTAmount());
        $this->assertEquals(0, $stat->getRebatePTCount());
        $this->assertEquals(0, $stat->getRebateLTAmount());
        $this->assertEquals(0, $stat->getRebateLTCount());
        $this->assertEquals(0, $stat->getRebateMIAmount());
        $this->assertEquals(0, $stat->getRebateMICount());
        $this->assertEquals(0, $stat->getRebateABAmount());
        $this->assertEquals(0, $stat->getRebateABCount());
        $this->assertEquals(0, $stat->getRebateMGAmount());
        $this->assertEquals(0, $stat->getRebateMGCount());
        $this->assertEquals(0, $stat->getRebateOGAmount());
        $this->assertEquals(0, $stat->getRebateOGCount());
        $this->assertEquals(0, $stat->getRebateSBAmount());
        $this->assertEquals(0, $stat->getRebateSBCount());
        $this->assertEquals(0, $stat->getRebateGDAmount());
        $this->assertEquals(0, $stat->getRebateGDCount());
        $this->assertEquals(0, $stat->getRebateSAAmount());
        $this->assertEquals(0, $stat->getRebateSACount());
        $this->assertEquals(0, $stat->getRebateGnsAmount());
        $this->assertEquals(0, $stat->getRebateGnsCount());
        $this->assertEquals(0, $stat->getRebateMGJackpotAmount());
        $this->assertEquals(0, $stat->getRebateMGJackpotCount());
        $this->assertEquals(0, $stat->getRebateMGSlotsAmount());
        $this->assertEquals(0, $stat->getRebateMGSlotsCount());
        $this->assertEquals(0, $stat->getRebateMGFeatureAmount());
        $this->assertEquals(0, $stat->getRebateMGFeatureCount());
        $this->assertEquals(0, $stat->getRebateMGTableAmount());
        $this->assertEquals(0, $stat->getRebateMGTableCount());
        $this->assertEquals(0, $stat->getRebateMGMobileAmount());
        $this->assertEquals(0, $stat->getRebateMGMobileCount());
        $this->assertEquals(0, $stat->getRebateISBAmount());
        $this->assertEquals(0, $stat->getRebateISBCount());
        $this->assertEquals(0, $stat->getRebateBBFGAmount());
        $this->assertEquals(0, $stat->getRebateBBFGCount());
        $this->assertEquals(0, $stat->getRebateBCAmount());
        $this->assertEquals(0, $stat->getRebateBCCount());
        $this->assertEquals(0, $stat->getRebateBBSlotsAmount());
        $this->assertEquals(0, $stat->getRebateBBSlotsCount());
        $this->assertEquals(0, $stat->getRebateBBTableAmount());
        $this->assertEquals(0, $stat->getRebateBBTableCount());
        $this->assertEquals(0, $stat->getRebateBBArcadeAmount());
        $this->assertEquals(0, $stat->getRebateBBArcadeCount());
        $this->assertEquals(0, $stat->getRebateBBScratchAmount());
        $this->assertEquals(0, $stat->getRebateBBScratchCount());
        $this->assertEquals(0, $stat->getRebateBBFeatureAmount());
        $this->assertEquals(0, $stat->getRebateBBFeatureCount());
        $this->assertEquals(0, $stat->getRebateBBTreasureAmount());
        $this->assertEquals(0, $stat->getRebateBBTreasureCount());
        $this->assertEquals(0, $stat->getRebateISBSlotsAmount());
        $this->assertEquals(0, $stat->getRebateISBSlotsCount());
        $this->assertEquals(0, $stat->getRebateISBTableAmount());
        $this->assertEquals(0, $stat->getRebateISBTableCount());
        $this->assertEquals(0, $stat->getRebateISBJackpotAmount());
        $this->assertEquals(0, $stat->getRebateISBJackpotCount());
        $this->assertEquals(0, $stat->getRebateISBPokerAmount());
        $this->assertEquals(0, $stat->getRebateISBPokerCount());
        $this->assertEquals(0, $stat->getRebate888FishingAmount());
        $this->assertEquals(0, $stat->getRebate888FishingCount());
        $this->assertEquals(0, $stat->getRebatePTSlotsAmount());
        $this->assertEquals(0, $stat->getRebatePTSlotsCount());
        $this->assertEquals(0, $stat->getRebatePTTableAmount());
        $this->assertEquals(0, $stat->getRebatePTTableCount());
        $this->assertEquals(0, $stat->getRebatePTJackpotAmount());
        $this->assertEquals(0, $stat->getRebatePTJackpotCount());
        $this->assertEquals(0, $stat->getRebatePTArcadeAmount());
        $this->assertEquals(0, $stat->getRebatePTArcadeCount());
        $this->assertEquals(0, $stat->getRebatePTScratchAmount());
        $this->assertEquals(0, $stat->getRebatePTScratchCount());
        $this->assertEquals(0, $stat->getRebatePTPokerAmount());
        $this->assertEquals(0, $stat->getRebatePTPokerCount());
        $this->assertEquals(0, $stat->getRebatePTUnclassifiedAmount());
        $this->assertEquals(0, $stat->getRebatePTUnclassifiedCount());
        $this->assertEquals(0, $stat->getRebateGOGAmount());
        $this->assertEquals(0, $stat->getRebateGOGCount());
        $this->assertEquals(0, $stat->getRebateSk1Amount());
        $this->assertEquals(0, $stat->getRebateSk1Count());
        $this->assertEquals(0, $stat->getRebateSk2Amount());
        $this->assertEquals(0, $stat->getRebateSk2Count());
        $this->assertEquals(0, $stat->getRebateSk3Amount());
        $this->assertEquals(0, $stat->getRebateSk3Count());
        $this->assertEquals(0, $stat->getRebateSk4Amount());
        $this->assertEquals(0, $stat->getRebateSk4Count());
        $this->assertEquals(0, $stat->getRebateSk5Amount());
        $this->assertEquals(0, $stat->getRebateSk5Count());
        $this->assertEquals(0, $stat->getRebateSk6Amount());
        $this->assertEquals(0, $stat->getRebateSk6Count());
        $this->assertEquals(0, $stat->getRebateHBSlotsAmount());
        $this->assertEquals(0, $stat->getRebateHBSlotsCount());
        $this->assertEquals(0, $stat->getRebateHBTableAmount());
        $this->assertEquals(0, $stat->getRebateHBTableCount());
        $this->assertEquals(0, $stat->getRebateHBPokerAmount());
        $this->assertEquals(0, $stat->getRebateHBPokerCount());
        $this->assertEquals(0, $stat->getRebateBGLiveAmount());
        $this->assertEquals(0, $stat->getRebateBGLiveCount());
        $this->assertEquals(0, $stat->getRebateFishingMasterAmount());
        $this->assertEquals(0, $stat->getRebateFishingMasterCount());
        $this->assertEquals(0, $stat->getRebatePPSlotsAmount());
        $this->assertEquals(0, $stat->getRebatePPSlotsCount());
        $this->assertEquals(0, $stat->getRebatePPTableAmount());
        $this->assertEquals(0, $stat->getRebatePPTableCount());
        $this->assertEquals(0, $stat->getRebatePPJackpotAmount());
        $this->assertEquals(0, $stat->getRebatePPJackpotCount());
        $this->assertEquals(0, $stat->getRebatePPFeatureAmount());
        $this->assertEquals(0, $stat->getRebatePPFeatureCount());
        $this->assertEquals(0, $stat->getRebatePTFishingAmount());
        $this->assertEquals(0, $stat->getRebatePTFishingCount());
        $this->assertEquals(0, $stat->getRebateGNSSlotsAmount());
        $this->assertEquals(0, $stat->getRebateGNSSlotsCount());
        $this->assertEquals(0, $stat->getRebateGNSFishingAmount());
        $this->assertEquals(0, $stat->getRebateGNSFishingCount());
        $this->assertEquals(0, $stat->getRebateJDBSlotsAmount());
        $this->assertEquals(0, $stat->getRebateJDBSlotsCount());
        $this->assertEquals(0, $stat->getRebateJDBArcadeAmount());
        $this->assertEquals(0, $stat->getRebateJDBArcadeCount());
        $this->assertEquals(0, $stat->getRebateJDBFishingAmount());
        $this->assertEquals(0, $stat->getRebateJDBFishingCount());
        $this->assertEquals(0, $stat->getRebateAgslotSlotsAmount());
        $this->assertEquals(0, $stat->getRebateAgslotSlotsCount());
        $this->assertEquals(0, $stat->getRebateAgslotTableAmount());
        $this->assertEquals(0, $stat->getRebateAgslotTableCount());
        $this->assertEquals(0, $stat->getRebateAgslotJackpotAmount());
        $this->assertEquals(0, $stat->getRebateAgslotJackpotCount());
        $this->assertEquals(0, $stat->getRebateAgslotFishingAmount());
        $this->assertEquals(0, $stat->getRebateAgslotFishingCount());
        $this->assertEquals(0, $stat->getRebateAgslotPokerAmount());
        $this->assertEquals(0, $stat->getRebateAgslotPokerCount());
        $this->assertEquals(0, $stat->getRebateMWSlotsAmount());
        $this->assertEquals(0, $stat->getRebateMWSlotsCount());
        $this->assertEquals(0, $stat->getRebateMWTableAmount());
        $this->assertEquals(0, $stat->getRebateMWTableCount());
        $this->assertEquals(0, $stat->getRebateMWArcadeAmount());
        $this->assertEquals(0, $stat->getRebateMWArcadeCount());
        $this->assertEquals(0, $stat->getRebateMWFishingAmount());
        $this->assertEquals(0, $stat->getRebateMWFishingCount());
        $this->assertEquals(0, $stat->getRebateINSportAmount());
        $this->assertEquals(0, $stat->getRebateINSportCount());
        $this->assertEquals(0, $stat->getRebateRTSlotsAmount());
        $this->assertEquals(0, $stat->getRebateRTSlotsCount());
        $this->assertEquals(0, $stat->getRebateRTTableAmount());
        $this->assertEquals(0, $stat->getRebateRTTableCount());
        $this->assertEquals(0, $stat->getRebateSGSlotsAmount());
        $this->assertEquals(0, $stat->getRebateSGSlotsCount());
        $this->assertEquals(0, $stat->getRebateSGTableAmount());
        $this->assertEquals(0, $stat->getRebateSGTableCount());
        $this->assertEquals(0, $stat->getRebateSGArcadeAmount());
        $this->assertEquals(0, $stat->getRebateSGArcadeCount());
        $this->assertEquals(0, $stat->getRebateSGJackpotAmount());
        $this->assertEquals(0, $stat->getRebateSGJackpotCount());
        $this->assertEquals(0, $stat->getRebateVRVrAmount());
        $this->assertEquals(0, $stat->getRebateVRVrCount());
        $this->assertEquals(0, $stat->getRebateVRLottoAmount());
        $this->assertEquals(0, $stat->getRebateVRLottoCount());
        $this->assertEquals(0, $stat->getRebateVRMarksixAmount());
        $this->assertEquals(0, $stat->getRebateVRMarksixCount());
        $this->assertEquals(0, $stat->getRebatePT2SlotsAmount());
        $this->assertEquals(0, $stat->getRebatePT2SlotsCount());
        $this->assertEquals(0, $stat->getRebatePT2JackpotAmount());
        $this->assertEquals(0, $stat->getRebatePT2JackpotCount());
        $this->assertEquals(0, $stat->getRebatePT2FishingAmount());
        $this->assertEquals(0, $stat->getRebatePT2FishingCount());
        $this->assertEquals(0, $stat->getRebatePT2TableAmount());
        $this->assertEquals(0, $stat->getRebatePT2TableCount());
        $this->assertEquals(0, $stat->getRebatePT2FeatureAmount());
        $this->assertEquals(0, $stat->getRebatePT2FeatureCount());
        $this->assertEquals(0, $stat->getRebateBngSlotsAmount());
        $this->assertEquals(0, $stat->getRebateBngSlotsCount());
        $this->assertEquals(0, $stat->getRebateEVOAmount());
        $this->assertEquals(0, $stat->getRebateEVOCount());
        $this->assertEquals(0, $stat->getRebateGNSJackpotAmount());
        $this->assertEquals(0, $stat->getRebateGNSJackpotCount());
        $this->assertEquals(0, $stat->getRebateGNSFeatureAmount());
        $this->assertEquals(0, $stat->getRebateGNSFeatureCount());
        $this->assertEquals(0, $stat->getRebateKYAmount());
        $this->assertEquals(0, $stat->getRebateKYCount());
        $this->assertEquals(0, $stat->getrebateGNSTableGamesAmount());
        $this->assertEquals(0, $stat->getrebateGNSTableGamesCount());
        $this->assertEquals(0, $stat->getRebateAmount());
        $this->assertEquals(0, $stat->getRebateCount());

        $stat->setId(11);
        $stat->setCurrency(156);
        $stat->setDomain(2);
        $stat->setParentId(7);
        $stat->setRebateBallAmount(1);
        $stat->setRebateBallCount(1);
        $stat->setRebateKenoAmount(1);
        $stat->setRebateKenoCount(1);
        $stat->setRebateVideoAmount(1);
        $stat->setRebateVideoCount(1);
        $stat->setRebateSportAmount(1);
        $stat->setRebateSportCount(1);
        $stat->setRebateProbAmount(1);
        $stat->setRebateProbCount(1);
        $stat->setRebateLotteryAmount(1);
        $stat->setRebateLotteryCount(1);
        $stat->setRebateBBplayAmount(1);
        $stat->setRebateBBplayCount(1);
        $stat->setRebateOfferAmount(1);
        $stat->setRebateOfferCount(1);
        $stat->setRebateBBVideoAmount(1);
        $stat->setRebateBBVideoCount(1);
        $stat->setRebateTTVideoAmount(1);
        $stat->setRebateTTVideoCount(1);
        $stat->setRebateArmVideoAmount(1);
        $stat->setRebateArmVideoCount(1);
        $stat->setRebateXpjVideoAmount(1);
        $stat->setRebateXpjVideoCount(1);
        $stat->setRebateYfVideoAmount(1);
        $stat->setRebateYfVideoCount(1);
        $stat->setRebate3dAmount(1);
        $stat->setRebate3dCount(1);
        $stat->setRebateBattleAmount(1);
        $stat->setRebateBattleCount(1);
        $stat->setRebateVirtualAmount(1);
        $stat->setRebateVirtualCount(1);
        $stat->setRebateVipVideoAmount(1);
        $stat->setRebateVipVideoCount(1);
        $stat->setRebateAgVideoAmount(1);
        $stat->setRebateAgVideoCount(1);
        $stat->setRebatePTAmount(1);
        $stat->setRebatePTCount(1);
        $stat->setRebateLTAmount(1);
        $stat->setRebateLTCount(1);
        $stat->setRebateMIAmount(1);
        $stat->setRebateMICount(1);
        $stat->setRebateABAmount(1);
        $stat->setRebateABCount(1);
        $stat->setRebateMGAmount(1);
        $stat->setRebateMGCount(1);
        $stat->setRebateOGAmount(1);
        $stat->setRebateOGCount(1);
        $stat->setRebateSBAmount(1);
        $stat->setRebateSBCount(1);
        $stat->setRebateGDAmount(1);
        $stat->setRebateGDCount(1);
        $stat->setRebateSAAmount(1);
        $stat->setRebateSACount(1);
        $stat->setRebateGnsAmount(1);
        $stat->setRebateGnsCount(1);
        $stat->setRebateMGJackpotAmount(1);
        $stat->setRebateMGJackpotCount(1);
        $stat->setRebateMGSlotsAmount(1);
        $stat->setRebateMGSlotsCount(1);
        $stat->setRebateMGFeatureAmount(1);
        $stat->setRebateMGFeatureCount(1);
        $stat->setRebateMGTableAmount(1);
        $stat->setRebateMGTableCount(1);
        $stat->setRebateMGMobileAmount(1);
        $stat->setRebateMGMobileCount(1);
        $stat->setRebateISBAmount(1);
        $stat->setRebateISBCount(1);
        $stat->setRebateBBFGAmount(1);
        $stat->setRebateBBFGCount(1);
        $stat->setRebateBCAmount(1);
        $stat->setRebateBCCount(1);
        $stat->setRebateBBSlotsAmount(1);
        $stat->setRebateBBSlotsCount(1);
        $stat->setRebateBBTableAmount(1);
        $stat->setRebateBBTableCount(1);
        $stat->setRebateBBArcadeAmount(1);
        $stat->setRebateBBArcadeCount(1);
        $stat->setRebateBBScratchAmount(1);
        $stat->setRebateBBScratchCount(1);
        $stat->setRebateBBFeatureAmount(1);
        $stat->setRebateBBFeatureCount(1);
        $stat->setRebateBBTreasureAmount(1);
        $stat->setRebateBBTreasureCount(1);
        $stat->setRebateISBSlotsAmount(1);
        $stat->setRebateISBSlotsCount(1);
        $stat->setRebateISBTableAmount(1);
        $stat->setRebateISBTableCount(1);
        $stat->setRebateISBJackpotAmount(1);
        $stat->setRebateISBJackpotCount(1);
        $stat->setRebateISBPokerAmount(1);
        $stat->setRebateISBPokerCount(1);
        $stat->setRebate888FishingAmount(1);
        $stat->setRebate888FishingCount(1);
        $stat->setRebatePTSlotsAmount(1);
        $stat->setRebatePTSlotsCount(1);
        $stat->setRebatePTTableAmount(1);
        $stat->setRebatePTTableCount(1);
        $stat->setRebatePTJackpotAmount(1);
        $stat->setRebatePTJackpotCount(1);
        $stat->setRebatePTArcadeAmount(1);
        $stat->setRebatePTArcadeCount(1);
        $stat->setRebatePTScratchAmount(1);
        $stat->setRebatePTScratchCount(1);
        $stat->setRebatePTPokerAmount(1);
        $stat->setRebatePTPokerCount(1);
        $stat->setRebatePTUnclassifiedAmount(1);
        $stat->setRebatePTUnclassifiedCount(1);
        $stat->setRebateGOGAmount(1);
        $stat->setRebateGOGCount(1);
        $stat->setRebateSk1Amount(1);
        $stat->setRebateSk1Count(1);
        $stat->setRebateSk2Amount(1);
        $stat->setRebateSk2Count(1);
        $stat->setRebateSk3Amount(1);
        $stat->setRebateSk3Count(1);
        $stat->setRebateSk4Amount(1);
        $stat->setRebateSk4Count(1);
        $stat->setRebateSk5Amount(1);
        $stat->setRebateSk5Count(1);
        $stat->setRebateSk6Amount(1);
        $stat->setRebateSk6Count(1);
        $stat->setRebateHBSlotsAmount(1);
        $stat->setRebateHBSlotsCount(1);
        $stat->setRebateHBTableAmount(1);
        $stat->setRebateHBTableCount(1);
        $stat->setRebateHBPokerAmount(1);
        $stat->setRebateHBPokerCount(1);
        $stat->setRebateBGLiveAmount(1);
        $stat->setRebateBGLiveCount(1);
        $stat->setRebateFishingMasterAmount(1);
        $stat->setRebateFishingMasterCount(1);
        $stat->setRebatePPSlotsAmount(1);
        $stat->setRebatePPSlotsCount(1);
        $stat->setRebatePPTableAmount(1);
        $stat->setRebatePPTableCount(1);
        $stat->setRebatePPJackpotAmount(1);
        $stat->setRebatePPJackpotCount(1);
        $stat->setRebatePPFeatureAmount(1);
        $stat->setRebatePPFeatureCount(1);
        $stat->setRebatePTFishingAmount(1);
        $stat->setRebatePTFishingCount(1);
        $stat->setRebateGNSSlotsAmount(1);
        $stat->setRebateGNSSlotsCount(1);
        $stat->setRebateGNSFishingAmount(1);
        $stat->setRebateGNSFishingCount(1);
        $stat->setRebateJDBSlotsAmount(1);
        $stat->setRebateJDBSlotsCount(1);
        $stat->setRebateJDBArcadeAmount(1);
        $stat->setRebateJDBArcadeCount(1);
        $stat->setRebateJDBFishingAmount(1);
        $stat->setRebateJDBFishingCount(1);
        $stat->setRebateAgslotSlotsAmount(1);
        $stat->setRebateAgslotSlotsCount(1);
        $stat->setRebateAgslotTableAmount(1);
        $stat->setRebateAgslotTableCount(1);
        $stat->setRebateAgslotJackpotAmount(1);
        $stat->setRebateAgslotJackpotCount(1);
        $stat->setRebateAgslotFishingAmount(1);
        $stat->setRebateAgslotFishingCount(1);
        $stat->setRebateAgslotPokerAmount(1);
        $stat->setRebateAgslotPokerCount(1);
        $stat->setRebateMWSlotsAmount(1);
        $stat->setRebateMWSlotsCount(1);
        $stat->setRebateMWTableAmount(1);
        $stat->setRebateMWTableCount(1);
        $stat->setRebateMWArcadeAmount(1);
        $stat->setRebateMWArcadeCount(1);
        $stat->setRebateMWFishingAmount(1);
        $stat->setRebateMWFishingCount(1);
        $stat->setRebateINSportAmount(1);
        $stat->setRebateINSportCount(1);
        $stat->setRebateRTSlotsAmount(1);
        $stat->setRebateRTSlotsCount(1);
        $stat->setRebateRTTableAmount(1);
        $stat->setRebateRTTableCount(1);
        $stat->setRebateSGSlotsAmount(1);
        $stat->setRebateSGSlotsCount(1);
        $stat->setRebateSGTableAmount(1);
        $stat->setRebateSGTableCount(1);
        $stat->setRebateSGJackpotAmount(1);
        $stat->setRebateSGJackpotCount(1);
        $stat->setRebateSGArcadeAmount(1);
        $stat->setRebateSGArcadeCount(1);
        $stat->setRebateVRVrAmount(1);
        $stat->setRebateVRVrCount(1);
        $stat->setRebateVRLottoAmount(1);
        $stat->setRebateVRLottoCount(1);
        $stat->setRebateVRMarksixAmount(1);
        $stat->setRebateVRMarksixCount(1);
        $stat->setRebatePT2SlotsAmount(1);
        $stat->setRebatePT2SlotsCount(1);
        $stat->setRebatePT2JackpotAmount(1);
        $stat->setRebatePT2JackpotCount(1);
        $stat->setRebatePT2FishingAmount(1);
        $stat->setRebatePT2FishingCount(1);
        $stat->setRebatePT2TableAmount(1);
        $stat->setRebatePT2TableCount(1);
        $stat->setRebatePT2FeatureAmount(1);
        $stat->setRebatePT2FeatureCount(1);
        $stat->setRebateBngSlotsAmount(1);
        $stat->setRebateBngSlotsCount(1);
        $stat->setRebateEVOAmount(1);
        $stat->setRebateEVOCount(1);
        $stat->setRebateGNSJackpotAmount(1);
        $stat->setRebateGNSJackpotCount(1);
        $stat->setRebateGNSFeatureAmount(1);
        $stat->setRebateGNSFeatureCount(1);
        $stat->setRebateKYAmount(1);
        $stat->setRebateKYCount(1);
        $stat->setRebateGNSTableGamesAmount(1);
        $stat->setRebateGNSTableGamesCount(1);
        $stat->setRebateAmount(1);
        $stat->setRebateCount(1);

        $this->assertEquals(11, $stat->getId());
        $this->assertEquals(156, $stat->getCurrency());
        $this->assertEquals(2, $stat->getDomain());
        $this->assertEquals(7, $stat->getParentId());
        $this->assertEquals(1, $stat->getRebateBallAmount());
        $this->assertEquals(1, $stat->getRebateBallCount());
        $this->assertEquals(1, $stat->getRebateKenoAmount());
        $this->assertEquals(1, $stat->getRebateKenoCount());
        $this->assertEquals(1, $stat->getRebateVideoAmount());
        $this->assertEquals(1, $stat->getRebateVideoCount());
        $this->assertEquals(1, $stat->getRebateSportAmount());
        $this->assertEquals(1, $stat->getRebateSportCount());
        $this->assertEquals(1, $stat->getRebateProbAmount());
        $this->assertEquals(1, $stat->getRebateProbCount());
        $this->assertEquals(1, $stat->getRebateLotteryAmount());
        $this->assertEquals(1, $stat->getRebateLotteryCount());
        $this->assertEquals(1, $stat->getRebateBBplayAmount());
        $this->assertEquals(1, $stat->getRebateBBplayCount());
        $this->assertEquals(1, $stat->getRebateOfferAmount());
        $this->assertEquals(1, $stat->getRebateOfferCount());
        $this->assertEquals(1, $stat->getRebateBBVideoAmount());
        $this->assertEquals(1, $stat->getRebateBBVideoCount());
        $this->assertEquals(1, $stat->getRebateTTVideoAmount());
        $this->assertEquals(1, $stat->getRebateTTVideoCount());
        $this->assertEquals(1, $stat->getRebateArmVideoAmount());
        $this->assertEquals(1, $stat->getRebateArmVideoCount());
        $this->assertEquals(1, $stat->getRebateXpjVideoAmount());
        $this->assertEquals(1, $stat->getRebateXpjVideoCount());
        $this->assertEquals(1, $stat->getRebateYfVideoAmount());
        $this->assertEquals(1, $stat->getRebateYfVideoCount());
        $this->assertEquals(1, $stat->getRebate3dAmount());
        $this->assertEquals(1, $stat->getRebate3dCount());
        $this->assertEquals(1, $stat->getRebateBattleAmount());
        $this->assertEquals(1, $stat->getRebateBattleCount());
        $this->assertEquals(1, $stat->getRebateVirtualAmount());
        $this->assertEquals(1, $stat->getRebateVirtualCount());
        $this->assertEquals(1, $stat->getRebateVipVideoAmount());
        $this->assertEquals(1, $stat->getRebateVipVideoCount());
        $this->assertEquals(1, $stat->getRebateAgVideoAmount());
        $this->assertEquals(1, $stat->getRebateAgVideoCount());
        $this->assertEquals(1, $stat->getRebatePTAmount());
        $this->assertEquals(1, $stat->getRebatePTCount());
        $this->assertEquals(1, $stat->getRebateLTAmount());
        $this->assertEquals(1, $stat->getRebateLTCount());
        $this->assertEquals(1, $stat->getRebateMIAmount());
        $this->assertEquals(1, $stat->getRebateMICount());
        $this->assertEquals(1, $stat->getRebateABAmount());
        $this->assertEquals(1, $stat->getRebateABCount());
        $this->assertEquals(1, $stat->getRebateMGAmount());
        $this->assertEquals(1, $stat->getRebateMGCount());
        $this->assertEquals(1, $stat->getRebateOGAmount());
        $this->assertEquals(1, $stat->getRebateOGCount());
        $this->assertEquals(1, $stat->getRebateSBAmount());
        $this->assertEquals(1, $stat->getRebateSBCount());
        $this->assertEquals(1, $stat->getRebateGDAmount());
        $this->assertEquals(1, $stat->getRebateGDCount());
        $this->assertEquals(1, $stat->getRebateSAAmount());
        $this->assertEquals(1, $stat->getRebateSACount());
        $this->assertEquals(1, $stat->getRebateGnsAmount());
        $this->assertEquals(1, $stat->getRebateGnsCount());
        $this->assertEquals(1, $stat->getRebateMGJackpotAmount());
        $this->assertEquals(1, $stat->getRebateMGJackpotCount());
        $this->assertEquals(1, $stat->getRebateMGSlotsAmount());
        $this->assertEquals(1, $stat->getRebateMGSlotsCount());
        $this->assertEquals(1, $stat->getRebateMGFeatureAmount());
        $this->assertEquals(1, $stat->getRebateMGFeatureCount());
        $this->assertEquals(1, $stat->getRebateMGTableAmount());
        $this->assertEquals(1, $stat->getRebateMGTableCount());
        $this->assertEquals(1, $stat->getRebateMGMobileAmount());
        $this->assertEquals(1, $stat->getRebateMGMobileCount());
        $this->assertEquals(1, $stat->getRebateISBAmount());
        $this->assertEquals(1, $stat->getRebateISBCount());
        $this->assertEquals(1, $stat->getRebateBBFGAmount());
        $this->assertEquals(1, $stat->getRebateBBFGCount());
        $this->assertEquals(1, $stat->getRebateBCAmount());
        $this->assertEquals(1, $stat->getRebateBCCount());
        $this->assertEquals(1, $stat->getRebateBBSlotsAmount());
        $this->assertEquals(1, $stat->getRebateBBSlotsCount());
        $this->assertEquals(1, $stat->getRebateBBTableAmount());
        $this->assertEquals(1, $stat->getRebateBBTableCount());
        $this->assertEquals(1, $stat->getRebateBBArcadeAmount());
        $this->assertEquals(1, $stat->getRebateBBArcadeCount());
        $this->assertEquals(1, $stat->getRebateBBScratchAmount());
        $this->assertEquals(1, $stat->getRebateBBScratchCount());
        $this->assertEquals(1, $stat->getRebateBBFeatureAmount());
        $this->assertEquals(1, $stat->getRebateBBFeatureCount());
        $this->assertEquals(1, $stat->getRebateBBTreasureAmount());
        $this->assertEquals(1, $stat->getRebateBBTreasureCount());
        $this->assertEquals(1, $stat->getRebateISBSlotsAmount());
        $this->assertEquals(1, $stat->getRebateISBSlotsCount());
        $this->assertEquals(1, $stat->getRebateISBTableAmount());
        $this->assertEquals(1, $stat->getRebateISBTableCount());
        $this->assertEquals(1, $stat->getRebateISBJackpotAmount());
        $this->assertEquals(1, $stat->getRebateISBJackpotCount());
        $this->assertEquals(1, $stat->getRebateISBPokerAmount());
        $this->assertEquals(1, $stat->getRebateISBPokerCount());
        $this->assertEquals(1, $stat->getRebate888FishingAmount());
        $this->assertEquals(1, $stat->getRebate888FishingCount());
        $this->assertEquals(1, $stat->getRebatePTSlotsAmount());
        $this->assertEquals(1, $stat->getRebatePTSlotsCount());
        $this->assertEquals(1, $stat->getRebatePTTableAmount());
        $this->assertEquals(1, $stat->getRebatePTTableCount());
        $this->assertEquals(1, $stat->getRebatePTJackpotAmount());
        $this->assertEquals(1, $stat->getRebatePTJackpotCount());
        $this->assertEquals(1, $stat->getRebatePTArcadeAmount());
        $this->assertEquals(1, $stat->getRebatePTArcadeCount());
        $this->assertEquals(1, $stat->getRebatePTScratchAmount());
        $this->assertEquals(1, $stat->getRebatePTScratchCount());
        $this->assertEquals(1, $stat->getRebatePTPokerAmount());
        $this->assertEquals(1, $stat->getRebatePTPokerCount());
        $this->assertEquals(1, $stat->getRebatePTUnclassifiedAmount());
        $this->assertEquals(1, $stat->getRebatePTUnclassifiedCount());
        $this->assertEquals(1, $stat->getRebateGOGAmount());
        $this->assertEquals(1, $stat->getRebateGOGCount());
        $this->assertEquals(1, $stat->getRebateSk1Amount());
        $this->assertEquals(1, $stat->getRebateSk1Count());
        $this->assertEquals(1, $stat->getRebateSk2Amount());
        $this->assertEquals(1, $stat->getRebateSk2Count());
        $this->assertEquals(1, $stat->getRebateSk3Amount());
        $this->assertEquals(1, $stat->getRebateSk3Count());
        $this->assertEquals(1, $stat->getRebateSk4Amount());
        $this->assertEquals(1, $stat->getRebateSk4Count());
        $this->assertEquals(1, $stat->getRebateSk5Amount());
        $this->assertEquals(1, $stat->getRebateSk5Count());
        $this->assertEquals(1, $stat->getRebateSk6Amount());
        $this->assertEquals(1, $stat->getRebateSk6Count());
        $this->assertEquals(1, $stat->getRebateHBSlotsAmount());
        $this->assertEquals(1, $stat->getRebateHBSlotsCount());
        $this->assertEquals(1, $stat->getRebateHBTableAmount());
        $this->assertEquals(1, $stat->getRebateHBTableCount());
        $this->assertEquals(1, $stat->getRebateHBPokerAmount());
        $this->assertEquals(1, $stat->getRebateHBPokerCount());
        $this->assertEquals(1, $stat->getRebateBGLiveAmount());
        $this->assertEquals(1, $stat->getRebateBGLiveCount());
        $this->assertEquals(1, $stat->getRebateFishingMasterAmount());
        $this->assertEquals(1, $stat->getRebateFishingMasterCount());
        $this->assertEquals(1, $stat->getRebatePPSlotsAmount());
        $this->assertEquals(1, $stat->getRebatePPSlotsCount());
        $this->assertEquals(1, $stat->getRebatePPTableAmount());
        $this->assertEquals(1, $stat->getRebatePPTableCount());
        $this->assertEquals(1, $stat->getRebatePPJackpotAmount());
        $this->assertEquals(1, $stat->getRebatePPJackpotCount());
        $this->assertEquals(1, $stat->getRebatePPFeatureAmount());
        $this->assertEquals(1, $stat->getRebatePPFeatureCount());
        $this->assertEquals(1, $stat->getRebatePTFishingAmount());
        $this->assertEquals(1, $stat->getRebatePTFishingCount());
        $this->assertEquals(1, $stat->getRebateGNSSlotsAmount());
        $this->assertEquals(1, $stat->getRebateGNSSlotsCount());
        $this->assertEquals(1, $stat->getRebateGNSFishingAmount());
        $this->assertEquals(1, $stat->getRebateGNSFishingCount());
        $this->assertEquals(1, $stat->getRebateJDBSlotsAmount());
        $this->assertEquals(1, $stat->getRebateJDBSlotsCount());
        $this->assertEquals(1, $stat->getRebateJDBArcadeAmount());
        $this->assertEquals(1, $stat->getRebateJDBArcadeCount());
        $this->assertEquals(1, $stat->getRebateJDBFishingAmount());
        $this->assertEquals(1, $stat->getRebateJDBFishingCount());
        $this->assertEquals(1, $stat->getRebateAgslotSlotsAmount());
        $this->assertEquals(1, $stat->getRebateAgslotSlotsCount());
        $this->assertEquals(1, $stat->getRebateAgslotTableAmount());
        $this->assertEquals(1, $stat->getRebateAgslotTableCount());
        $this->assertEquals(1, $stat->getRebateAgslotJackpotAmount());
        $this->assertEquals(1, $stat->getRebateAgslotJackpotCount());
        $this->assertEquals(1, $stat->getRebateAgslotFishingAmount());
        $this->assertEquals(1, $stat->getRebateAgslotFishingCount());
        $this->assertEquals(1, $stat->getRebateAgslotPokerAmount());
        $this->assertEquals(1, $stat->getRebateAgslotPokerCount());
        $this->assertEquals(1, $stat->getRebateMWSlotsAmount());
        $this->assertEquals(1, $stat->getRebateMWSlotsCount());
        $this->assertEquals(1, $stat->getRebateMWTableAmount());
        $this->assertEquals(1, $stat->getRebateMWTableCount());
        $this->assertEquals(1, $stat->getRebateMWArcadeAmount());
        $this->assertEquals(1, $stat->getRebateMWArcadeCount());
        $this->assertEquals(1, $stat->getRebateMWFishingAmount());
        $this->assertEquals(1, $stat->getRebateMWFishingCount());
        $this->assertEquals(1, $stat->getRebateINSportAmount());
        $this->assertEquals(1, $stat->getRebateINSportCount());
        $this->assertEquals(1, $stat->getRebateRTSlotsAmount());
        $this->assertEquals(1, $stat->getRebateRTSlotsCount());
        $this->assertEquals(1, $stat->getRebateRTTableAmount());
        $this->assertEquals(1, $stat->getRebateRTTableCount());
        $this->assertEquals(1, $stat->getRebateSGSlotsAmount());
        $this->assertEquals(1, $stat->getRebateSGSlotsCount());
        $this->assertEquals(1, $stat->getRebateSGTableAmount());
        $this->assertEquals(1, $stat->getRebateSGTableCount());
        $this->assertEquals(1, $stat->getRebateSGJackpotAmount());
        $this->assertEquals(1, $stat->getRebateSGJackpotCount());
        $this->assertEquals(1, $stat->getRebateSGArcadeAmount());
        $this->assertEquals(1, $stat->getRebateSGArcadeCount());
        $this->assertEquals(1, $stat->getRebateVRVrAmount());
        $this->assertEquals(1, $stat->getRebateVRVrCount());
        $this->assertEquals(1, $stat->getRebateVRLottoAmount());
        $this->assertEquals(1, $stat->getRebateVRLottoCount());
        $this->assertEquals(1, $stat->getRebateVRMarksixAmount());
        $this->assertEquals(1, $stat->getRebateVRMarksixCount());
        $this->assertEquals(1, $stat->getRebatePT2SlotsAmount());
        $this->assertEquals(1, $stat->getRebatePT2SlotsCount());
        $this->assertEquals(1, $stat->getRebatePT2JackpotAmount());
        $this->assertEquals(1, $stat->getRebatePT2JackpotCount());
        $this->assertEquals(1, $stat->getRebatePT2FishingAmount());
        $this->assertEquals(1, $stat->getRebatePT2FishingCount());
        $this->assertEquals(1, $stat->getRebatePT2TableAmount());
        $this->assertEquals(1, $stat->getRebatePT2TableCount());
        $this->assertEquals(1, $stat->getRebatePT2FeatureAmount());
        $this->assertEquals(1, $stat->getRebatePT2FeatureCount());
        $this->assertEquals(1, $stat->getRebateBngSlotsAmount());
        $this->assertEquals(1, $stat->getRebateBngSlotsCount());
        $this->assertEquals(1, $stat->getRebateEVOAmount());
        $this->assertEquals(1, $stat->getRebateEVOCount());
        $this->assertEquals(1, $stat->getRebateGNSJackpotAmount());
        $this->assertEquals(1, $stat->getRebateGNSJackpotCount());
        $this->assertEquals(1, $stat->getRebateGNSFeatureAmount());
        $this->assertEquals(1, $stat->getRebateGNSFeatureCount());
        $this->assertEquals(1, $stat->getRebateKYAmount());
        $this->assertEquals(1, $stat->getRebateKYCount());
        $this->assertEquals(1, $stat->getrebateGNSTableGamesAmount());
        $this->assertEquals(1, $stat->getrebateGNSTableGamesCount());
        $this->assertEquals(1, $stat->getRebateAmount());
        $this->assertEquals(1, $stat->getRebateCount());

        $stat->addRebateBallAmount(1);
        $stat->addRebateBallCount(1);
        $stat->addRebateKenoAmount(1);
        $stat->addRebateKenoCount(1);
        $stat->addRebateVideoAmount(1);
        $stat->addRebateVideoCount(1);
        $stat->addRebateSportAmount(1);
        $stat->addRebateSportCount(1);
        $stat->addRebateProbAmount(1);
        $stat->addRebateProbCount(1);
        $stat->addRebateLotteryAmount(1);
        $stat->addRebateLotteryCount(1);
        $stat->addRebateBBplayAmount(1);
        $stat->addRebateBBplayCount(1);
        $stat->addRebateOfferAmount(1);
        $stat->addRebateOfferCount(1);
        $stat->addRebateBBVideoAmount(1);
        $stat->addRebateBBVideoCount(1);
        $stat->addRebateTTVideoAmount(1);
        $stat->addRebateTTVideoCount(1);
        $stat->addRebateArmVideoAmount(1);
        $stat->addRebateArmVideoCount(1);
        $stat->addRebateXpjVideoAmount(1);
        $stat->addRebateXpjVideoCount(1);
        $stat->addRebateYfVideoAmount(1);
        $stat->addRebateYfVideoCount(1);
        $stat->addRebate3dAmount(1);
        $stat->addRebate3dCount(1);
        $stat->addRebateBattleAmount(1);
        $stat->addRebateBattleCount(1);
        $stat->addRebateVirtualAmount(1);
        $stat->addRebateVirtualCount(1);
        $stat->addRebateVipVideoAmount(1);
        $stat->addRebateVipVideoCount(1);
        $stat->addRebateAgVideoAmount(1);
        $stat->addRebateAgVideoCount(1);
        $stat->addRebatePTAmount(1);
        $stat->addRebatePTCount(1);
        $stat->addRebateLTAmount(1);
        $stat->addRebateLTCount(1);
        $stat->addRebateMIAmount(1);
        $stat->addRebateMICount(1);
        $stat->addRebateABAmount(1);
        $stat->addRebateABCount(1);
        $stat->addRebateMGAmount(1);
        $stat->addRebateMGCount(1);
        $stat->addRebateOGAmount(1);
        $stat->addRebateOGCount(1);
        $stat->addRebateSBAmount(1);
        $stat->addRebateSBCount(1);
        $stat->addRebateGDAmount(1);
        $stat->addRebateGDCount(1);
        $stat->addRebateSAAmount(1);
        $stat->addRebateSACount(1);
        $stat->addRebateGnsAmount(1);
        $stat->addRebateGnsCount(1);
        $stat->addRebateMGJackpotAmount(1);
        $stat->addRebateMGJackpotCount(1);
        $stat->addRebateMGSlotsAmount(1);
        $stat->addRebateMGSlotsCount(1);
        $stat->addRebateMGFeatureAmount(1);
        $stat->addRebateMGFeatureCount(1);
        $stat->addRebateMGTableAmount(1);
        $stat->addRebateMGTableCount(1);
        $stat->addRebateMGMobileAmount(1);
        $stat->addRebateMGMobileCount(1);
        $stat->addRebateISBAmount(1);
        $stat->addRebateISBCount(1);
        $stat->addRebateBBFGAmount(1);
        $stat->addRebateBBFGCount(1);
        $stat->addRebateBCAmount(1);
        $stat->addRebateBCCount(1);
        $stat->addRebateBBSlotsAmount(1);
        $stat->addRebateBBSlotsCount(1);
        $stat->addRebateBBTableAmount(1);
        $stat->addRebateBBTableCount(1);
        $stat->addRebateBBArcadeAmount(1);
        $stat->addRebateBBArcadeCount(1);
        $stat->addRebateBBScratchAmount(1);
        $stat->addRebateBBScratchCount(1);
        $stat->addRebateBBFeatureAmount(1);
        $stat->addRebateBBFeatureCount(1);
        $stat->addRebateBBTreasureAmount(1);
        $stat->addRebateBBTreasureCount(1);
        $stat->addRebateISBSlotsAmount(1);
        $stat->addRebateISBSlotsCount(1);
        $stat->addRebateISBTableAmount(1);
        $stat->addRebateISBTableCount(1);
        $stat->addRebateISBJackpotAmount(1);
        $stat->addRebateISBJackpotCount(1);
        $stat->addRebateISBPokerAmount(1);
        $stat->addRebateISBPokerCount(1);
        $stat->addRebate888FishingAmount(1);
        $stat->addRebate888FishingCount(1);
        $stat->addRebatePTSlotsAmount(1);
        $stat->addRebatePTSlotsCount(1);
        $stat->addRebatePTTableAmount(1);
        $stat->addRebatePTTableCount(1);
        $stat->addRebatePTJackpotAmount(1);
        $stat->addRebatePTJackpotCount(1);
        $stat->addRebatePTArcadeAmount(1);
        $stat->addRebatePTArcadeCount(1);
        $stat->addRebatePTScratchAmount(1);
        $stat->addRebatePTScratchCount(1);
        $stat->addRebatePTPokerAmount(1);
        $stat->addRebatePTPokerCount(1);
        $stat->addRebatePTUnclassifiedAmount(1);
        $stat->addRebatePTUnclassifiedCount(1);
        $stat->addRebateGOGAmount(1);
        $stat->addRebateGOGCount(1);
        $stat->addRebateSk1Amount(1);
        $stat->addRebateSk1Count(1);
        $stat->addRebateSk2Amount(1);
        $stat->addRebateSk2Count(1);
        $stat->addRebateSk3Amount(1);
        $stat->addRebateSk3Count(1);
        $stat->addRebateSk4Amount(1);
        $stat->addRebateSk4Count(1);
        $stat->addRebateSk5Amount(1);
        $stat->addRebateSk5Count(1);
        $stat->addRebateSk6Amount(1);
        $stat->addRebateSk6Count(1);
        $stat->addRebateHBSlotsAmount(1);
        $stat->addRebateHBSlotsCount(1);
        $stat->addRebateHBTableAmount(1);
        $stat->addRebateHBTableCount(1);
        $stat->addRebateHBPokerAmount(1);
        $stat->addRebateHBPokerCount(1);
        $stat->addRebateBGLiveAmount(1);
        $stat->addRebateBGLiveCount(1);
        $stat->addRebateFishingMasterAmount(1);
        $stat->addRebateFishingMasterCount(1);
        $stat->addRebatePPSlotsAmount(1);
        $stat->addRebatePPSlotsCount(1);
        $stat->addRebatePPTableAmount(1);
        $stat->addRebatePPTableCount(1);
        $stat->addRebatePPJackpotAmount(1);
        $stat->addRebatePPJackpotCount(1);
        $stat->addRebatePPFeatureAmount(1);
        $stat->addRebatePPFeatureCount(1);
        $stat->addRebatePTFishingAmount(1);
        $stat->addRebatePTFishingCount(1);
        $stat->addRebateGNSSlotsAmount(1);
        $stat->addRebateGNSSlotsCount(1);
        $stat->addRebateGNSFishingAmount(1);
        $stat->addRebateGNSFishingCount(1);
        $stat->addRebateJDBSlotsAmount(1);
        $stat->addRebateJDBSlotsCount(1);
        $stat->addRebateJDBArcadeAmount(1);
        $stat->addRebateJDBArcadeCount(1);
        $stat->addRebateJDBFishingAmount(1);
        $stat->addRebateJDBFishingCount(1);
        $stat->addRebateAgslotSlotsAmount(1);
        $stat->addRebateAgslotSlotsCount(1);
        $stat->addRebateAgslotTableAmount(1);
        $stat->addRebateAgslotTableCount(1);
        $stat->addRebateAgslotJackpotAmount(1);
        $stat->addRebateAgslotJackpotCount(1);
        $stat->addRebateAgslotFishingAmount(1);
        $stat->addRebateAgslotFishingCount(1);
        $stat->addRebateAgslotPokerAmount(1);
        $stat->addRebateAgslotPokerCount(1);
        $stat->addRebateMWSlotsAmount(1);
        $stat->addRebateMWSlotsCount(1);
        $stat->addRebateMWTableAmount(1);
        $stat->addRebateMWTableCount(1);
        $stat->addRebateMWArcadeAmount(1);
        $stat->addRebateMWArcadeCount(1);
        $stat->addRebateMWFishingAmount(1);
        $stat->addRebateMWFishingCount(1);
        $stat->addRebateINSportAmount(1);
        $stat->addRebateINSportCount(1);
        $stat->addRebateRTSlotsAmount(1);
        $stat->addRebateRTSlotsCount(1);
        $stat->addRebateRTTableAmount(1);
        $stat->addRebateRTTableCount(1);
        $stat->addRebateSGSlotsAmount(1);
        $stat->addRebateSGSlotsCount(1);
        $stat->addRebateSGTableAmount(1);
        $stat->addRebateSGTableCount(1);
        $stat->addRebateSGJackpotAmount(1);
        $stat->addRebateSGJackpotCount(1);
        $stat->addRebateSGArcadeAmount(1);
        $stat->addRebateSGArcadeCount(1);
        $stat->addRebateVRVrAmount(1);
        $stat->addRebateVRVrCount(1);
        $stat->addRebateVRLottoAmount(1);
        $stat->addRebateVRLottoCount(1);
        $stat->addRebateVRMarksixAmount(1);
        $stat->addRebateVRMarksixCount(1);
        $stat->addRebatePT2SlotsAmount(1);
        $stat->addRebatePT2SlotsCount(1);
        $stat->addRebatePT2JackpotAmount(1);
        $stat->addRebatePT2JackpotCount(1);
        $stat->addRebatePT2FishingAmount(1);
        $stat->addRebatePT2FishingCount(1);
        $stat->addRebatePT2TableAmount(1);
        $stat->addRebatePT2TableCount(1);
        $stat->addRebatePT2FeatureAmount(1);
        $stat->addRebatePT2FeatureCount(1);
        $stat->addRebateBngSlotsAmount(1);
        $stat->addRebateBngSlotsCount(1);
        $stat->addRebateEVOAmount(1);
        $stat->addRebateEVOCount(1);
        $stat->addRebateGNSJackpotAmount(1);
        $stat->addRebateGNSJackpotCount(1);
        $stat->addRebateGNSFeatureAmount(1);
        $stat->addRebateGNSFeatureCount(1);
        $stat->addRebateKYAmount(1);
        $stat->addRebateKYCount(1);
        $stat->addRebateGNSTableGamesAmount(1);
        $stat->addRebateGNSTableGamesCount(1);
        $stat->addRebateAmount(1);
        $stat->addRebateCount(1);

        $this->assertEquals(2, $stat->getRebateBallAmount());
        $this->assertEquals(2, $stat->getRebateBallCount());
        $this->assertEquals(2, $stat->getRebateKenoAmount());
        $this->assertEquals(2, $stat->getRebateKenoCount());
        $this->assertEquals(2, $stat->getRebateVideoAmount());
        $this->assertEquals(2, $stat->getRebateVideoCount());
        $this->assertEquals(2, $stat->getRebateSportAmount());
        $this->assertEquals(2, $stat->getRebateSportCount());
        $this->assertEquals(2, $stat->getRebateProbAmount());
        $this->assertEquals(2, $stat->getRebateProbCount());
        $this->assertEquals(2, $stat->getRebateLotteryAmount());
        $this->assertEquals(2, $stat->getRebateLotteryCount());
        $this->assertEquals(2, $stat->getRebateBBplayAmount());
        $this->assertEquals(2, $stat->getRebateBBplayCount());
        $this->assertEquals(2, $stat->getRebateOfferAmount());
        $this->assertEquals(2, $stat->getRebateOfferCount());
        $this->assertEquals(2, $stat->getRebateBBVideoAmount());
        $this->assertEquals(2, $stat->getRebateBBVideoCount());
        $this->assertEquals(2, $stat->getRebateTTVideoAmount());
        $this->assertEquals(2, $stat->getRebateTTVideoCount());
        $this->assertEquals(2, $stat->getRebateArmVideoAmount());
        $this->assertEquals(2, $stat->getRebateArmVideoCount());
        $this->assertEquals(2, $stat->getRebateXpjVideoAmount());
        $this->assertEquals(2, $stat->getRebateXpjVideoCount());
        $this->assertEquals(2, $stat->getRebateYfVideoAmount());
        $this->assertEquals(2, $stat->getRebateYfVideoCount());
        $this->assertEquals(2, $stat->getRebate3dAmount());
        $this->assertEquals(2, $stat->getRebate3dCount());
        $this->assertEquals(2, $stat->getRebateBattleAmount());
        $this->assertEquals(2, $stat->getRebateBattleCount());
        $this->assertEquals(2, $stat->getRebateVirtualAmount());
        $this->assertEquals(2, $stat->getRebateVirtualCount());
        $this->assertEquals(2, $stat->getRebateVipVideoAmount());
        $this->assertEquals(2, $stat->getRebateVipVideoCount());
        $this->assertEquals(2, $stat->getRebateAgVideoAmount());
        $this->assertEquals(2, $stat->getRebateAgVideoCount());
        $this->assertEquals(2, $stat->getRebatePTAmount());
        $this->assertEquals(2, $stat->getRebatePTCount());
        $this->assertEquals(2, $stat->getRebateLTAmount());
        $this->assertEquals(2, $stat->getRebateLTCount());
        $this->assertEquals(2, $stat->getRebateMIAmount());
        $this->assertEquals(2, $stat->getRebateMICount());
        $this->assertEquals(2, $stat->getRebateABAmount());
        $this->assertEquals(2, $stat->getRebateABCount());
        $this->assertEquals(2, $stat->getRebateMGAmount());
        $this->assertEquals(2, $stat->getRebateMGCount());
        $this->assertEquals(2, $stat->getRebateOGAmount());
        $this->assertEquals(2, $stat->getRebateOGCount());
        $this->assertEquals(2, $stat->getRebateSBAmount());
        $this->assertEquals(2, $stat->getRebateSBCount());
        $this->assertEquals(2, $stat->getRebateGDAmount());
        $this->assertEquals(2, $stat->getRebateGDCount());
        $this->assertEquals(2, $stat->getRebateSAAmount());
        $this->assertEquals(2, $stat->getRebateSACount());
        $this->assertEquals(2, $stat->getRebateGnsAmount());
        $this->assertEquals(2, $stat->getRebateGnsCount());
        $this->assertEquals(2, $stat->getRebateMGJackpotAmount());
        $this->assertEquals(2, $stat->getRebateMGJackpotCount());
        $this->assertEquals(2, $stat->getRebateMGSlotsAmount());
        $this->assertEquals(2, $stat->getRebateMGSlotsCount());
        $this->assertEquals(2, $stat->getRebateMGFeatureAmount());
        $this->assertEquals(2, $stat->getRebateMGFeatureCount());
        $this->assertEquals(2, $stat->getRebateMGTableAmount());
        $this->assertEquals(2, $stat->getRebateMGTableCount());
        $this->assertEquals(2, $stat->getRebateMGMobileAmount());
        $this->assertEquals(2, $stat->getRebateMGMobileCount());
        $this->assertEquals(2, $stat->getRebateISBAmount());
        $this->assertEquals(2, $stat->getRebateISBCount());
        $this->assertEquals(2, $stat->getRebateBBFGAmount());
        $this->assertEquals(2, $stat->getRebateBBFGCount());
        $this->assertEquals(2, $stat->getRebateBCAmount());
        $this->assertEquals(2, $stat->getRebateBCCount());
        $this->assertEquals(2, $stat->getRebateBBSlotsAmount());
        $this->assertEquals(2, $stat->getRebateBBSlotsCount());
        $this->assertEquals(2, $stat->getRebateBBTableAmount());
        $this->assertEquals(2, $stat->getRebateBBTableCount());
        $this->assertEquals(2, $stat->getRebateBBArcadeAmount());
        $this->assertEquals(2, $stat->getRebateBBArcadeCount());
        $this->assertEquals(2, $stat->getRebateBBScratchAmount());
        $this->assertEquals(2, $stat->getRebateBBScratchCount());
        $this->assertEquals(2, $stat->getRebateBBFeatureAmount());
        $this->assertEquals(2, $stat->getRebateBBFeatureCount());
        $this->assertEquals(2, $stat->getRebateBBTreasureAmount());
        $this->assertEquals(2, $stat->getRebateBBTreasureCount());
        $this->assertEquals(2, $stat->getRebateISBSlotsAmount());
        $this->assertEquals(2, $stat->getRebateISBSlotsCount());
        $this->assertEquals(2, $stat->getRebateISBTableAmount());
        $this->assertEquals(2, $stat->getRebateISBTableCount());
        $this->assertEquals(2, $stat->getRebateISBJackpotAmount());
        $this->assertEquals(2, $stat->getRebateISBJackpotCount());
        $this->assertEquals(2, $stat->getRebateISBPokerAmount());
        $this->assertEquals(2, $stat->getRebateISBPokerCount());
        $this->assertEquals(2, $stat->getRebate888FishingAmount());
        $this->assertEquals(2, $stat->getRebate888FishingCount());
        $this->assertEquals(2, $stat->getRebatePTSlotsAmount());
        $this->assertEquals(2, $stat->getRebatePTSlotsCount());
        $this->assertEquals(2, $stat->getRebatePTTableAmount());
        $this->assertEquals(2, $stat->getRebatePTTableCount());
        $this->assertEquals(2, $stat->getRebatePTJackpotAmount());
        $this->assertEquals(2, $stat->getRebatePTJackpotCount());
        $this->assertEquals(2, $stat->getRebatePTArcadeAmount());
        $this->assertEquals(2, $stat->getRebatePTArcadeCount());
        $this->assertEquals(2, $stat->getRebatePTScratchAmount());
        $this->assertEquals(2, $stat->getRebatePTScratchCount());
        $this->assertEquals(2, $stat->getRebatePTPokerAmount());
        $this->assertEquals(2, $stat->getRebatePTPokerCount());
        $this->assertEquals(2, $stat->getRebatePTUnclassifiedAmount());
        $this->assertEquals(2, $stat->getRebatePTUnclassifiedCount());
        $this->assertEquals(2, $stat->getRebateGOGAmount());
        $this->assertEquals(2, $stat->getRebateGOGCount());
        $this->assertEquals(2, $stat->getRebateSk1Amount());
        $this->assertEquals(2, $stat->getRebateSk1Count());
        $this->assertEquals(2, $stat->getRebateSk2Amount());
        $this->assertEquals(2, $stat->getRebateSk2Count());
        $this->assertEquals(2, $stat->getRebateSk3Amount());
        $this->assertEquals(2, $stat->getRebateSk3Count());
        $this->assertEquals(2, $stat->getRebateSk4Amount());
        $this->assertEquals(2, $stat->getRebateSk4Count());
        $this->assertEquals(2, $stat->getRebateSk5Amount());
        $this->assertEquals(2, $stat->getRebateSk5Count());
        $this->assertEquals(2, $stat->getRebateSk6Amount());
        $this->assertEquals(2, $stat->getRebateSk6Count());
        $this->assertEquals(2, $stat->getRebateHBSlotsAmount());
        $this->assertEquals(2, $stat->getRebateHBSlotsCount());
        $this->assertEquals(2, $stat->getRebateHBTableAmount());
        $this->assertEquals(2, $stat->getRebateHBTableCount());
        $this->assertEquals(2, $stat->getRebateHBPokerAmount());
        $this->assertEquals(2, $stat->getRebateHBPokerCount());
        $this->assertEquals(2, $stat->getRebateBGLiveAmount());
        $this->assertEquals(2, $stat->getRebateBGLiveCount());
        $this->assertEquals(2, $stat->getRebateFishingMasterAmount());
        $this->assertEquals(2, $stat->getRebateFishingMasterCount());
        $this->assertEquals(2, $stat->getRebatePPSlotsAmount());
        $this->assertEquals(2, $stat->getRebatePPSlotsCount());
        $this->assertEquals(2, $stat->getRebatePPTableAmount());
        $this->assertEquals(2, $stat->getRebatePPTableCount());
        $this->assertEquals(2, $stat->getRebatePPJackpotAmount());
        $this->assertEquals(2, $stat->getRebatePPJackpotCount());
        $this->assertEquals(2, $stat->getRebatePPFeatureAmount());
        $this->assertEquals(2, $stat->getRebatePPFeatureCount());
        $this->assertEquals(2, $stat->getRebatePTFishingAmount());
        $this->assertEquals(2, $stat->getRebatePTFishingCount());
        $this->assertEquals(2, $stat->getRebateGNSSlotsAmount());
        $this->assertEquals(2, $stat->getRebateGNSSlotsCount());
        $this->assertEquals(2, $stat->getRebateGNSFishingAmount());
        $this->assertEquals(2, $stat->getRebateGNSFishingCount());
        $this->assertEquals(2, $stat->getRebateJDBSlotsAmount());
        $this->assertEquals(2, $stat->getRebateJDBSlotsCount());
        $this->assertEquals(2, $stat->getRebateJDBArcadeAmount());
        $this->assertEquals(2, $stat->getRebateJDBArcadeCount());
        $this->assertEquals(2, $stat->getRebateJDBFishingAmount());
        $this->assertEquals(2, $stat->getRebateJDBFishingCount());
        $this->assertEquals(2, $stat->getRebateAgslotSlotsAmount());
        $this->assertEquals(2, $stat->getRebateAgslotSlotsCount());
        $this->assertEquals(2, $stat->getRebateAgslotTableAmount());
        $this->assertEquals(2, $stat->getRebateAgslotTableCount());
        $this->assertEquals(2, $stat->getRebateAgslotJackpotAmount());
        $this->assertEquals(2, $stat->getRebateAgslotJackpotCount());
        $this->assertEquals(2, $stat->getRebateAgslotFishingAmount());
        $this->assertEquals(2, $stat->getRebateAgslotFishingCount());
        $this->assertEquals(2, $stat->getRebateAgslotPokerAmount());
        $this->assertEquals(2, $stat->getRebateAgslotPokerCount());
        $this->assertEquals(2, $stat->getRebateMWSlotsAmount());
        $this->assertEquals(2, $stat->getRebateMWSlotsCount());
        $this->assertEquals(2, $stat->getRebateMWTableAmount());
        $this->assertEquals(2, $stat->getRebateMWTableCount());
        $this->assertEquals(2, $stat->getRebateMWArcadeAmount());
        $this->assertEquals(2, $stat->getRebateMWArcadeCount());
        $this->assertEquals(2, $stat->getRebateMWFishingAmount());
        $this->assertEquals(2, $stat->getRebateMWFishingCount());
        $this->assertEquals(2, $stat->getRebateINSportAmount());
        $this->assertEquals(2, $stat->getRebateINSportCount());
        $this->assertEquals(2, $stat->getRebateRTSlotsAmount());
        $this->assertEquals(2, $stat->getRebateRTSlotsCount());
        $this->assertEquals(2, $stat->getRebateRTTableAmount());
        $this->assertEquals(2, $stat->getRebateRTTableCount());
        $this->assertEquals(2, $stat->getRebateSGSlotsAmount());
        $this->assertEquals(2, $stat->getRebateSGSlotsCount());
        $this->assertEquals(2, $stat->getRebateSGTableAmount());
        $this->assertEquals(2, $stat->getRebateSGTableCount());
        $this->assertEquals(2, $stat->getRebateSGJackpotAmount());
        $this->assertEquals(2, $stat->getRebateSGJackpotCount());
        $this->assertEquals(2, $stat->getRebateSGArcadeAmount());
        $this->assertEquals(2, $stat->getRebateSGArcadeCount());
        $this->assertEquals(2, $stat->getRebateVRVrAmount());
        $this->assertEquals(2, $stat->getRebateVRVrCount());
        $this->assertEquals(2, $stat->getRebateVRLottoAmount());
        $this->assertEquals(2, $stat->getRebateVRLottoCount());
        $this->assertEquals(2, $stat->getRebateVRMarksixAmount());
        $this->assertEquals(2, $stat->getRebateVRMarksixCount());
        $this->assertEquals(2, $stat->getRebatePT2SlotsAmount());
        $this->assertEquals(2, $stat->getRebatePT2SlotsCount());
        $this->assertEquals(2, $stat->getRebatePT2JackpotAmount());
        $this->assertEquals(2, $stat->getRebatePT2JackpotCount());
        $this->assertEquals(2, $stat->getRebatePT2FishingAmount());
        $this->assertEquals(2, $stat->getRebatePT2FishingCount());
        $this->assertEquals(2, $stat->getRebatePT2TableAmount());
        $this->assertEquals(2, $stat->getRebatePT2TableCount());
        $this->assertEquals(2, $stat->getRebatePT2FeatureAmount());
        $this->assertEquals(2, $stat->getRebatePT2FeatureCount());
        $this->assertEquals(2, $stat->getRebateBngSlotsAmount());
        $this->assertEquals(2, $stat->getRebateBngSlotsCount());
        $this->assertEquals(2, $stat->getRebateEVOAmount());
        $this->assertEquals(2, $stat->getRebateEVOCount());
        $this->assertEquals(2, $stat->getRebateGNSJackpotAmount());
        $this->assertEquals(2, $stat->getRebateGNSJackpotCount());
        $this->assertEquals(2, $stat->getRebateGNSFeatureAmount());
        $this->assertEquals(2, $stat->getRebateGNSFeatureCount());
        $this->assertEquals(2, $stat->getRebateKYAmount());
        $this->assertEquals(2, $stat->getRebateKYCount());
        $this->assertEquals(2, $stat->getrebateGNSTableGamesAmount());
        $this->assertEquals(2, $stat->getrebateGNSTableGamesCount());
        $this->assertEquals(2, $stat->getRebateAmount());
        $this->assertEquals(2, $stat->getRebateCount());

        $stat->addRebateBallCount();
        $stat->addRebateKenoCount();
        $stat->addRebateVideoCount();
        $stat->addRebateSportCount();
        $stat->addRebateProbCount();
        $stat->addRebateLotteryCount();
        $stat->addRebateBBplayCount();
        $stat->addRebateOfferCount();
        $stat->addRebateBBVideoCount();
        $stat->addRebateTTVideoCount();
        $stat->addRebateArmVideoCount();
        $stat->addRebateXpjVideoCount();
        $stat->addRebateYfVideoCount();
        $stat->addRebate3dCount();
        $stat->addRebateBattleCount();
        $stat->addRebateVirtualCount();
        $stat->addRebateVipVideoCount();
        $stat->addRebateAgVideoCount();
        $stat->addRebatePTCount();
        $stat->addRebateLTCount();
        $stat->addRebateMICount();
        $stat->addRebateABCount();
        $stat->addRebateMGCount();
        $stat->addRebateOGCount();
        $stat->addRebateSBCount();
        $stat->addRebateGDCount();
        $stat->addRebateSACount();
        $stat->addRebateGnsCount();
        $stat->addRebateMGJackpotCount();
        $stat->addRebateMGSlotsCount();
        $stat->addRebateMGFeatureCount();
        $stat->addRebateMGTableCount();
        $stat->addRebateMGMobileCount();
        $stat->addRebateISBCount();
        $stat->addRebateBBFGCount();
        $stat->addRebateBCCount();
        $stat->addRebateBBSlotsCount();
        $stat->addRebateBBTableCount();
        $stat->addRebateBBArcadeCount();
        $stat->addRebateBBScratchCount();
        $stat->addRebateBBFeatureCount();
        $stat->addRebateBBTreasureCount();
        $stat->addRebateISBSlotsCount();
        $stat->addRebateISBTableCount();
        $stat->addRebateISBJackpotCount();
        $stat->addRebateISBPokerCount();
        $stat->addRebate888FishingCount();
        $stat->addRebatePTSlotsCount();
        $stat->addRebatePTTableCount();
        $stat->addRebatePTJackpotCount();
        $stat->addRebatePTArcadeCount();
        $stat->addRebatePTScratchCount();
        $stat->addRebatePTPokerCount();
        $stat->addRebatePTUnclassifiedCount();
        $stat->addRebateGOGCount();
        $stat->addRebateSk1Count();
        $stat->addRebateSk2Count();
        $stat->addRebateSk3Count();
        $stat->addRebateSk4Count();
        $stat->addRebateSk5Count();
        $stat->addRebateSk6Count();
        $stat->addRebateHBSlotsCount();
        $stat->addRebateHBTableCount();
        $stat->addRebateHBPokerCount();
        $stat->addRebateBGLiveCount();
        $stat->addRebateFishingMasterCount();
        $stat->addRebatePPSlotsCount();
        $stat->addRebatePPTableCount();
        $stat->addRebatePPJackpotCount();
        $stat->addRebatePPFeatureCount();
        $stat->addRebatePTFishingCount();
        $stat->addRebateGNSSlotsCount();
        $stat->addRebateGNSFishingCount();
        $stat->addRebateJDBSlotsCount();
        $stat->addRebateJDBArcadeCount();
        $stat->addRebateJDBFishingCount();
        $stat->addRebateAgslotSlotsCount();
        $stat->addRebateAgslotTableCount();
        $stat->addRebateAgslotJackpotCount();
        $stat->addRebateAgslotFishingCount();
        $stat->addRebateAgslotPokerCount();
        $stat->addRebateMWSlotsCount();
        $stat->addRebateMWTableCount();
        $stat->addRebateMWArcadeCount();
        $stat->addRebateMWFishingCount();
        $stat->addRebateINSportCount();
        $stat->addRebateRTSlotsCount();
        $stat->addRebateRTTableCount();
        $stat->addRebateSGSlotsCount();
        $stat->addRebateSGTableCount();
        $stat->addRebateSGJackpotCount();
        $stat->addRebateSGArcadeCount();
        $stat->addRebateVRVrCount();
        $stat->addRebateVRLottoCount();
        $stat->addRebateVRMarksixCount();
        $stat->addRebatePT2SlotsCount();
        $stat->addRebatePT2JackpotCount();
        $stat->addRebatePT2FishingCount();
        $stat->addRebatePT2TableCount();
        $stat->addRebatePT2FeatureCount();
        $stat->addRebateBngSlotsCount();
        $stat->addRebateEVOCount();
        $stat->addRebateGNSJackpotCount();
        $stat->addRebateGNSFeatureCount();
        $stat->addRebateKYCount();
        $stat->addRebateGNSTableGamesCount();
        $stat->addRebateCount();

        $this->assertEquals(3, $stat->getRebateBallCount());
        $this->assertEquals(3, $stat->getRebateKenoCount());
        $this->assertEquals(3, $stat->getRebateVideoCount());
        $this->assertEquals(3, $stat->getRebateSportCount());
        $this->assertEquals(3, $stat->getRebateProbCount());
        $this->assertEquals(3, $stat->getRebateLotteryCount());
        $this->assertEquals(3, $stat->getRebateBBplayCount());
        $this->assertEquals(3, $stat->getRebateOfferCount());
        $this->assertEquals(3, $stat->getRebateBBVideoCount());
        $this->assertEquals(3, $stat->getRebateTTVideoCount());
        $this->assertEquals(3, $stat->getRebateArmVideoCount());
        $this->assertEquals(3, $stat->getRebateXpjVideoCount());
        $this->assertEquals(3, $stat->getRebateYfVideoCount());
        $this->assertEquals(3, $stat->getRebate3dCount());
        $this->assertEquals(3, $stat->getRebateBattleCount());
        $this->assertEquals(3, $stat->getRebateVirtualCount());
        $this->assertEquals(3, $stat->getRebateVipVideoCount());
        $this->assertEquals(3, $stat->getRebateAgVideoCount());
        $this->assertEquals(3, $stat->getRebatePTCount());
        $this->assertEquals(3, $stat->getRebateLTCount());
        $this->assertEquals(3, $stat->getRebateMICount());
        $this->assertEquals(3, $stat->getRebateABCount());
        $this->assertEquals(3, $stat->getRebateMGCount());
        $this->assertEquals(3, $stat->getRebateOGCount());
        $this->assertEquals(3, $stat->getRebateSBCount());
        $this->assertEquals(3, $stat->getRebateGDCount());
        $this->assertEquals(3, $stat->getRebateSACount());
        $this->assertEquals(3, $stat->getRebateGnsCount());
        $this->assertEquals(3, $stat->getRebateMGJackpotCount());
        $this->assertEquals(3, $stat->getRebateMGSlotsCount());
        $this->assertEquals(3, $stat->getRebateMGFeatureCount());
        $this->assertEquals(3, $stat->getRebateMGTableCount());
        $this->assertEquals(3, $stat->getRebateMGMobileCount());
        $this->assertEquals(3, $stat->getRebateISBCount());
        $this->assertEquals(3, $stat->getRebateBBFGCount());
        $this->assertEquals(3, $stat->getRebateBCCount());
        $this->assertEquals(3, $stat->getRebateBBSlotsCount());
        $this->assertEquals(3, $stat->getRebateBBTableCount());
        $this->assertEquals(3, $stat->getRebateBBArcadeCount());
        $this->assertEquals(3, $stat->getRebateBBScratchCount());
        $this->assertEquals(3, $stat->getRebateBBFeatureCount());
        $this->assertEquals(3, $stat->getRebateBBTreasureCount());
        $this->assertEquals(3, $stat->getRebateISBSlotsCount());
        $this->assertEquals(3, $stat->getRebateISBTableCount());
        $this->assertEquals(3, $stat->getRebateISBJackpotCount());
        $this->assertEquals(3, $stat->getRebateISBPokerCount());
        $this->assertEquals(3, $stat->getRebate888FishingCount());
        $this->assertEquals(3, $stat->getRebatePTSlotsCount());
        $this->assertEquals(3, $stat->getRebatePTTableCount());
        $this->assertEquals(3, $stat->getRebatePTJackpotCount());
        $this->assertEquals(3, $stat->getRebatePTArcadeCount());
        $this->assertEquals(3, $stat->getRebatePTScratchCount());
        $this->assertEquals(3, $stat->getRebatePTPokerCount());
        $this->assertEquals(3, $stat->getRebatePTUnclassifiedCount());
        $this->assertEquals(3, $stat->getRebateGOGCount());
        $this->assertEquals(3, $stat->getRebateSk1Count());
        $this->assertEquals(3, $stat->getRebateSk2Count());
        $this->assertEquals(3, $stat->getRebateSk3Count());
        $this->assertEquals(3, $stat->getRebateSk4Count());
        $this->assertEquals(3, $stat->getRebateSk5Count());
        $this->assertEquals(3, $stat->getRebateSk6Count());
        $this->assertEquals(3, $stat->getRebateHBSlotsCount());
        $this->assertEquals(3, $stat->getRebateHBTableCount());
        $this->assertEquals(3, $stat->getRebateHBPokerCount());
        $this->assertEquals(3, $stat->getRebateBGLiveCount());
        $this->assertEquals(3, $stat->getRebateFishingMasterCount());
        $this->assertEquals(3, $stat->getRebatePPSlotsCount());
        $this->assertEquals(3, $stat->getRebatePPTableCount());
        $this->assertEquals(3, $stat->getRebatePPJackpotCount());
        $this->assertEquals(3, $stat->getRebatePPFeatureCount());
        $this->assertEquals(3, $stat->getRebatePTFishingCount());
        $this->assertEquals(3, $stat->getRebateGNSSlotsCount());
        $this->assertEquals(3, $stat->getRebateGNSFishingCount());
        $this->assertEquals(3, $stat->getRebateJDBSlotsCount());
        $this->assertEquals(3, $stat->getRebateJDBArcadeCount());
        $this->assertEquals(3, $stat->getRebateJDBFishingCount());
        $this->assertEquals(3, $stat->getRebateAgslotSlotsCount());
        $this->assertEquals(3, $stat->getRebateAgslotTableCount());
        $this->assertEquals(3, $stat->getRebateAgslotJackpotCount());
        $this->assertEquals(3, $stat->getRebateAgslotFishingCount());
        $this->assertEquals(3, $stat->getRebateAgslotPokerCount());
        $this->assertEquals(3, $stat->getRebateMWSlotsCount());
        $this->assertEquals(3, $stat->getRebateMWTableCount());
        $this->assertEquals(3, $stat->getRebateMWArcadeCount());
        $this->assertEquals(3, $stat->getRebateMWFishingCount());
        $this->assertEquals(3, $stat->getRebateINSportCount());
        $this->assertEquals(3, $stat->getRebateRTSlotsCount());
        $this->assertEquals(3, $stat->getRebateRTTableCount());
        $this->assertEquals(3, $stat->getRebateSGSlotsCount());
        $this->assertEquals(3, $stat->getRebateSGTableCount());
        $this->assertEquals(3, $stat->getRebateSGJackpotCount());
        $this->assertEquals(3, $stat->getRebateSGArcadeCount());
        $this->assertEquals(3, $stat->getRebateVRVrCount());
        $this->assertEquals(3, $stat->getRebateVRLottoCount());
        $this->assertEquals(3, $stat->getRebateVRMarksixCount());
        $this->assertEquals(3, $stat->getRebatePT2SlotsCount());
        $this->assertEquals(3, $stat->getRebatePT2JackpotCount());
        $this->assertEquals(3, $stat->getRebatePT2FishingCount());
        $this->assertEquals(3, $stat->getRebatePT2TableCount());
        $this->assertEquals(3, $stat->getRebatePT2FeatureCount());
        $this->assertEquals(3, $stat->getRebateBngSlotsCount());
        $this->assertEquals(3, $stat->getRebateEVOCount());
        $this->assertEquals(3, $stat->getRebateGNSJackpotCount());
        $this->assertEquals(3, $stat->getRebateGNSFeatureCount());
        $this->assertEquals(3, $stat->getRebateKYCount());
        $this->assertEquals(3, $stat->getRebateGNSTableGamesCount());
        $this->assertEquals(3, $stat->getRebateCount());
    }
}
