<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130626142041 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql", "Migration can only be executed safely on 'mysql'.");

        $this->addSql("CREATE TABLE `acc_param` (`id` int(11) NOT NULL AUTO_INCREMENT,  `currency_name` varchar(3) NOT NULL,  `account` varchar(32) NOT NULL,  `web` varchar(32) NOT NULL,  `account_date` datetime NOT NULL,  `account_name` varchar(100) NOT NULL,  `account_no` varchar(32) NOT NULL,  `bank_name` varchar(64) NOT NULL,  `gold` decimal(16,4) NOT NULL,  `remark` varchar(32) NOT NULL,  `check_02` smallint(6) NOT NULL,  `money_01` decimal(16,4) NOT NULL,  `money_02` decimal(16,4) NOT NULL,  `money_03` decimal(16,4) NOT NULL,  `from_id` int(11) NOT NULL,  `is_test` tinyint(1) NOT NULL,  `multiple_audit` smallint(6) NOT NULL,  `status_str` varchar(255) NOT NULL,  `status` smallint(6) NOT NULL,  `count` smallint(6) NOT NULL,  `update_at` datetime NOT NULL,  PRIMARY KEY (`id`),  KEY `idx_acc_param_status` (`status`),  KEY `idx_acc_param_count` (`count`))AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `background_process` (`name` varchar(50) NOT NULL,  `enable` tinyint(1) NOT NULL,  `begin_at` datetime NOT NULL,  `end_at` datetime NOT NULL,  `memo` varchar(100) NOT NULL,  `num` smallint(6) NOT NULL,  `msg_num` int(11) NOT NULL,  PRIMARY KEY (`name`));");
        $this->addSql("INSERT INTO `background_process` (`name`, `enable`, `begin_at`, `end_at`, `memo`, `num`, `msg_num`) VALUES ('activate_merchant', 1, '2014-01-28 15:49:01', '2014-01-28 15:49:04', '恢復商家額度, 每天 00:00', 0, 0),('activate_sl_next', 0, '2000-01-01 00:00:00', '2000-01-01 00:00:00', '更新佔成, 每天 00:00, 每週一 12:00', 0, 0),('check_cash_entry', 0, '2000-01-01 00:00:00', '2000-01-01 00:00:00', '檢查現金交易明細, 1/hour', 0, 0),('check_cash_error', 0, '2000-01-01 00:00:00', '2000-01-01 00:00:00', '檢查現金明細, 每天06:05', 0, 0),('check_cash_fake_error', 0, '2000-01-01 00:00:00', '2000-01-01 00:00:00', '檢查假現金明細, 每天05:05', 0, 0),('check_withdraw', 0, '2000-01-01 00:00:00', '2000-01-01 00:00:00', '到帳戶系統確認出款狀態, 1/min', 0, 0),('message_to_italking', 0, '2000-01-01 00:00:00', '2000-01-01 00:00:00', '送訊息至iTalking, 1/min', 0, 0),('run_card_poper', 0, '2000-01-01 00:00:00', '2000-01-01 00:00:00', '處理租卡明細, 1/sec', 0, 0),('run_card_sync', 0, '2000-01-01 00:00:00', '2000-01-01 00:00:00', '更新租卡餘額, 1/sec', 0, 0),('run_cashfake_poper', 0, '2000-01-01 00:00:00', '2000-01-01 00:00:00', '處理假現金明細, 1/sec', 0, 0),('run_cashfake_sync', 0, '2000-01-01 00:00:00', '2000-01-01 00:00:00', '更新假現金餘額, 1/sec', 0, 0),('run_cash_poper', 0, '2000-01-01 00:00:00', '2000-01-01 00:00:00', '處理現金明細, 1/sec', 0, 0),('run_cash_sync', 0, '2000-01-01 00:00:00', '2000-01-01 00:00:00', '更新現金餘額, 1/sec', 0, 0),('run_credit_poper', 0, '2000-01-01 00:00:00', '2000-01-01 00:00:00', '新增信用額度明細, 以及區間資料, 1/sec', 0, 0),('run_credit_sync', 0, '2000-01-01 00:00:00', '2000-01-01 00:00:00', '同步信用額度區間資料, 同步額度上限, 1/sec', 0, 0),('sync_cashfake_his_poper', 0, '2000-01-01 00:00:00', '2000-01-01 00:00:00', '同步快開額度交易明細資料, 1/sec', 0, 0),('sync_his_poper', 1, '2000-01-01 00:00:00', '2000-01-01 00:00:00', '同步現金交易明細資料, 1/sec', 0, 0),('toAccount', 0, '2000-01-01 00:00:00', '2000-01-01 00:00:00', '送出款至Account紀錄, 1/min', 0, 0);");
        $this->addSql("CREATE TABLE `bank` (`id` int(11) NOT NULL AUTO_INCREMENT,  `user_id` int(11) NOT NULL,  `code` smallint(6) DEFAULT NULL,  `account` varchar(36) NOT NULL,  `province` varchar(100) NOT NULL,  `city` varchar(100) NOT NULL,  `status` smallint(6) NOT NULL,  PRIMARY KEY (`id`),  KEY `IDX_D860BF7AA76ED395` (`user_id`),  KEY `idx_bank_account` (`account`)) AUTO_INCREMENT=1 ;");
        $this->addSql("CREATE TABLE `bank_currency` (`id` int(11) NOT NULL AUTO_INCREMENT,  `bank_info_id` int(11) NOT NULL,  `currency` varchar(3) NOT NULL,  PRIMARY KEY (`id`)) AUTO_INCREMENT=53;");
        $this->addSql("INSERT INTO `bank_currency` (`id`, `bank_info_id`, `currency`) VALUES (1, 1, 'CNY'),(2, 2, 'CNY'),(3, 3, 'CNY'),(4, 4, 'CNY'),(5, 5, 'CNY'),(6, 6, 'CNY'),(7, 7, 'CNY'),(8, 8, 'CNY'),(9, 9, 'CNY'),(10, 10, 'CNY'),(11, 11, 'CNY'),(12, 12, 'CNY'),(13, 13, 'CNY'),(14, 14, 'CNY'),(15, 15, 'CNY'),(16, 16, 'CNY'),(17, 17, 'CNY'),(18, 18, 'CNY'),(19, 19, 'CNY'),(20, 20, 'VND'),(21, 21, 'VND'),(22, 22, 'VND'),(23, 23, 'VND'),(24, 24, 'VND'),(25, 25, 'VND'),(26, 26, 'VND'),(27, 27, 'THB'),(28, 28, 'THB'),(29, 29, 'THB'),(30, 30, 'THB'),(31, 31, 'THB'),(32, 32, 'VND'),(33, 33, 'VND'),(34, 34, 'VND'),(35, 35, 'VND'),(36, 36, 'VND'),(37, 37, 'VND'),(38, 38, 'VND'),(39, 39, 'VND'),(40, 40, 'VND'),(41, 41, 'VND'),(42, 42, 'VND'),(43, 43, 'VND'),(44, 44, 'VND'),(45, 45, 'VND'),(46, 46, 'VND'),(47, 47, 'VND'),(48, 48, 'VND'),(49, 49, 'VND'),(50, 50, 'VND'),(51, 51, 'VND'),(52, 52, 'VND');");
        $this->addSql("CREATE TABLE `bank_info` (`id` int(11) NOT NULL AUTO_INCREMENT,  `bankname` varchar(255) NOT NULL,  PRIMARY KEY (`id`)) AUTO_INCREMENT=53;");
        $this->addSql("INSERT INTO `bank_info` (`id`, `bankname`) VALUES (1, '工商银行'),(2, '交通银行'),(3, '农业银行'),(4, '建设银行'),(5, '招商银行'),(6, '民生银行总行'),(7, '深圳发展银行'),(8, '上海浦东发展银行'),(9, '北京银行'),(10, '兴业银行'),(11, '中信银行'),(12, '光大银行'),(13, '华夏银行'),(14, '广东发展银行'),(15, '深圳平安银行'),(16, '中国邮政'),(17, '中国银行'),(18, '农村信用合作社'),(19, '上海银行'),(20, 'VIETCOM BANK'),(21, 'DONG A BANK'),(22, 'TECHCOM BANK'),(23, 'ACB'),(24, 'SACOM BANK'),(25, 'VIETTIN BANK'),(26, 'EXIM BANK'),(27, 'Bangkok Bank'),(28, 'KASIKORNBANK'),(29, 'BANK OF AYUDHYA'),(30, 'KRUNGTHAI BANK'),(31, 'SIAM COMMERCIAL BANK'),(32, 'ACB'),(33, 'DONGABANK'),(34, 'VIETCOMBANK'),(35, 'VIETINBANK'),(36, 'SACOMBANK'),(37, 'TECHCOMBANK'),(38, 'EXIMBANK'),(39, 'MARITIME BANK'),(40, 'AGRIBANK'),(41, 'BIDV'),(42, 'MHB'),(43, 'TRUSTBANK'),(44, 'MILITARY BANK'),(45, 'PNB'),(46, 'NASBANK'),(47, 'ABBANK'),(48, 'OCEANBANK'),(49, 'VIETABANK'),(50, 'BAOVIETBANK'),(51, 'PG BANK'),(52, 'NAM A BANK');");
        $this->addSql("CREATE TABLE `card` (`id` int(11) NOT NULL AUTO_INCREMENT,  `user_id` int(11) NOT NULL,  `enable_num` int(11) NOT NULL,  `enable` tinyint(1) NOT NULL,  `balance` int(11) NOT NULL,  `last_balance` int(11) NOT NULL,  `version` int(11) NOT NULL DEFAULT '1',  PRIMARY KEY (`id`),  KEY `IDX_161498D3A76ED395` (`user_id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `card_entry` (`id` bigint(20) NOT NULL,  `card_id` int(11) NOT NULL,  `opcode` int(11) NOT NULL,  `amount` int(11) NOT NULL,  `balance` int(11) NOT NULL,  `created_at` datetime NOT NULL,  `ref_id` varchar(20) DEFAULT NULL,  `operator` varchar(20) NOT NULL DEFAULT '',  PRIMARY KEY (`id`),  KEY `IDX_13156CB64ACC9A20` (`card_id`),  KEY `idx_card_entry_created_at` (`created_at`));");
        $this->addSql("CREATE TABLE `cash` (`id` int(11) NOT NULL AUTO_INCREMENT,  `currency` varchar(3) NOT NULL,  `user_id` int(11) NOT NULL,  `version` int(11) NOT NULL DEFAULT '1',  `balance` decimal(16,4) NOT NULL,  `pre_sub` decimal(16,4) NOT NULL,  `pre_add` decimal(16,4) NOT NULL,  PRIMARY KEY (`id`),  KEY `IDX_6B9E5B9A76ED395` (`user_id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `cash_deposit_entry` (`id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `oid` varchar(20) NOT NULL,  `user_id` int(11) NOT NULL,  `domain` int(11) NOT NULL,  `amount` decimal(16,4) NOT NULL,  `offer` decimal(16,4) NOT NULL,  `fee` decimal(16,4) NOT NULL,  `level` smallint(6) NOT NULL,  `telephone` varchar(20) NOT NULL,  `postcode` varchar(12) NOT NULL,  `address` varchar(254) NOT NULL,  `email` varchar(50) NOT NULL,  `full_set` tinyint(1) NOT NULL,  `merchant_id` smallint(5) unsigned NOT NULL,  `merchant_number` varchar(25) NOT NULL,  `currency` smallint(5) unsigned NOT NULL,  `rate` decimal(16,8) NOT NULL,  `user_rate` decimal(16,8) NOT NULL,  `memo` varchar(500) NOT NULL,  `entry_id` bigint(20) unsigned DEFAULT NULL,  `offer_entry_id` bigint(20) unsigned DEFAULT NULL,  `fee_entry_id` bigint(20) unsigned DEFAULT NULL,  `abandon_offer` tinyint(1) NOT NULL,  `manual` tinyint(1) NOT NULL,  `confirm` tinyint(1) NOT NULL,  `at` bigint(20) NOT NULL,  `version` int(10) unsigned NOT NULL DEFAULT '1',  PRIMARY KEY (`id`),  KEY `idx_cash_deposit_entry_user_id` (`user_id`),  KEY `idx_cash_deposit_entry_domain` (`domain`),  KEY `idx_cash_deposit_entry_at` (`at`),  KEY `idx_cash_deposit_entry_confirm` (`confirm`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `cash_entry` (`id` bigint(20) NOT NULL,  `at` bigint(20) NOT NULL,  `cash_id` int(11) NOT NULL,  `opcode` int(11) NOT NULL,  `created_at` datetime NOT NULL,  `amount` decimal(16,4) NOT NULL,  `memo` varchar(100) NOT NULL DEFAULT '',  `balance` decimal(16,4) NOT NULL,  `ref_id` bigint(20) NOT NULL,  PRIMARY KEY (`id`,`at`),  KEY `IDX_181F065C3D7A0C28` (`cash_id`),  KEY `idx_cash_entry_created_at` (`created_at`),  KEY `idx_cash_entry_ref_id` (`ref_id`),  KEY `idx_cash_entry_opcode` (`opcode`),  KEY `idx_cash_entry_at` (`at`),  KEY `idx_cash_entry_cash_id_at` (`cash_id`,`at`));");
        $this->addSql("CREATE TABLE `cash_entry_diff` (`id` bigint(20) NOT NULL,  `check_time` datetime NOT NULL,  PRIMARY KEY (`id`));");
        $this->addSql("CREATE TABLE `cash_entry_operator` (`entry_id` bigint(20) NOT NULL,  `username` varchar(20) NOT NULL DEFAULT '',  PRIMARY KEY (`entry_id`));");
        $this->addSql("CREATE TABLE `cash_error` (`id` int(11) NOT NULL AUTO_INCREMENT,  `cash_id` int(11) NOT NULL,  `balance` decimal(16,4) NOT NULL,  `total_amount` decimal(16,4) NOT NULL,  `at` datetime NOT NULL,  PRIMARY KEY (`id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `cash_fake` (`id` int(11) NOT NULL AUTO_INCREMENT,  `currency` varchar(3) NOT NULL,  `user_id` int(11) NOT NULL,  `version` int(11) NOT NULL DEFAULT '1',  `enable` tinyint(1) NOT NULL,  `balance` decimal(16,4) NOT NULL,  `pre_sub` decimal(16,4) NOT NULL,  `pre_add` decimal(16,4) NOT NULL,  PRIMARY KEY (`id`),  KEY `IDX_F04B3802A76ED395` (`user_id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `cash_fake_entry` (`id` bigint(20) NOT NULL,  `at` bigint(20) NOT NULL,  `cash_fake_id` int(11) NOT NULL,  `opcode` int(11) NOT NULL,  `created_at` datetime NOT NULL,  `amount` decimal(16,4) NOT NULL,  `memo` varchar(100) NOT NULL DEFAULT '',  `balance` decimal(16,4) NOT NULL,  `ref_id` bigint(20) NOT NULL,  PRIMARY KEY (`id`,`at`),  KEY `IDX_84518F4C9354354D` (`cash_fake_id`),  KEY `idx_cash_fake_entry_created_at` (`created_at`),  KEY `idx_cash_fake_entry_ref_id` (`ref_id`),  KEY `idx_cash_fake_entry_opcode` (`opcode`),  KEY `idx_cash_fake_entry_at` (`at`),  KEY `idx_cash_fake_entry_cash_id_at` (`cash_fake_id`,`at`));");
        $this->addSql("CREATE TABLE `cash_fake_entry_operator` (`entry_id` bigint(20) NOT NULL,  `username` varchar(20) NOT NULL DEFAULT '',  `transfer_out` tinyint(1) DEFAULT NULL,  `whom` varchar(20) NOT NULL,  `level` smallint(6) DEFAULT NULL,  PRIMARY KEY (`entry_id`));");
        $this->addSql("CREATE TABLE `cash_fake_error` (`id` int(11) NOT NULL AUTO_INCREMENT,  `cash_fake_id` int(11) NOT NULL,  `balance` decimal(16,4) NOT NULL,  `total_amount` decimal(16,4) NOT NULL,  `at` datetime NOT NULL,  PRIMARY KEY (`id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `cash_fake_total_balance` (`id` int(11) NOT NULL AUTO_INCREMENT,  `parent_id` int(11) NOT NULL,  `currency` varchar(3) NOT NULL,  `enable_balance` decimal(16,4) NOT NULL,  `disable_balance` decimal(16,4) NOT NULL,  `at` datetime DEFAULT NULL,  PRIMARY KEY (`id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `cash_fake_trans` (`id` bigint(20) NOT NULL,  `cash_fake_id` int(11) DEFAULT NULL,  `opcode` int(11) NOT NULL,  `amount` decimal(16,4) NOT NULL,  `ref_id` varchar(20) DEFAULT NULL,  `created_at` datetime NOT NULL,  `checked` tinyint(1) NOT NULL,  `checked_at` datetime DEFAULT NULL,  `memo` varchar(100) NOT NULL DEFAULT '',  PRIMARY KEY (`id`),  KEY `IDX_DF510C819354354D` (`cash_fake_id`),  KEY `idx_cash_fake_trans_ref_id` (`ref_id`),  KEY `idx_cash_fake_trans_created_at` (`created_at`),  KEY `idx_cash_fake_trans_checked` (`checked`));");
        $this->addSql("CREATE TABLE `cash_fake_transfer_entry` (`id` bigint(20) NOT NULL,  `cash_fake_id` int(11) NOT NULL,  `opcode` int(11) NOT NULL,  `created_at` datetime NOT NULL,  `amount` decimal(16,4) NOT NULL,  `balance` decimal(16,4) NOT NULL,  `ref_id` varchar(20) DEFAULT NULL,  `memo` varchar(100) NOT NULL DEFAULT '',  `at` bigint(20) NOT NULL,  PRIMARY KEY (`id`),  KEY `IDX_7A1C1EA89354354D` (`cash_fake_id`),  KEY `idx_cash_fake_transfer_entry_opcode` (`opcode`),  KEY `idx_cash_fake_transfer_entry_created_at` (`created_at`),  KEY `idx_cash_fake_transfer_entry_ref_id` (`ref_id`),  KEY `idx_cash_fake_transfer_entry_at` (`at`));");
        $this->addSql("CREATE TABLE `cash_fake_turn_error` (`id` int(11) NOT NULL AUTO_INCREMENT,  `cash_fake_id` int(11) NOT NULL,  `error_id` int(11) NOT NULL,  `entry_at` bigint(20) NOT NULL,  PRIMARY KEY (`id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `cash_total_balance` (`id` int(11) NOT NULL AUTO_INCREMENT,  `parent_id` int(11) NOT NULL,  `currency` varchar(3) NOT NULL,  `enable_balance` decimal(16,4) NOT NULL,  `disable_balance` decimal(16,4) NOT NULL,  `at` datetime DEFAULT NULL,  PRIMARY KEY (`id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `cash_trans` (`id` bigint(20) NOT NULL,  `cash_id` int(11) DEFAULT NULL,  `opcode` int(11) NOT NULL,  `amount` decimal(16,4) NOT NULL,  `ref_id` varchar(20) DEFAULT NULL,  `created_at` datetime NOT NULL,  `checked` tinyint(1) NOT NULL,  `checked_at` datetime DEFAULT NULL,  `memo` varchar(100) NOT NULL DEFAULT '',  PRIMARY KEY (`id`),  KEY `IDX_431F85913D7A0C28` (`cash_id`),  KEY `idx_cash_trans_ref_id` (`ref_id`),  KEY `idx_cash_trans_created_at` (`created_at`),  KEY `idx_cash_trans_checked` (`checked`));");
        $this->addSql("CREATE TABLE `cash_transfer_entry` (`id` bigint(20) NOT NULL,  `cash_id` int(11) NOT NULL,  `opcode` int(11) NOT NULL,  `created_at` datetime NOT NULL,  `amount` decimal(16,4) NOT NULL,  `balance` decimal(16,4) NOT NULL,  `ref_id` varchar(20) DEFAULT NULL,  `memo` varchar(100) NOT NULL DEFAULT '',  `at` bigint(20) NOT NULL,  `extra` varchar(50) DEFAULT NULL,  `tag` varchar(50) DEFAULT NULL,  PRIMARY KEY (`id`),  KEY `IDX_E4381A343D7A0C28` (`cash_id`),  KEY `idx_cash_transfer_entry_opcode` (`opcode`),  KEY `idx_cash_transfer_entry_created_at` (`created_at`),  KEY `idx_cash_transfer_entry_ref_id` (`ref_id`),  KEY `idx_cash_transfer_entry_at` (`at`),  KEY `idx_cash_transfer_entry_extra` (`extra`),  KEY `idx_cash_transfer_entry_tag` (`tag`));");
        $this->addSql("CREATE TABLE `cash_turn_error` (`id` int(11) NOT NULL AUTO_INCREMENT,  `cash_id` int(11) NOT NULL,  `error_id` int(11) NOT NULL,  `entry_at` bigint(20) NOT NULL,  PRIMARY KEY (`id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `cash_withdraw_entry` (`id` bigint(20) NOT NULL AUTO_INCREMENT,  `cash_id` int(11) NOT NULL,  `domain` int(11) NOT NULL,  `amount` decimal(16,4) NOT NULL,  `fee` decimal(16,4) NOT NULL,  `aduit_fee` decimal(16,4) NOT NULL,  `aduit_charge` decimal(16,4) NOT NULL,  `deduction` decimal(16,4) NOT NULL,  `real_amount` decimal(16,4) NOT NULL,  `level` smallint(6) NOT NULL,  `name_real` varchar(100) NOT NULL,  `telephone` varchar(20) NOT NULL,  `bank_name` varchar(255) NOT NULL,  `account` varchar(36) NOT NULL,  `province` varchar(100) NOT NULL,  `city` varchar(100) NOT NULL,  `checked_username` varchar(20) DEFAULT NULL,  `update_at` datetime DEFAULT NULL,  `at` datetime NOT NULL,  `rate` decimal(16,8) NOT NULL,  `memo` varchar(500) NOT NULL,  `ip` varchar(25) NOT NULL,  `first` tinyint(1) NOT NULL,  `entry_id` bigint(20) DEFAULT NULL,  `status` smallint(6) NOT NULL,  `version` int(10) unsigned NOT NULL DEFAULT '1',  PRIMARY KEY (`id`),  KEY `idx_cash_withdraw_entry_cash_id` (`cash_id`),  KEY `idx_cash_withdraw_entry_at` (`at`),  KEY `idx_cash_withdraw_entry_update_at` (`update_at`),  KEY `idx_cash_withdraw_entry_status` (`status`),  KEY `idx_cash_withdraw_entry_memo` (`memo`(255)),  KEY `idx_cash_withdraw_entry_domain` (`domain`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `credit` (`id` int(11) NOT NULL AUTO_INCREMENT,  `user_id` int(11) NOT NULL,  `line` bigint(20) NOT NULL,  `total_line` bigint(20) NOT NULL,  `group_num` int(11) NOT NULL,  `version` int(11) NOT NULL DEFAULT '1',  `enable` tinyint(1) NOT NULL,  PRIMARY KEY (`id`),  KEY `IDX_1CC16EFEA76ED395` (`user_id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `credit_entry` (`id` bigint(20) NOT NULL AUTO_INCREMENT,  `credit_id` int(11) NOT NULL,  `opcode` int(11) NOT NULL,  `at` bigint(20) NOT NULL,  `period_at` datetime NOT NULL,  `amount` decimal(16,4) NOT NULL,  `balance` decimal(16,4) NOT NULL,  `line` bigint(20) NOT NULL,  `total_line` bigint(20) NOT NULL,  `ref_id` varchar(20) DEFAULT NULL,  `memo` varchar(100) NOT NULL DEFAULT '',  PRIMARY KEY (`id`),  KEY `idx_credit_entry_credit_id` (`credit_id`),  KEY `idx_credit_entry_period_at` (`period_at`),  KEY `idx_credit_entry_at` (`at`),  KEY `idx_credit_entry_ref_id` (`ref_id`),  KEY `idx_credit_entry_opcode` (`opcode`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `credit_period` (`id` int(11) NOT NULL AUTO_INCREMENT,  `credit_id` int(11) NOT NULL,  `amount` decimal(16,4) NOT NULL,  `at` datetime NOT NULL,  `version` int(11) NOT NULL DEFAULT '1',  PRIMARY KEY (`id`),  KEY `IDX_F48EFFAFCE062FF9` (`credit_id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `deposit_company` (`id` int(10) unsigned NOT NULL AUTO_INCREMENT,  `payment_charge_id` int(10) unsigned NOT NULL,  `discount` smallint(5) unsigned NOT NULL,  `discount_give_up` tinyint(1) NOT NULL,  `discount_amount` decimal(16,4) NOT NULL,  `discount_percent` decimal(5,2) NOT NULL,  `discount_factor` smallint(5) unsigned NOT NULL,  `discount_limit` decimal(16,4) NOT NULL,  `deposit_max` decimal(16,4) NOT NULL,  `deposit_min` decimal(16,4) NOT NULL,  `audit_live` tinyint(1) NOT NULL,  `audit_live_amount` decimal(16,4) NOT NULL,  `audit_ball` tinyint(1) NOT NULL,  `audit_ball_amount` decimal(16,4) NOT NULL,  `audit_complex` tinyint(1) NOT NULL,  `audit_complex_amount` decimal(16,4) NOT NULL,  `audit_normal` tinyint(1) NOT NULL,  `audit_normal_amount` decimal(5,2) NOT NULL,  `audit_3d` tinyint(1) NOT NULL,  `audit_3d_amount` decimal(16,4) NOT NULL,  `audit_battle` tinyint(1) NOT NULL,  `audit_battle_amount` decimal(16,4) NOT NULL,  `audit_virtual` tinyint(1) NOT NULL,  `audit_virtual_amount` decimal(16,4) NOT NULL,  `audit_discount_amount` decimal(5,2) NOT NULL,  `audit_loosen` decimal(16,4) NOT NULL,  `audit_administrative` decimal(5,2) NOT NULL,  `other_discount_amount` decimal(16,4) NOT NULL,  `other_discount_percent` decimal(5,2) NOT NULL,  `other_discount_limit` decimal(16,4) NOT NULL,  `version` int(11) NOT NULL DEFAULT '1',  PRIMARY KEY (`id`),  UNIQUE KEY `UNIQ_4E75F3141601663C` (`payment_charge_id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `deposit_online` (`id` int(10) unsigned NOT NULL AUTO_INCREMENT,  `payment_charge_id` int(10) unsigned NOT NULL,  `discount` smallint(5) unsigned NOT NULL,  `discount_give_up` tinyint(1) NOT NULL,  `discount_amount` decimal(16,4) NOT NULL,  `discount_percent` decimal(5,2) NOT NULL,  `discount_factor` smallint(5) unsigned NOT NULL,  `discount_limit` decimal(16,4) NOT NULL,  `deposit_max` decimal(16,4) NOT NULL,  `deposit_min` decimal(16,4) NOT NULL,  `audit_live` tinyint(1) NOT NULL,  `audit_live_amount` decimal(16,4) NOT NULL,  `audit_ball` tinyint(1) NOT NULL,  `audit_ball_amount` decimal(16,4) NOT NULL,  `audit_complex` tinyint(1) NOT NULL,  `audit_complex_amount` decimal(16,4) NOT NULL,  `audit_normal` tinyint(1) NOT NULL,  `audit_normal_amount` decimal(5,2) NOT NULL,  `audit_3d` tinyint(1) NOT NULL,  `audit_3d_amount` decimal(16,4) NOT NULL,  `audit_battle` tinyint(1) NOT NULL,  `audit_battle_amount` decimal(16,4) NOT NULL,  `audit_virtual` tinyint(1) NOT NULL,  `audit_virtual_amount` decimal(16,4) NOT NULL,  `audit_discount_amount` decimal(5,2) NOT NULL,  `audit_loosen` decimal(16,4) NOT NULL,  `audit_administrative` decimal(5,2) NOT NULL,  `version` int(11) NOT NULL DEFAULT '1',  PRIMARY KEY (`id`),  UNIQUE KEY `UNIQ_8FB9E3AB1601663C` (`payment_charge_id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `domain_bank` (`id` int(11) NOT NULL AUTO_INCREMENT,  `domain` int(11) NOT NULL,  `bank_currency_id` int(11) NOT NULL,  PRIMARY KEY (`id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `exchange` (`id` int(11) NOT NULL AUTO_INCREMENT,  `currency` varchar(3) NOT NULL,  `buy` decimal(16,8) NOT NULL,  `basic` decimal(16,8) NOT NULL,  `sell` decimal(16,8) NOT NULL,  `active_at` datetime NOT NULL,  PRIMARY KEY (`id`)) AUTO_INCREMENT=27;");
        $this->addSql("INSERT INTO `exchange` (`id`, `currency`, `buy`, `basic`, `sell`, `active_at`) VALUES (1, 'CNY', '1.00000000', '1.00000000', '1.00000000', '2010-12-01 12:00:00'),(2, 'TWD', '0.20000000', '0.20000000', '0.20000000', '2010-12-01 12:00:00'),(3, 'HKD', '0.95000000', '0.95000000', '0.95000000', '2010-12-01 12:00:00'),(4, 'HKD', '0.96000000', '0.96000000', '0.96000000', '2010-12-15 12:00:00'),(5, 'TWD', '0.22300000', '0.22300000', '0.22300000', '2010-12-15 12:00:00'),(6, 'EUR', '8.76000000', '8.76000000', '8.76000000', '2010-12-01 12:00:00'),(7, 'GBP', '10.16000000', '10.16000000', '10.16000000', '2010-12-01 12:00:00'),(8, 'IDR', '0.00070000', '0.00070000', '0.00070000', '2010-12-01 12:00:00'),(9, 'JPY', '0.08000000', '0.08000000', '0.08000000', '2010-12-01 12:00:00'),(11, 'MYR', '2.03000000', '2.03000000', '2.03000000', '2010-12-01 12:00:00'),(12, 'SGD', '5.02000000', '5.02000000', '5.02000000', '2010-12-01 12:00:00'),(13, 'THB', '0.21000000', '0.21000000', '0.21000000', '2010-12-01 12:00:00'),(14, 'USD', '6.34000000', '6.34000000', '6.34000000', '2010-12-01 12:00:00'),(15, 'EUR', '8.76000000', '8.76000000', '8.76000000', '2011-06-01 12:00:00'),(16, 'GBP', '10.16000000', '10.16000000', '10.16000000', '2011-06-01 12:00:00'),(17, 'IDR', '0.00070000', '0.00070000', '0.00070000', '2011-06-01 12:00:00'),(18, 'JPY', '0.08000000', '0.08000000', '0.08000000', '2011-06-01 12:00:00'),(19, 'MYR', '2.03000000', '2.03000000', '2.03000000', '2011-06-01 12:00:00'),(20, 'SGD', '5.02000000', '5.02000000', '5.02000000', '2011-06-01 12:00:00'),(21, 'THB', '0.21000000', '0.21000000', '0.21000000', '2011-06-01 12:00:00'),(22, 'USD', '6.34000000', '6.34000000', '6.34000000', '2011-06-01 12:00:00'),(23, 'HKD', '0.81600000', '0.81600000', '0.81600000', '2011-06-01 12:00:00'),(24, 'TWD', '0.21100000', '0.21100000', '0.21100000', '2011-06-01 12:00:00'),(25, 'KRW', '0.00600000', '0.00600000', '0.00600000', '2011-06-01 12:00:00'),(26, 'VND', '0.00030000', '0.00030000', '0.00030000', '2011-06-01 12:00:00');");
        $this->addSql("CREATE TABLE `exchange_record` (`id` int(11) NOT NULL AUTO_INCREMENT,  `exchange_id` int(11) NOT NULL,  `currency` varchar(3) NOT NULL,  `buy` decimal(16,8) NOT NULL,  `sell` decimal(16,8) NOT NULL,  `basic` decimal(16,8) NOT NULL,  `active_at` datetime NOT NULL,  `modified_at` datetime NOT NULL,  `memo` varchar(100) NOT NULL,  PRIMARY KEY (`id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `geoip_block` (`block_id` int(10) unsigned NOT NULL AUTO_INCREMENT,  `country_id` int(10) unsigned NOT NULL,  `region_id` int(10) unsigned DEFAULT NULL,  `city_id` int(10) unsigned DEFAULT NULL,  `version_id` int(10) unsigned NOT NULL,  `ip_start` int(10) unsigned NOT NULL,  `ip_end` int(10) unsigned NOT NULL,  PRIMARY KEY (`block_id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `geoip_city` (`city_id` int(10) unsigned NOT NULL AUTO_INCREMENT,  `region_id` int(10) unsigned NOT NULL,  `country_code` varchar(5) NOT NULL,  `region_code` varchar(5) NOT NULL,  `city_code` varchar(40) NOT NULL,  `en_name` varchar(40) NOT NULL,  `zh_tw_name` varchar(40) NOT NULL,  `zh_cn_name` varchar(40) NOT NULL,  PRIMARY KEY (`city_id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `geoip_country` (`country_id` int(10) unsigned NOT NULL AUTO_INCREMENT,  `country_code` varchar(5) NOT NULL,  `en_name` varchar(40) NOT NULL,  `zh_tw_name` varchar(40) NOT NULL,  `zh_cn_name` varchar(40) NOT NULL,  PRIMARY KEY (`country_id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `geoip_region` (`region_id` int(10) unsigned NOT NULL AUTO_INCREMENT,  `country_id` int(10) unsigned NOT NULL,  `country_code` varchar(5) NOT NULL,  `region_code` varchar(5) NOT NULL,  `en_name` varchar(40) NOT NULL,  `zh_tw_name` varchar(40) NOT NULL,  `zh_cn_name` varchar(40) NOT NULL,  PRIMARY KEY (`region_id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `geoip_version` (`version_id` int(10) unsigned NOT NULL AUTO_INCREMENT,  `status` tinyint(1) NOT NULL,  `created_at` datetime NOT NULL,  `update_at` datetime NOT NULL,  PRIMARY KEY (`version_id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `login_log` (`id` int(11) NOT NULL AUTO_INCREMENT,  `user_id` int(11) DEFAULT NULL,  `username` varchar(20) NOT NULL,  `password` varchar(50) NOT NULL,  `ip` varchar(25) NOT NULL,  `at` datetime NOT NULL,  `result` int(11) NOT NULL,  `session_id` varchar(255) DEFAULT NULL,  `domain` int(11) NOT NULL,  `platform` varchar(8) DEFAULT NULL,  PRIMARY KEY (`id`),  KEY `idx_login_log_username` (`username`),  KEY `idx_login_log_domain` (`domain`),  KEY `idx_login_log_result` (`result`),  KEY `idx_login_log_at` (`at`),  KEY `idx_login_user_id` (`user_id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `log_operation` (`id` int(11) NOT NULL AUTO_INCREMENT,  `table_name` varchar(25) NOT NULL,  `major_key` varchar(40) NOT NULL,  `uri` varchar(100) NOT NULL,  `method` varchar(15) NOT NULL,  `at` datetime NOT NULL,  `server_ip` varchar(25) NOT NULL,  `client_ip` varchar(25) NOT NULL,  `message` varchar(2048) NOT NULL,  PRIMARY KEY (`id`),  KEY `idx_log_operation_table_name` (`table_name`),  KEY `idx_log_operation_major_key` (`major_key`),  KEY `idx_log_operation_at` (`at`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `maintain_record` (`id` int(11) NOT NULL AUTO_INCREMENT,  `maintainAt` datetime NOT NULL,  `state` int(11) NOT NULL,  `group_num` int(11) NOT NULL,  PRIMARY KEY (`id`),  KEY `IDX_8A2059D25FD14717` (`group_num`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `maintain_rule` (`group_num` int(11) NOT NULL,  `period` varchar(20) NOT NULL,  `maintain_at` datetime NOT NULL,  `state` int(11) NOT NULL,  PRIMARY KEY (`group_num`));");
        $this->addSql("INSERT INTO `maintain_rule` (`group_num`, `period`, `maintain_at`, `state`) VALUES (1, '0 12 * * 1', '0000-00-00 00:00:00', 3),(2, '0 12 * * 1', '0000-00-00 00:00:00', 3),(3, '0 12 * * 1', '0000-00-00 00:00:00', 3),(5, '0 0 * * *', '0000-00-00 00:00:00', 3),(6, '0 12 * * 1', '0000-00-00 00:00:00', 3),(7, '0 0 * * *', '0000-00-00 00:00:00', 3),(8, '0 0 * * *', '0000-00-00 00:00:00', 3),(9, '0 0 * * *', '0000-00-00 00:00:00', 3),(10, '0 0 * * *', '0000-00-00 00:00:00', 3),(11, '0 0 * * *', '0000-00-00 00:00:00', 3);");
        $this->addSql("CREATE TABLE `merchant` (`id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,  `payment_gateway_id` smallint(5) unsigned NOT NULL,  `alias` varchar(45) NOT NULL,  `number` varchar(25) NOT NULL,  `enable` tinyint(1) NOT NULL,  `domain` int(11) NOT NULL,  `currency` varchar(3) NOT NULL,  `private_key` varchar(512) NOT NULL,  `shop_url` varchar(100) NOT NULL,  `web_url` varchar(100) NOT NULL,  `full_set` tinyint(1) NOT NULL,  `created_by_admin` tinyint(1) NOT NULL,  `suspend` tinyint(1) NOT NULL,  `removed` tinyint(1) NOT NULL,  `bind_shop` tinyint(1) NOT NULL,  `approved` tinyint(1) NOT NULL,  PRIMARY KEY (`id`),  KEY `IDX_74AB25E162890FD5` (`payment_gateway_id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `merchant_extra` (`merchant_id` smallint(5) unsigned NOT NULL,  `name` varchar(45) NOT NULL,  `value` varchar(100) NOT NULL,  PRIMARY KEY (`merchant_id`,`name`),  KEY `IDX_DAACD7226796D554` (`merchant_id`));");
        $this->addSql("CREATE TABLE `merchant_has_bank_info` (`merchant_id` smallint(5) unsigned NOT NULL,  `bank_info_id` int(11) NOT NULL,  PRIMARY KEY (`merchant_id`,`bank_info_id`),  KEY `IDX_9473F9846796D554` (`merchant_id`),  KEY `IDX_9473F984731FA956` (`bank_info_id`));");
        $this->addSql("CREATE TABLE `merchant_ip_strategy` (`id` int(10) unsigned NOT NULL AUTO_INCREMENT,  `merchant_id` smallint(5) unsigned NOT NULL,  `country_id` int(10) unsigned NOT NULL,  `region_id` int(10) unsigned DEFAULT NULL,  `city_id` int(10) unsigned DEFAULT NULL,  PRIMARY KEY (`id`),  KEY `IDX_EC6935F93616FF93` (`merchant_id`),  KEY `IDX_EC6935F9F92F3E70` (`country_id`),  KEY `IDX_EC6935F998260155` (`region_id`),  KEY `IDX_EC6935F98BAC62AF` (`city_id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `merchant_key` (`id` int(11) NOT NULL AUTO_INCREMENT,  `merchant_id` smallint(5) unsigned NOT NULL,  `file_name` varchar(50) NOT NULL,  `file` blob NOT NULL,  PRIMARY KEY (`id`),  KEY `IDX_8D25C0026796D554` (`merchant_id`))AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `merchant_payment_level` (`merchant_id` smallint(5) unsigned NOT NULL,  `payment_level` smallint(5) unsigned NOT NULL,  `order_id` smallint(5) unsigned NOT NULL,  `version` int(11) NOT NULL DEFAULT '1',  PRIMARY KEY (`merchant_id`,`payment_level`));");
        $this->addSql("CREATE TABLE `merchant_record` (`id` int(10) unsigned NOT NULL AUTO_INCREMENT,  `domain` int(11) NOT NULL,  `created_at` bigint(20) unsigned NOT NULL,  `msg` varchar(2000) NOT NULL,  PRIMARY KEY (`id`),  KEY `idx_merchant_record_created_at` (`created_at`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `merchant_stat` (`id` int(10) unsigned NOT NULL AUTO_INCREMENT,  `merchant_id` smallint(5) unsigned NOT NULL,  `domain` int(11) NOT NULL,  `count` int(10) unsigned NOT NULL,  `total` decimal(16,4) NOT NULL,  `at` bigint(20) unsigned NOT NULL,  PRIMARY KEY (`id`),  UNIQUE KEY `uni_stat` (`merchant_id`,`at`),  KEY `IDX_61BB302A6796D554` (`merchant_id`),  KEY `idx_merchant_stat_domain` (`domain`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `payment_charge` (`id` int(10) unsigned NOT NULL AUTO_INCREMENT,  `domain` int(11) NOT NULL,  `name` varchar(45) NOT NULL,  `preset` tinyint(1) NOT NULL,  `rank` smallint(6) NOT NULL,  `code` varchar(15) NOT NULL,  `version` int(11) NOT NULL DEFAULT '1',  PRIMARY KEY (`id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `payment_gateway` (`id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,  `code` varchar(15) NOT NULL,  `name` varchar(45) NOT NULL,  `post_url` varchar(200) NOT NULL,  `auto_reop` tinyint(1) NOT NULL,  `reop_url` varchar(200) NOT NULL,  `version` int(11) NOT NULL DEFAULT '1',  PRIMARY KEY (`id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `payment_gateway_currency` (`payment_gateway_id` smallint(5) unsigned NOT NULL,  `currency` varchar(3) NOT NULL,  PRIMARY KEY (`payment_gateway_id`,`currency`),  KEY `IDX_164AD92162890FD5` (`payment_gateway_id`));");
        $this->addSql("CREATE TABLE `payment_gateway_fee` (`payment_charge_id` int(10) unsigned NOT NULL,  `payment_gateway_id` smallint(5) unsigned NOT NULL,  `rate` decimal(8,4) NOT NULL,  PRIMARY KEY (`payment_charge_id`,`payment_gateway_id`),  KEY `IDX_B46A3721601663C` (`payment_charge_id`),  KEY `IDX_B46A37262890FD5` (`payment_gateway_id`));");
        $this->addSql("CREATE TABLE `payment_gateway_has_bank_info` (`payment_gateway_id` smallint(5) unsigned NOT NULL,  `bank_info_id` int(11) NOT NULL,  PRIMARY KEY (`payment_gateway_id`,`bank_info_id`),  KEY `IDX_51B68F9F62890FD5` (`payment_gateway_id`),  KEY `IDX_51B68F9F731FA956` (`bank_info_id`));");
        $this->addSql("CREATE TABLE `payment_level` (`domain` int(11) NOT NULL,  `level` smallint(5) unsigned NOT NULL,  `order_strategy` smallint(5) unsigned NOT NULL,  PRIMARY KEY (`domain`,`level`))");
        $this->addSql("CREATE TABLE `payment_withdraw_fee` (`payment_charge_id` int(10) unsigned NOT NULL,  `free_period` smallint(6) NOT NULL,  `free_count` smallint(6) NOT NULL,  `amount_max` decimal(16,4) NOT NULL,  `amount_percent` decimal(5,2) NOT NULL,  `withdraw_max` decimal(16,4) NOT NULL,  `withdraw_min` decimal(16,4) NOT NULL,  PRIMARY KEY (`payment_charge_id`));");
        $this->addSql("CREATE TABLE `payment_withdraw_verify` (`payment_charge_id` int(10) unsigned NOT NULL,  `need_verify` tinyint(1) NOT NULL,  `verify_time` smallint(5) unsigned NOT NULL,  `verify_amount` int(10) unsigned NOT NULL,  PRIMARY KEY (`payment_charge_id`));");
        $this->addSql("CREATE TABLE `removed_cash` (`id` int(11) NOT NULL,  `removed_user_id` int(11) NOT NULL,  `currency` varchar(3) NOT NULL,  `balance` decimal(16,4) NOT NULL,  PRIMARY KEY (`id`),  KEY `IDX_888EF66DF4BCAA6A` (`removed_user_id`));");
        $this->addSql("CREATE TABLE `removed_payment_gateway` (`id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,  `originId` smallint(5) unsigned NOT NULL,  `code` varchar(15) NOT NULL,  `name` varchar(45) NOT NULL,  `post_url` varchar(200) NOT NULL,  `auto_reop` tinyint(1) NOT NULL,  `reop_url` varchar(200) NOT NULL,  PRIMARY KEY (`id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `removed_user` (`id` int(11) NOT NULL AUTO_INCREMENT,  `origin_id` int(11) NOT NULL,  `parent_id` int(11) DEFAULT NULL,  `username` varchar(20) NOT NULL,  `domain` int(11) NOT NULL,  `alias` varchar(50) NOT NULL,  `role` smallint(6) DEFAULT NULL,  `sub` tinyint(1) NOT NULL,  `enable` tinyint(1) NOT NULL,  `block` tinyint(1) NOT NULL,  `created_at` datetime NOT NULL,  `modified_at` datetime NOT NULL,  `password` varchar(50) NOT NULL,  `password_expire_at` datetime NOT NULL,  `password_reset` tinyint(1) NOT NULL,  `oid` varchar(50) NOT NULL,  `last_login` datetime DEFAULT NULL,  `test` tinyint(1) NOT NULL,  `currency` varchar(3) NOT NULL,  `last_bank` int(11) DEFAULT NULL,  `size` int(11) NOT NULL,  `rent` tinyint(1) NOT NULL,  `err_num` int(11) NOT NULL,  `bankrupt` tinyint(1) NOT NULL,  PRIMARY KEY (`id`),  KEY `idx_removed_user_origin_id` (`origin_id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `removed_user_detail` (`id` int(11) NOT NULL,  `removed_user_id` int(11) NOT NULL,  `email` varchar(50) NOT NULL,  `name_real` varchar(100) NOT NULL,  `name_chinese` varchar(36) NOT NULL,  `name_english` varchar(36) NOT NULL,  `country` varchar(30) NOT NULL,  `identity_type` varchar(2) NOT NULL,  `identity_code` varchar(18) NOT NULL,  `password` varchar(10) NOT NULL,  `birthday` datetime DEFAULT NULL,  `telephone` varchar(20) NOT NULL,  `qq_num` varchar(16) NOT NULL,  `note` varchar(150) NOT NULL,  PRIMARY KEY (`id`),  UNIQUE KEY `UNIQ_8F1D9653F4BCAA6A` (`removed_user_id`));");
        $this->addSql("CREATE TABLE `share_limit` (`id` int(11) NOT NULL AUTO_INCREMENT,  `user_id` int(11) NOT NULL,  `group_num` int(11) NOT NULL,  `upper` decimal(4,1) NOT NULL,  `lower` decimal(4,1) NOT NULL,  `parent_upper` decimal(4,1) NOT NULL,  `parent_lower` decimal(4,1) NOT NULL,  `min1` decimal(4,1) NOT NULL,  `max1` decimal(4,1) NOT NULL,  `max2` decimal(4,1) NOT NULL,  `version` int(11) NOT NULL DEFAULT '1',  PRIMARY KEY (`id`),  KEY `IDX_F6F8048DA76ED395` (`user_id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `share_limit_next` (`id` int(11) NOT NULL,  `user_id` int(11) NOT NULL,  `group_num` int(11) NOT NULL,  `upper` decimal(4,1) NOT NULL,  `lower` decimal(4,1) NOT NULL,  `parent_upper` decimal(4,1) NOT NULL,  `parent_lower` decimal(4,1) NOT NULL,  `min1` decimal(4,1) NOT NULL,  `max1` decimal(4,1) NOT NULL,  `max2` decimal(4,1) NOT NULL,  `version` int(11) NOT NULL DEFAULT '1',  PRIMARY KEY (`id`),  KEY `IDX_662FE700A76ED395` (`user_id`));");
        $this->addSql("CREATE TABLE `test` (`id` int(11) NOT NULL AUTO_INCREMENT,  `memo` varchar(30) NOT NULL,  PRIMARY KEY (`id`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `user` (`id` int(11) NOT NULL,  `parent_id` int(11) DEFAULT NULL,  `username` varchar(20) NOT NULL,  `domain` int(11) NOT NULL,  `alias` varchar(50) NOT NULL,  `role` smallint(6) DEFAULT NULL,  `sub` tinyint(1) NOT NULL,  `enable` tinyint(1) NOT NULL,  `block` tinyint(1) NOT NULL,  `created_at` datetime NOT NULL,  `modified_at` datetime NOT NULL,  `password` varchar(50) NOT NULL,  `password_expire_at` datetime NOT NULL,  `password_reset` tinyint(1) NOT NULL,  `oid` varchar(50) NOT NULL,  `last_login` datetime DEFAULT NULL,  `last_bank` int(11) DEFAULT NULL,  `test` tinyint(1) NOT NULL,  `currency` varchar(3) NOT NULL,  `size` int(11) NOT NULL,  `rent` tinyint(1) NOT NULL,  `err_num` int(11) NOT NULL,  `bankrupt` tinyint(1) NOT NULL,  PRIMARY KEY (`id`),  UNIQUE KEY `uni_username_domain` (`username`,`domain`),  KEY `IDX_8D93D649727ACA70` (`parent_id`),  KEY `idx_user_enable` (`enable`),  KEY `idx_user_sub` (`sub`),  KEY `idx_user_oid` (`oid`),  KEY `idx_user_bankrupt` (`bankrupt`),  KEY `idx_user_role` (`role`),  KEY `idx_user_domain_modified_at` (`domain`,`modified_at`));");
        $this->addSql("CREATE TABLE `user_ancestor` (`user_id` int(11) NOT NULL,  `ancestor_id` int(11) NOT NULL,  `depth` smallint(6) NOT NULL,  PRIMARY KEY (`user_id`,`ancestor_id`),  KEY `idx_ancestor_depth` (`ancestor_id`,`depth`));");
        $this->addSql("CREATE TABLE `user_detail` (`id` int(11) NOT NULL AUTO_INCREMENT,  `user_id` int(11) NOT NULL,  `email` varchar(50) NOT NULL,  `name_real` varchar(100) NOT NULL,  `name_chinese` varchar(36) NOT NULL,  `name_english` varchar(36) NOT NULL,  `country` varchar(30) NOT NULL,  `identity_type` varchar(2) NOT NULL,  `identity_code` varchar(18) NOT NULL,  `birthday` datetime DEFAULT NULL,  `telephone` varchar(20) NOT NULL,  `qq_num` varchar(16) NOT NULL,  `note` varchar(150) NOT NULL,  `password` varchar(10) NOT NULL,  PRIMARY KEY (`id`),  UNIQUE KEY `UNIQ_4B5464AEA76ED395` (`user_id`),  KEY `idx_user_detail_email` (`email`),  KEY `idx_user_detail_name_real` (`name_real`),  KEY `idx_user_detail_name_chinese` (`name_chinese`),  KEY `idx_user_detail_name_english` (`name_english`),  KEY `idx_user_detail_identity_code` (`identity_code`),  KEY `idx_user_detail_qq_num` (`qq_num`)) AUTO_INCREMENT=1;");
        $this->addSql("CREATE TABLE `user_payment_level` (`user_id` int(11) NOT NULL,  `block` tinyint(1) NOT NULL,  `payment_level` smallint(6) NOT NULL,  `last_payment_level` smallint(6) NOT NULL,  PRIMARY KEY (`user_id`),  KEY `idx_user_payment_level` (`payment_level`));");
        $this->addSql("CREATE TABLE `user_sequence` (`id` int(11) NOT NULL AUTO_INCREMENT,  PRIMARY KEY (`id`)) AUTO_INCREMENT=2;");
        $this->addSql("ALTER TABLE `bank`  ADD CONSTRAINT `FK_D860BF7AA76ED395` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`);");
        $this->addSql("ALTER TABLE `card`  ADD CONSTRAINT `FK_161498D3A76ED395` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`);");
        $this->addSql("ALTER TABLE `card_entry`  ADD CONSTRAINT `FK_13156CB64ACC9A20` FOREIGN KEY (`card_id`) REFERENCES `card` (`id`);");
        $this->addSql("ALTER TABLE `cash`  ADD CONSTRAINT `FK_6B9E5B9A76ED395` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`);");
        $this->addSql("ALTER TABLE `cash_fake`  ADD CONSTRAINT `FK_F04B3802A76ED395` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`);");
        $this->addSql("ALTER TABLE `cash_fake_trans`  ADD CONSTRAINT `FK_DF510C819354354D` FOREIGN KEY (`cash_fake_id`) REFERENCES `cash_fake` (`id`);");
        $this->addSql("ALTER TABLE `cash_trans`  ADD CONSTRAINT `FK_431F85913D7A0C28` FOREIGN KEY (`cash_id`) REFERENCES `cash` (`id`);");
        $this->addSql("ALTER TABLE `credit`  ADD CONSTRAINT `FK_1CC16EFEA76ED395` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`);");
        $this->addSql("ALTER TABLE `credit_period`  ADD CONSTRAINT `FK_F48EFFAFCE062FF9` FOREIGN KEY (`credit_id`) REFERENCES `credit` (`id`);");
        $this->addSql("ALTER TABLE `deposit_company`  ADD CONSTRAINT `FK_4E75F3141601663C` FOREIGN KEY (`payment_charge_id`) REFERENCES `payment_charge` (`id`);");
        $this->addSql("ALTER TABLE `deposit_online`  ADD CONSTRAINT `FK_8FB9E3AB1601663C` FOREIGN KEY (`payment_charge_id`) REFERENCES `payment_charge` (`id`);");
        $this->addSql("ALTER TABLE `maintain_record`  ADD CONSTRAINT `FK_8A2059D25FD14717` FOREIGN KEY (`group_num`) REFERENCES `maintain_rule` (`group_num`);");
        $this->addSql("ALTER TABLE `merchant`  ADD CONSTRAINT `FK_74AB25E162890FD5` FOREIGN KEY (`payment_gateway_id`) REFERENCES `payment_gateway` (`id`);");
        $this->addSql("ALTER TABLE `merchant_extra`  ADD CONSTRAINT `FK_DAACD7226796D554` FOREIGN KEY (`merchant_id`) REFERENCES `merchant` (`id`);");
        $this->addSql("ALTER TABLE `merchant_has_bank_info`  ADD CONSTRAINT `FK_9473F9846796D554` FOREIGN KEY (`merchant_id`) REFERENCES `merchant` (`id`),  ADD CONSTRAINT `FK_9473F984731FA956` FOREIGN KEY (`bank_info_id`) REFERENCES `bank_info` (`id`);");
        $this->addSql("ALTER TABLE `merchant_ip_strategy`  ADD CONSTRAINT `FK_EC6935F93616FF93` FOREIGN KEY (`merchant_id`) REFERENCES `merchant` (`id`),  ADD CONSTRAINT `FK_EC6935F98BAC62AF` FOREIGN KEY (`city_id`) REFERENCES `geoip_city` (`city_id`),  ADD CONSTRAINT `FK_EC6935F998260155` FOREIGN KEY (`region_id`) REFERENCES `geoip_region` (`region_id`),  ADD CONSTRAINT `FK_EC6935F9F92F3E70` FOREIGN KEY (`country_id`) REFERENCES `geoip_country` (`country_id`);");
        $this->addSql("ALTER TABLE `merchant_key`  ADD CONSTRAINT `FK_8D25C0026796D554` FOREIGN KEY (`merchant_id`) REFERENCES `merchant` (`id`);");
        $this->addSql("ALTER TABLE `merchant_stat`  ADD CONSTRAINT `FK_68EF6FCC6796D554` FOREIGN KEY (`merchant_id`) REFERENCES `merchant` (`id`);");
        $this->addSql("ALTER TABLE `payment_gateway_currency`  ADD CONSTRAINT `FK_164AD92162890FD5` FOREIGN KEY (`payment_gateway_id`) REFERENCES `payment_gateway` (`id`);");
        $this->addSql("ALTER TABLE `payment_gateway_fee`  ADD CONSTRAINT `FK_B46A37262890FD5` FOREIGN KEY (`payment_gateway_id`) REFERENCES `payment_gateway` (`id`),  ADD CONSTRAINT `FK_B46A3721601663C` FOREIGN KEY (`payment_charge_id`) REFERENCES `payment_charge` (`id`);");
        $this->addSql("ALTER TABLE `payment_gateway_has_bank_info`  ADD CONSTRAINT `FK_51B68F9F62890FD5` FOREIGN KEY (`payment_gateway_id`) REFERENCES `payment_gateway` (`id`),  ADD CONSTRAINT `FK_51B68F9F731FA956` FOREIGN KEY (`bank_info_id`) REFERENCES `bank_info` (`id`);");
        $this->addSql("ALTER TABLE `payment_withdraw_fee`  ADD CONSTRAINT `FK_231D9ADD1601663C` FOREIGN KEY (`payment_charge_id`) REFERENCES `payment_charge` (`id`);");
        $this->addSql("ALTER TABLE `payment_withdraw_verify`  ADD CONSTRAINT `FK_1D8E9B01601663C` FOREIGN KEY (`payment_charge_id`) REFERENCES `payment_charge` (`id`);");
        $this->addSql("ALTER TABLE `removed_cash`  ADD CONSTRAINT `FK_888EF66DF4BCAA6A` FOREIGN KEY (`removed_user_id`) REFERENCES `removed_user` (`id`);");
        $this->addSql("ALTER TABLE `removed_user_detail`  ADD CONSTRAINT `FK_8F1D9653F4BCAA6A` FOREIGN KEY (`removed_user_id`) REFERENCES `removed_user` (`id`);");
        $this->addSql("ALTER TABLE `share_limit`  ADD CONSTRAINT `FK_F6F8048DA76ED395` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`);");
        $this->addSql("ALTER TABLE `share_limit_next`  ADD CONSTRAINT `FK_662FE700A76ED395` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`);");
        $this->addSql("ALTER TABLE `user`  ADD CONSTRAINT `FK_8D93D649727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `user` (`id`);");
        $this->addSql("ALTER TABLE `user_ancestor`  ADD CONSTRAINT `FK_EBC981BBA76ED395` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`),  ADD CONSTRAINT `FK_EBC981BBC671CEA1` FOREIGN KEY (`ancestor_id`) REFERENCES `user` (`id`);");
        $this->addSql("ALTER TABLE `user_detail`  ADD CONSTRAINT `FK_4B5464AEA76ED395` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`);");
        $this->addSql("ALTER TABLE `user_payment_level`  ADD CONSTRAINT `FK_232D57F1A76ED395` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`);");
    }

    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql", "Migration can only be executed safely on 'mysql'.");

        $this->addSql("DROP TABLE `acc_param`;");
        $this->addSql("DROP TABLE `background_process`;");
        $this->addSql("DROP TABLE `bank`;");
        $this->addSql("DROP TABLE `bank_currency`;");
        $this->addSql("DROP TABLE `merchant_has_bank_info`;");
        $this->addSql("DROP TABLE `payment_gateway_has_bank_info`;");
        $this->addSql("DROP TABLE `bank_info`;");
        $this->addSql("DROP TABLE `card_entry`;");
        $this->addSql("DROP TABLE `card`;");
        $this->addSql("DROP TABLE `cash_withdraw_entry`;");
        $this->addSql("DROP TABLE `cash_transfer_entry`;");
        $this->addSql("DROP TABLE `cash_trans`;");
        $this->addSql("DROP TABLE `cash_entry`;");
        $this->addSql("DROP TABLE `cash_turn_error`;");
        $this->addSql("DROP TABLE `cash`;");
        $this->addSql("DROP TABLE `cash_deposit_entry`;");
        $this->addSql("DROP TABLE `cash_entry_diff`;");
        $this->addSql("DROP TABLE `cash_entry_operator`;");
        $this->addSql("DROP TABLE `cash_error`;");
        $this->addSql("DROP TABLE `cash_fake_transfer_entry`;");
        $this->addSql("DROP TABLE `cash_fake_trans`;");
        $this->addSql("DROP TABLE `cash_fake_entry`;");
        $this->addSql("DROP TABLE `cash_fake`;");
        $this->addSql("DROP TABLE `cash_fake_entry_operator`;");
        $this->addSql("DROP TABLE `cash_fake_error`;");
        $this->addSql("DROP TABLE `cash_fake_total_balance`;");
        $this->addSql("DROP TABLE `cash_fake_turn_error`;");
        $this->addSql("DROP TABLE `cash_total_balance`;");
        $this->addSql("DROP TABLE `credit_entry`;");
        $this->addSql("DROP TABLE `credit_period`;");
        $this->addSql("DROP TABLE `credit`;");
        $this->addSql("DROP TABLE `deposit_company`;");
        $this->addSql("DROP TABLE `deposit_online`;");
        $this->addSql("DROP TABLE `domain_bank`;");
        $this->addSql("DROP TABLE `exchange`;");
        $this->addSql("DROP TABLE `exchange_record`;");
        $this->addSql("DROP TABLE `geoip_block`;");
        $this->addSql("DROP TABLE `merchant_ip_strategy`;");
        $this->addSql("DROP TABLE `geoip_city`;");
        $this->addSql("DROP TABLE `geoip_country`;");
        $this->addSql("DROP TABLE `geoip_region`;");
        $this->addSql("DROP TABLE `geoip_version`;");
        $this->addSql("DROP TABLE `login_log`;");
        $this->addSql("DROP TABLE `log_operation`;");
        $this->addSql("DROP TABLE `maintain_record`;");
        $this->addSql("DROP TABLE `maintain_rule`;");
        $this->addSql("DROP TABLE `merchant_extra`;");
        $this->addSql("DROP TABLE `merchant_key`;");
        $this->addSql("DROP TABLE `merchant_payment_level`;");
        $this->addSql("DROP TABLE `merchant_stat`;");
        $this->addSql("DROP TABLE `merchant`;");
        $this->addSql("DROP TABLE `merchant_record`;");
        $this->addSql("DROP TABLE `payment_gateway_fee`;");
        $this->addSql("DROP TABLE `payment_withdraw_fee`;");
        $this->addSql("DROP TABLE `payment_withdraw_verify`;");
        $this->addSql("DROP TABLE `payment_charge`;");
        $this->addSql("DROP TABLE `payment_gateway_currency`;");
        $this->addSql("DROP TABLE `payment_gateway`;");
        $this->addSql("DROP TABLE `payment_level`;");
        $this->addSql("DROP TABLE `removed_cash`;");
        $this->addSql("DROP TABLE `removed_payment_gateway`;");
        $this->addSql("DROP TABLE `removed_user_detail`;");
        $this->addSql("DROP TABLE `removed_user`;");
        $this->addSql("DROP TABLE `share_limit`;");
        $this->addSql("DROP TABLE `share_limit_next`;");
        $this->addSql("DROP TABLE `test`;");
        $this->addSql("DROP TABLE `user_detail`;");
        $this->addSql("DROP TABLE `user_ancestor`;");
        $this->addSql("DROP TABLE `user_payment_level`;");
        $this->addSql("DROP TABLE `user`;");
        $this->addSql("DROP TABLE `user_sequence`;");
    }
}
