<?php

namespace BB\DurianBundle\Tests\Command;

use BB\DurianBundle\Tests\Functional\WebTestCase;

/**
 * 測試統計現金返點命令
 *
 * @author Sweet 2014.11.18
 */
class StatCashRebateCommandTest extends WebTestCase
{
    /**
     * 初始化
     */
    public function setUp()
    {
        parent::setUp();

        $classnames = [
            'BB\DurianBundle\Tests\DataFixtures\ORM\LoadStatCashOpcodeData'
        ];
        $this->loadFixtures($classnames, 'his');

        $classnames = ['BB\DurianBundle\Tests\DataFixtures\ORM\LoadBackgroundProcess'];
        $this->loadFixtures($classnames);
    }

    /**
     * 測試統計轉入資料正確
     */
    public function testStatSuccess()
    {
        $params = [
            '--start-date' => '2014-10-10',
            '--end-date' => '2014-10-10',
            '--batch-size' => 1000,
            '--wait-sec' => 0.00001,
            '--slow' => true
        ];
        $ret = $this->runCommand('durian:stat-cash-rebate', $params);

        // 沒有出現錯誤訊息
        $results = explode(PHP_EOL, $ret);
        $this->assertCount(3, $results);
        $this->assertEmpty($results[2]);

        $em = $this->getContainer()->get('doctrine.orm.his_entity_manager');

        $stat1 = $em->find('BBDurianBundle:StatCashRebate', 1);
        $this->assertEquals('2014-10-10 12:00:00', $stat1->getAt()->format('Y-m-d H:i:s'));
        $this->assertEquals(7, $stat1->getUserId());
        $this->assertEquals(901, $stat1->getCurrency());
        $this->assertEquals(2, $stat1->getDomain());
        $this->assertEquals(6, $stat1->getParentId());
        $this->assertEquals(80, $stat1->getRebateBallAmount());
        $this->assertEquals(4, $stat1->getRebateBallCount());
        $this->assertEquals(0, $stat1->getRebateKenoAmount());
        $this->assertEquals(0, $stat1->getRebateKenoCount());
        $this->assertEquals(0, $stat1->getRebateVideoAmount());
        $this->assertEquals(0, $stat1->getRebateVideoCount());
        $this->assertEquals(0, $stat1->getRebateSportAmount());
        $this->assertEquals(0, $stat1->getRebateSportCount());
        $this->assertEquals(0, $stat1->getRebateProbAmount());
        $this->assertEquals(0, $stat1->getRebateProbCount());
        $this->assertEquals(0, $stat1->getRebateLotteryAmount());
        $this->assertEquals(0, $stat1->getRebateLotteryCount());
        $this->assertEquals(0, $stat1->getRebateBBplayAmount());
        $this->assertEquals(0, $stat1->getRebateBBplayCount());
        $this->assertEquals(20, $stat1->getRebateOfferAmount());
        $this->assertEquals(1, $stat1->getRebateOfferCount());
        $this->assertEquals(0, $stat1->getRebateBBVideoAmount());
        $this->assertEquals(0, $stat1->getRebateBBVideoCount());
        $this->assertEquals(0, $stat1->getRebateTTVideoAmount());
        $this->assertEquals(0, $stat1->getRebateTTVideoCount());
        $this->assertEquals(0, $stat1->getRebateArmVideoAmount());
        $this->assertEquals(0, $stat1->getRebateArmVideoCount());
        $this->assertEquals(0, $stat1->getRebateXpjVideoAmount());
        $this->assertEquals(0, $stat1->getRebateXpjVideoCount());
        $this->assertEquals(0, $stat1->getRebateYfVideoAmount());
        $this->assertEquals(0, $stat1->getRebateYfVideoCount());
        $this->assertEquals(0, $stat1->getRebate3dAmount());
        $this->assertEquals(0, $stat1->getRebate3dCount());
        $this->assertEquals(0, $stat1->getRebateBattleAmount());
        $this->assertEquals(0, $stat1->getRebateBattleCount());
        $this->assertEquals(0, $stat1->getRebateVirtualAmount());
        $this->assertEquals(0, $stat1->getRebateVirtualCount());
        $this->assertEquals(0, $stat1->getRebateVipVideoAmount());
        $this->assertEquals(0, $stat1->getRebateVipVideoCount());
        $this->assertEquals(0, $stat1->getRebateAgVideoAmount());
        $this->assertEquals(0, $stat1->getRebateAgVideoCount());
        $this->assertEquals(0, $stat1->getRebatePTAmount());
        $this->assertEquals(0, $stat1->getRebatePTCount());
        $this->assertEquals(0, $stat1->getRebateLTAmount());
        $this->assertEquals(0, $stat1->getRebateLTCount());
        $this->assertEquals(0, $stat1->getRebateMIAmount());
        $this->assertEquals(0, $stat1->getRebateMICount());
        $this->assertEquals(0, $stat1->getRebateABAmount());
        $this->assertEquals(0, $stat1->getRebateABCount());
        $this->assertEquals(0, $stat1->getRebateMGAmount());
        $this->assertEquals(0, $stat1->getRebateMGCount());
        $this->assertEquals(0, $stat1->getRebateOGAmount());
        $this->assertEquals(0, $stat1->getRebateOGCount());
        $this->assertEquals(0, $stat1->getRebateSBAmount());
        $this->assertEquals(0, $stat1->getRebateSBCount());
        $this->assertEquals(0, $stat1->getRebateGDAmount());
        $this->assertEquals(0, $stat1->getRebateGDCount());
        $this->assertEquals(0, $stat1->getRebateSAAmount());
        $this->assertEquals(0, $stat1->getRebateSACount());
        $this->assertEquals(0, $stat1->getRebateGnsAmount());
        $this->assertEquals(0, $stat1->getRebateGnsCount());
        $this->assertEquals(0, $stat1->getRebateMGJackpotAmount());
        $this->assertEquals(0, $stat1->getRebateMGJackpotCount());
        $this->assertEquals(0, $stat1->getRebateMGSlotsAmount());
        $this->assertEquals(0, $stat1->getRebateMGSlotsCount());
        $this->assertEquals(0, $stat1->getRebateMGFeatureAmount());
        $this->assertEquals(0, $stat1->getRebateMGFeatureCount());
        $this->assertEquals(0, $stat1->getRebateMGTableAmount());
        $this->assertEquals(0, $stat1->getRebateMGTableCount());
        $this->assertEquals(0, $stat1->getRebateMGMobileAmount());
        $this->assertEquals(0, $stat1->getRebateMGMobileCount());
        $this->assertEquals(0, $stat1->getRebateISBAmount());
        $this->assertEquals(0, $stat1->getRebateISBCount());
        $this->assertEquals(0, $stat1->getRebateBBFGAmount());
        $this->assertEquals(0, $stat1->getRebateBBFGCount());
        $this->assertEquals(0, $stat1->getRebateBCAmount());
        $this->assertEquals(0, $stat1->getRebateBCCount());
        $this->assertEquals(0, $stat1->getRebateBBSlotsAmount());
        $this->assertEquals(0, $stat1->getRebateBBSlotsCount());
        $this->assertEquals(0, $stat1->getRebateBBTableAmount());
        $this->assertEquals(0, $stat1->getRebateBBTableCount());
        $this->assertEquals(0, $stat1->getRebateBBArcadeAmount());
        $this->assertEquals(0, $stat1->getRebateBBArcadeCount());
        $this->assertEquals(0, $stat1->getRebateBBScratchAmount());
        $this->assertEquals(0, $stat1->getRebateBBScratchCount());
        $this->assertEquals(0, $stat1->getRebateBBFeatureAmount());
        $this->assertEquals(0, $stat1->getRebateBBFeatureCount());
        $this->assertEquals(0, $stat1->getRebateBBTreasureAmount());
        $this->assertEquals(0, $stat1->getRebateBBTreasureCount());
        $this->assertEquals(0, $stat1->getRebateISBSlotsAmount());
        $this->assertEquals(0, $stat1->getRebateISBSlotsCount());
        $this->assertEquals(0, $stat1->getRebateISBTableAmount());
        $this->assertEquals(0, $stat1->getRebateISBTableCount());
        $this->assertEquals(0, $stat1->getRebateISBJackpotAmount());
        $this->assertEquals(0, $stat1->getRebateISBJackpotCount());
        $this->assertEquals(0, $stat1->getRebateISBPokerAmount());
        $this->assertEquals(0, $stat1->getRebateISBPokerCount());
        $this->assertEquals(0, $stat1->getRebate888FishingAmount());
        $this->assertEquals(0, $stat1->getRebate888FishingCount());
        $this->assertEquals(0, $stat1->getRebatePTSlotsAmount());
        $this->assertEquals(0, $stat1->getRebatePTSlotsCount());
        $this->assertEquals(0, $stat1->getRebatePTTableAmount());
        $this->assertEquals(0, $stat1->getRebatePTTableCount());
        $this->assertEquals(0, $stat1->getRebatePTJackpotAmount());
        $this->assertEquals(0, $stat1->getRebatePTJackpotCount());
        $this->assertEquals(0, $stat1->getRebatePTArcadeAmount());
        $this->assertEquals(0, $stat1->getRebatePTArcadeCount());
        $this->assertEquals(0, $stat1->getRebatePTScratchAmount());
        $this->assertEquals(0, $stat1->getRebatePTScratchCount());
        $this->assertEquals(0, $stat1->getRebatePTPokerAmount());
        $this->assertEquals(0, $stat1->getRebatePTPokerCount());
        $this->assertEquals(0, $stat1->getRebatePTUnclassifiedAmount());
        $this->assertEquals(0, $stat1->getRebatePTUnclassifiedCount());
        $this->assertEquals(0, $stat1->getRebateGOGAmount());
        $this->assertEquals(0, $stat1->getRebateGOGCount());
        $this->assertEquals(0, $stat1->getRebateSk1Amount());
        $this->assertEquals(0, $stat1->getRebateSk1Count());
        $this->assertEquals(0, $stat1->getRebateSk2Amount());
        $this->assertEquals(0, $stat1->getRebateSk2Count());
        $this->assertEquals(0, $stat1->getRebateSk3Amount());
        $this->assertEquals(0, $stat1->getRebateSk3Count());
        $this->assertEquals(0, $stat1->getRebateSk4Amount());
        $this->assertEquals(0, $stat1->getRebateSk4Count());
        $this->assertEquals(0, $stat1->getRebateSk5Amount());
        $this->assertEquals(0, $stat1->getRebateSk5Count());
        $this->assertEquals(0, $stat1->getRebateSk6Amount());
        $this->assertEquals(0, $stat1->getRebateSk6Count());
        $this->assertEquals(0, $stat1->getRebateHBSlotsAmount());
        $this->assertEquals(0, $stat1->getRebateHBSlotsCount());
        $this->assertEquals(0, $stat1->getRebateHBTableAmount());
        $this->assertEquals(0, $stat1->getRebateHBTableCount());
        $this->assertEquals(0, $stat1->getRebateHBPokerAmount());
        $this->assertEquals(0, $stat1->getRebateHBPokerCount());
        $this->assertEquals(0, $stat1->getRebateBGLiveAmount());
        $this->assertEquals(0, $stat1->getRebateBGLiveCount());
        $this->assertEquals(0, $stat1->getRebateFishingMasterAmount());
        $this->assertEquals(0, $stat1->getRebateFishingMasterCount());
        $this->assertEquals(0, $stat1->getRebatePPSlotsAmount());
        $this->assertEquals(0, $stat1->getRebatePPSlotsCount());
        $this->assertEquals(0, $stat1->getRebatePPTableAmount());
        $this->assertEquals(0, $stat1->getRebatePPTableCount());
        $this->assertEquals(0, $stat1->getRebatePPJackpotAmount());
        $this->assertEquals(0, $stat1->getRebatePPJackpotCount());
        $this->assertEquals(0, $stat1->getRebatePPFeatureAmount());
        $this->assertEquals(0, $stat1->getRebatePPFeatureCount());
        $this->assertEquals(0, $stat1->getRebatePTFishingAmount());
        $this->assertEquals(0, $stat1->getRebatePTFishingCount());
        $this->assertEquals(0, $stat1->getRebateGNSSlotsAmount());
        $this->assertEquals(0, $stat1->getRebateGNSSlotsCount());
        $this->assertEquals(0, $stat1->getRebateGNSFishingAmount());
        $this->assertEquals(0, $stat1->getRebateGNSFishingCount());
        $this->assertEquals(0, $stat1->getRebateJDBSlotsAmount());
        $this->assertEquals(0, $stat1->getRebateJDBSlotsCount());
        $this->assertEquals(0, $stat1->getRebateJDBArcadeAmount());
        $this->assertEquals(0, $stat1->getRebateJDBArcadeCount());
        $this->assertEquals(0, $stat1->getRebateJDBFishingAmount());
        $this->assertEquals(0, $stat1->getRebateJDBFishingCount());
        $this->assertEquals(0, $stat1->getRebateAgslotSlotsAmount());
        $this->assertEquals(0, $stat1->getRebateAgslotSlotsCount());
        $this->assertEquals(0, $stat1->getRebateAgslotTableAmount());
        $this->assertEquals(0, $stat1->getRebateAgslotTableCount());
        $this->assertEquals(0, $stat1->getRebateAgslotJackpotAmount());
        $this->assertEquals(0, $stat1->getRebateAgslotJackpotCount());
        $this->assertEquals(0, $stat1->getRebateAgslotFishingAmount());
        $this->assertEquals(0, $stat1->getRebateAgslotFishingCount());
        $this->assertEquals(0, $stat1->getRebateAgslotPokerAmount());
        $this->assertEquals(0, $stat1->getRebateAgslotPokerCount());
        $this->assertEquals(0, $stat1->getRebateMWSlotsAmount());
        $this->assertEquals(0, $stat1->getRebateMWSlotsCount());
        $this->assertEquals(0, $stat1->getRebateMWTableAmount());
        $this->assertEquals(0, $stat1->getRebateMWTableCount());
        $this->assertEquals(0, $stat1->getRebateMWArcadeAmount());
        $this->assertEquals(0, $stat1->getRebateMWArcadeCount());
        $this->assertEquals(0, $stat1->getRebateMWFishingAmount());
        $this->assertEquals(0, $stat1->getRebateMWFishingCount());
        $this->assertEquals(0, $stat1->getRebateINSportAmount());
        $this->assertEquals(0, $stat1->getRebateINSportCount());
        $this->assertEquals(0, $stat1->getRebateRTSlotsAmount());
        $this->assertEquals(0, $stat1->getRebateRTSlotsCount());
        $this->assertEquals(0, $stat1->getRebateRTTableAmount());
        $this->assertEquals(0, $stat1->getRebateRTTableCount());
        $this->assertEquals(0, $stat1->getRebateSGSlotsAmount());
        $this->assertEquals(0, $stat1->getRebateSGSlotsCount());
        $this->assertEquals(0, $stat1->getRebateSGTableAmount());
        $this->assertEquals(0, $stat1->getRebateSGTableCount());
        $this->assertEquals(0, $stat1->getRebateSGJackpotAmount());
        $this->assertEquals(0, $stat1->getRebateSGJackpotCount());
        $this->assertEquals(0, $stat1->getRebateSGArcadeAmount());
        $this->assertEquals(0, $stat1->getRebateSGArcadeCount());
        $this->assertEquals(0, $stat1->getRebateVRVrAmount());
        $this->assertEquals(0, $stat1->getRebateVRVrCount());
        $this->assertEquals(0, $stat1->getRebateVRLottoAmount());
        $this->assertEquals(0, $stat1->getRebateVRLottoCount());
        $this->assertEquals(0, $stat1->getRebateVRMarksixAmount());
        $this->assertEquals(0, $stat1->getRebateVRMarksixCount());
        $this->assertEquals(0, $stat1->getRebatePT2SlotsAmount());
        $this->assertEquals(0, $stat1->getRebatePT2SlotsCount());
        $this->assertEquals(0, $stat1->getRebatePT2JackpotAmount());
        $this->assertEquals(0, $stat1->getRebatePT2JackpotCount());
        $this->assertEquals(0, $stat1->getRebatePT2FishingAmount());
        $this->assertEquals(0, $stat1->getRebatePT2FishingCount());
        $this->assertEquals(0, $stat1->getRebatePT2TableAmount());
        $this->assertEquals(0, $stat1->getRebatePT2TableCount());
        $this->assertEquals(0, $stat1->getRebatePT2FeatureAmount());
        $this->assertEquals(0, $stat1->getRebatePT2FeatureCount());
        $this->assertEquals(0, $stat1->getRebateBngSlotsAmount());
        $this->assertEquals(0, $stat1->getRebateBngSlotsCount());
        $this->assertEquals(0, $stat1->getRebateEVOAmount());
        $this->assertEquals(0, $stat1->getRebateEVOCount());
        $this->assertEquals(0, $stat1->getRebateGNSJackpotAmount());
        $this->assertEquals(0, $stat1->getRebateGNSJackpotCount());
        $this->assertEquals(0, $stat1->getRebateGNSFeatureAmount());
        $this->assertEquals(0, $stat1->getRebateGNSFeatureCount());
        $this->assertEquals(0, $stat1->getRebateKYAmount());
        $this->assertEquals(0, $stat1->getRebateKYCount());
        $this->assertEquals(0, $stat1->getrebateGNSTableGamesAmount());
        $this->assertEquals(0, $stat1->getrebateGNSTableGamesCount());
        $this->assertEquals(100, $stat1->getRebateAmount());
        $this->assertEquals(5, $stat1->getRebateCount());

        // 加大時間範圍
        $params = [
            '--start-date' => '2014-10-10',
            '--end-date' => '2014-10-13',
            '--wait-sec' => 0.00001
        ];
        $this->runCommand('durian:stat-cash-rebate', $params);

        $query = $em->createQuery('SELECT COUNT(s) FROM BBDurianBundle:StatCashRebate s WHERE s.at >= :start AND s.at <= :end');
        $query->setParameter('start', new \DateTime('2014-10-10 12:00:00'));
        $query->setParameter('end', new \DateTime('2014-10-13 12:00:00'));

        $count = $query->getSingleScalarResult();

        $this->assertEquals(2, $count);

        $stat1 = $em->find('BBDurianBundle:StatCashRebate', 1);
        $this->assertEquals('2014-10-10 12:00:00', $stat1->getAt()->format('Y-m-d H:i:s'));
        $this->assertEquals(7, $stat1->getUserId());
        $this->assertEquals(901, $stat1->getCurrency());
        $this->assertEquals(2, $stat1->getDomain());
        $this->assertEquals(6, $stat1->getParentId());
        $this->assertEquals(80, $stat1->getRebateBallAmount());
        $this->assertEquals(4, $stat1->getRebateBallCount());
        $this->assertEquals(0, $stat1->getRebateKenoAmount());
        $this->assertEquals(0, $stat1->getRebateKenoCount());
        $this->assertEquals(0, $stat1->getRebateVideoAmount());
        $this->assertEquals(0, $stat1->getRebateVideoCount());
        $this->assertEquals(0, $stat1->getRebateSportAmount());
        $this->assertEquals(0, $stat1->getRebateSportCount());
        $this->assertEquals(0, $stat1->getRebateProbAmount());
        $this->assertEquals(0, $stat1->getRebateProbCount());
        $this->assertEquals(0, $stat1->getRebateLotteryAmount());
        $this->assertEquals(0, $stat1->getRebateLotteryCount());
        $this->assertEquals(0, $stat1->getRebateBBplayAmount());
        $this->assertEquals(0, $stat1->getRebateBBplayCount());
        $this->assertEquals(20, $stat1->getRebateOfferAmount());
        $this->assertEquals(1, $stat1->getRebateOfferCount());
        $this->assertEquals(0, $stat1->getRebateBBVideoAmount());
        $this->assertEquals(0, $stat1->getRebateBBVideoCount());
        $this->assertEquals(0, $stat1->getRebateTTVideoAmount());
        $this->assertEquals(0, $stat1->getRebateTTVideoCount());
        $this->assertEquals(0, $stat1->getRebateArmVideoAmount());
        $this->assertEquals(0, $stat1->getRebateArmVideoCount());
        $this->assertEquals(0, $stat1->getRebateXpjVideoAmount());
        $this->assertEquals(0, $stat1->getRebateXpjVideoCount());
        $this->assertEquals(0, $stat1->getRebateYfVideoAmount());
        $this->assertEquals(0, $stat1->getRebateYfVideoCount());
        $this->assertEquals(0, $stat1->getRebate3dAmount());
        $this->assertEquals(0, $stat1->getRebate3dCount());
        $this->assertEquals(0, $stat1->getRebateBattleAmount());
        $this->assertEquals(0, $stat1->getRebateBattleCount());
        $this->assertEquals(0, $stat1->getRebateVirtualAmount());
        $this->assertEquals(0, $stat1->getRebateVirtualCount());
        $this->assertEquals(0, $stat1->getRebateVipVideoAmount());
        $this->assertEquals(0, $stat1->getRebateVipVideoCount());
        $this->assertEquals(0, $stat1->getRebateAgVideoAmount());
        $this->assertEquals(0, $stat1->getRebateAgVideoCount());
        $this->assertEquals(0, $stat1->getRebatePTAmount());
        $this->assertEquals(0, $stat1->getRebatePTCount());
        $this->assertEquals(0, $stat1->getRebateLTAmount());
        $this->assertEquals(0, $stat1->getRebateLTCount());
        $this->assertEquals(0, $stat1->getRebateMIAmount());
        $this->assertEquals(0, $stat1->getRebateMICount());
        $this->assertEquals(0, $stat1->getRebateABAmount());
        $this->assertEquals(0, $stat1->getRebateABCount());
        $this->assertEquals(0, $stat1->getRebateMGAmount());
        $this->assertEquals(0, $stat1->getRebateMGCount());
        $this->assertEquals(0, $stat1->getRebateOGAmount());
        $this->assertEquals(0, $stat1->getRebateOGCount());
        $this->assertEquals(0, $stat1->getRebateSBAmount());
        $this->assertEquals(0, $stat1->getRebateSBCount());
        $this->assertEquals(0, $stat1->getRebateGDAmount());
        $this->assertEquals(0, $stat1->getRebateGDCount());
        $this->assertEquals(0, $stat1->getRebateSAAmount());
        $this->assertEquals(0, $stat1->getRebateSACount());
        $this->assertEquals(0, $stat1->getRebateGnsAmount());
        $this->assertEquals(0, $stat1->getRebateGnsCount());
        $this->assertEquals(0, $stat1->getRebateMGJackpotAmount());
        $this->assertEquals(0, $stat1->getRebateMGJackpotCount());
        $this->assertEquals(0, $stat1->getRebateMGSlotsAmount());
        $this->assertEquals(0, $stat1->getRebateMGSlotsCount());
        $this->assertEquals(0, $stat1->getRebateMGFeatureAmount());
        $this->assertEquals(0, $stat1->getRebateMGFeatureCount());
        $this->assertEquals(0, $stat1->getRebateMGTableAmount());
        $this->assertEquals(0, $stat1->getRebateMGTableCount());
        $this->assertEquals(0, $stat1->getRebateMGMobileAmount());
        $this->assertEquals(0, $stat1->getRebateMGMobileCount());
        $this->assertEquals(0, $stat1->getRebateISBAmount());
        $this->assertEquals(0, $stat1->getRebateISBCount());
        $this->assertEquals(0, $stat1->getRebateBBFGAmount());
        $this->assertEquals(0, $stat1->getRebateBBFGCount());
        $this->assertEquals(0, $stat1->getRebateBCAmount());
        $this->assertEquals(0, $stat1->getRebateBCCount());
        $this->assertEquals(0, $stat1->getRebateBBSlotsAmount());
        $this->assertEquals(0, $stat1->getRebateBBSlotsCount());
        $this->assertEquals(0, $stat1->getRebateBBTableAmount());
        $this->assertEquals(0, $stat1->getRebateBBTableCount());
        $this->assertEquals(0, $stat1->getRebateBBArcadeAmount());
        $this->assertEquals(0, $stat1->getRebateBBArcadeCount());
        $this->assertEquals(0, $stat1->getRebateBBScratchAmount());
        $this->assertEquals(0, $stat1->getRebateBBScratchCount());
        $this->assertEquals(0, $stat1->getRebateBBFeatureAmount());
        $this->assertEquals(0, $stat1->getRebateBBFeatureCount());
        $this->assertEquals(0, $stat1->getRebateBBTreasureAmount());
        $this->assertEquals(0, $stat1->getRebateBBTreasureCount());
        $this->assertEquals(0, $stat1->getRebateISBSlotsAmount());
        $this->assertEquals(0, $stat1->getRebateISBSlotsCount());
        $this->assertEquals(0, $stat1->getRebateISBTableAmount());
        $this->assertEquals(0, $stat1->getRebateISBTableCount());
        $this->assertEquals(0, $stat1->getRebateISBJackpotAmount());
        $this->assertEquals(0, $stat1->getRebateISBJackpotCount());
        $this->assertEquals(0, $stat1->getRebateISBPokerAmount());
        $this->assertEquals(0, $stat1->getRebateISBPokerCount());
        $this->assertEquals(0, $stat1->getRebate888FishingAmount());
        $this->assertEquals(0, $stat1->getRebate888FishingCount());
        $this->assertEquals(0, $stat1->getRebatePTSlotsAmount());
        $this->assertEquals(0, $stat1->getRebatePTSlotsCount());
        $this->assertEquals(0, $stat1->getRebatePTTableAmount());
        $this->assertEquals(0, $stat1->getRebatePTTableCount());
        $this->assertEquals(0, $stat1->getRebatePTJackpotAmount());
        $this->assertEquals(0, $stat1->getRebatePTJackpotCount());
        $this->assertEquals(0, $stat1->getRebatePTArcadeAmount());
        $this->assertEquals(0, $stat1->getRebatePTArcadeCount());
        $this->assertEquals(0, $stat1->getRebatePTScratchAmount());
        $this->assertEquals(0, $stat1->getRebatePTScratchCount());
        $this->assertEquals(0, $stat1->getRebatePTPokerAmount());
        $this->assertEquals(0, $stat1->getRebatePTPokerCount());
        $this->assertEquals(0, $stat1->getRebatePTUnclassifiedAmount());
        $this->assertEquals(0, $stat1->getRebatePTUnclassifiedCount());
        $this->assertEquals(0, $stat1->getRebateGOGAmount());
        $this->assertEquals(0, $stat1->getRebateGOGCount());
        $this->assertEquals(0, $stat1->getRebateSk1Amount());
        $this->assertEquals(0, $stat1->getRebateSk1Count());
        $this->assertEquals(0, $stat1->getRebateSk2Amount());
        $this->assertEquals(0, $stat1->getRebateSk2Count());
        $this->assertEquals(0, $stat1->getRebateSk3Amount());
        $this->assertEquals(0, $stat1->getRebateSk3Count());
        $this->assertEquals(0, $stat1->getRebateSk4Amount());
        $this->assertEquals(0, $stat1->getRebateSk4Count());
        $this->assertEquals(0, $stat1->getRebateSk5Amount());
        $this->assertEquals(0, $stat1->getRebateSk5Count());
        $this->assertEquals(0, $stat1->getRebateSk6Amount());
        $this->assertEquals(0, $stat1->getRebateSk6Count());
        $this->assertEquals(0, $stat1->getRebateHBSlotsAmount());
        $this->assertEquals(0, $stat1->getRebateHBSlotsCount());
        $this->assertEquals(0, $stat1->getRebateHBTableAmount());
        $this->assertEquals(0, $stat1->getRebateHBTableCount());
        $this->assertEquals(0, $stat1->getRebateHBPokerAmount());
        $this->assertEquals(0, $stat1->getRebateHBPokerCount());
        $this->assertEquals(0, $stat1->getRebateBGLiveAmount());
        $this->assertEquals(0, $stat1->getRebateBGLiveCount());
        $this->assertEquals(0, $stat1->getRebateFishingMasterAmount());
        $this->assertEquals(0, $stat1->getRebateFishingMasterCount());
        $this->assertEquals(0, $stat1->getRebatePPSlotsAmount());
        $this->assertEquals(0, $stat1->getRebatePPSlotsCount());
        $this->assertEquals(0, $stat1->getRebatePPTableAmount());
        $this->assertEquals(0, $stat1->getRebatePPTableCount());
        $this->assertEquals(0, $stat1->getRebatePPJackpotAmount());
        $this->assertEquals(0, $stat1->getRebatePPJackpotCount());
        $this->assertEquals(0, $stat1->getRebatePPFeatureAmount());
        $this->assertEquals(0, $stat1->getRebatePPFeatureCount());
        $this->assertEquals(0, $stat1->getRebatePTFishingAmount());
        $this->assertEquals(0, $stat1->getRebatePTFishingCount());
        $this->assertEquals(0, $stat1->getRebateGNSSlotsAmount());
        $this->assertEquals(0, $stat1->getRebateGNSSlotsCount());
        $this->assertEquals(0, $stat1->getRebateGNSFishingAmount());
        $this->assertEquals(0, $stat1->getRebateGNSFishingCount());
        $this->assertEquals(0, $stat1->getRebateJDBSlotsAmount());
        $this->assertEquals(0, $stat1->getRebateJDBSlotsCount());
        $this->assertEquals(0, $stat1->getRebateJDBArcadeAmount());
        $this->assertEquals(0, $stat1->getRebateJDBArcadeCount());
        $this->assertEquals(0, $stat1->getRebateJDBFishingAmount());
        $this->assertEquals(0, $stat1->getRebateJDBFishingCount());
        $this->assertEquals(0, $stat1->getRebateAgslotSlotsAmount());
        $this->assertEquals(0, $stat1->getRebateAgslotSlotsCount());
        $this->assertEquals(0, $stat1->getRebateAgslotTableAmount());
        $this->assertEquals(0, $stat1->getRebateAgslotTableCount());
        $this->assertEquals(0, $stat1->getRebateAgslotJackpotAmount());
        $this->assertEquals(0, $stat1->getRebateAgslotJackpotCount());
        $this->assertEquals(0, $stat1->getRebateAgslotFishingAmount());
        $this->assertEquals(0, $stat1->getRebateAgslotFishingCount());
        $this->assertEquals(0, $stat1->getRebateAgslotPokerAmount());
        $this->assertEquals(0, $stat1->getRebateAgslotPokerCount());
        $this->assertEquals(0, $stat1->getRebateMWSlotsAmount());
        $this->assertEquals(0, $stat1->getRebateMWSlotsCount());
        $this->assertEquals(0, $stat1->getRebateMWTableAmount());
        $this->assertEquals(0, $stat1->getRebateMWTableCount());
        $this->assertEquals(0, $stat1->getRebateMWArcadeAmount());
        $this->assertEquals(0, $stat1->getRebateMWArcadeCount());
        $this->assertEquals(0, $stat1->getRebateMWFishingAmount());
        $this->assertEquals(0, $stat1->getRebateMWFishingCount());
        $this->assertEquals(0, $stat1->getRebateINSportAmount());
        $this->assertEquals(0, $stat1->getRebateINSportCount());
        $this->assertEquals(0, $stat1->getRebateRTSlotsAmount());
        $this->assertEquals(0, $stat1->getRebateRTSlotsCount());
        $this->assertEquals(0, $stat1->getRebateRTTableAmount());
        $this->assertEquals(0, $stat1->getRebateRTTableCount());
        $this->assertEquals(0, $stat1->getRebateSGSlotsAmount());
        $this->assertEquals(0, $stat1->getRebateSGSlotsCount());
        $this->assertEquals(0, $stat1->getRebateSGTableAmount());
        $this->assertEquals(0, $stat1->getRebateSGTableCount());
        $this->assertEquals(0, $stat1->getRebateSGJackpotAmount());
        $this->assertEquals(0, $stat1->getRebateSGJackpotCount());
        $this->assertEquals(0, $stat1->getRebateSGArcadeAmount());
        $this->assertEquals(0, $stat1->getRebateSGArcadeCount());
        $this->assertEquals(0, $stat1->getRebateVRVrAmount());
        $this->assertEquals(0, $stat1->getRebateVRVrCount());
        $this->assertEquals(0, $stat1->getRebateVRLottoAmount());
        $this->assertEquals(0, $stat1->getRebateVRLottoCount());
        $this->assertEquals(0, $stat1->getRebateVRMarksixAmount());
        $this->assertEquals(0, $stat1->getRebateVRMarksixCount());
        $this->assertEquals(0, $stat1->getRebatePT2SlotsAmount());
        $this->assertEquals(0, $stat1->getRebatePT2SlotsCount());
        $this->assertEquals(0, $stat1->getRebatePT2JackpotAmount());
        $this->assertEquals(0, $stat1->getRebatePT2JackpotCount());
        $this->assertEquals(0, $stat1->getRebatePT2FishingAmount());
        $this->assertEquals(0, $stat1->getRebatePT2FishingCount());
        $this->assertEquals(0, $stat1->getRebatePT2TableAmount());
        $this->assertEquals(0, $stat1->getRebatePT2TableCount());
        $this->assertEquals(0, $stat1->getRebatePT2FeatureAmount());
        $this->assertEquals(0, $stat1->getRebatePT2FeatureCount());
        $this->assertEquals(0, $stat1->getRebateBngSlotsAmount());
        $this->assertEquals(0, $stat1->getRebateBngSlotsCount());
        $this->assertEquals(0, $stat1->getRebateEVOAmount());
        $this->assertEquals(0, $stat1->getRebateEVOCount());
        $this->assertEquals(0, $stat1->getRebateGNSJackpotAmount());
        $this->assertEquals(0, $stat1->getRebateGNSJackpotCount());
        $this->assertEquals(0, $stat1->getRebateGNSFeatureAmount());
        $this->assertEquals(0, $stat1->getRebateGNSFeatureCount());
        $this->assertEquals(0, $stat1->getRebateKYAmount());
        $this->assertEquals(0, $stat1->getRebateKYCount());
        $this->assertEquals(0, $stat1->getrebateGNSTableGamesAmount());
        $this->assertEquals(0, $stat1->getrebateGNSTableGamesCount());
        $this->assertEquals(100, $stat1->getRebateAmount());
        $this->assertEquals(5, $stat1->getRebateCount());

        $stat2 = $em->find('BBDurianBundle:StatCashRebate', 2);
        $this->assertEquals('2014-10-13 12:00:00', $stat2->getAt()->format('Y-m-d H:i:s'));
        $this->assertEquals(8, $stat2->getUserId());
        $this->assertEquals(156, $stat2->getCurrency());
        $this->assertEquals(2, $stat2->getDomain());
        $this->assertEquals(7, $stat2->getParentId());
        $this->assertEquals(0, $stat2->getRebateBallAmount());
        $this->assertEquals(0, $stat2->getRebateBallCount());
        $this->assertEquals(0, $stat2->getRebateKenoAmount());
        $this->assertEquals(0, $stat2->getRebateKenoCount());
        $this->assertEquals(0, $stat2->getRebateVideoAmount());
        $this->assertEquals(0, $stat2->getRebateVideoCount());
        $this->assertEquals(0, $stat2->getRebateSportAmount());
        $this->assertEquals(0, $stat2->getRebateSportCount());
        $this->assertEquals(0, $stat2->getRebateProbAmount());
        $this->assertEquals(0, $stat2->getRebateProbCount());
        $this->assertEquals(20, $stat2->getRebateLotteryAmount());
        $this->assertEquals(1, $stat2->getRebateLotteryCount());
        $this->assertEquals(0, $stat2->getRebateBBplayAmount());
        $this->assertEquals(0, $stat2->getRebateBBplayCount());
        $this->assertEquals(0, $stat2->getRebateOfferAmount());
        $this->assertEquals(0, $stat2->getRebateOfferCount());
        $this->assertEquals(0, $stat2->getRebateBBVideoAmount());
        $this->assertEquals(0, $stat2->getRebateBBVideoCount());
        $this->assertEquals(0, $stat2->getRebateTTVideoAmount());
        $this->assertEquals(0, $stat2->getRebateTTVideoCount());
        $this->assertEquals(0, $stat2->getRebateArmVideoAmount());
        $this->assertEquals(0, $stat2->getRebateArmVideoCount());
        $this->assertEquals(0, $stat2->getRebateXpjVideoAmount());
        $this->assertEquals(0, $stat2->getRebateXpjVideoCount());
        $this->assertEquals(0, $stat2->getRebateYfVideoAmount());
        $this->assertEquals(0, $stat2->getRebateYfVideoCount());
        $this->assertEquals(0, $stat2->getRebate3dAmount());
        $this->assertEquals(0, $stat2->getRebate3dCount());
        $this->assertEquals(0, $stat2->getRebateBattleAmount());
        $this->assertEquals(0, $stat2->getRebateBattleCount());
        $this->assertEquals(0, $stat2->getRebateVirtualAmount());
        $this->assertEquals(0, $stat2->getRebateVirtualCount());
        $this->assertEquals(0, $stat2->getRebateVipVideoAmount());
        $this->assertEquals(0, $stat2->getRebateVipVideoCount());
        $this->assertEquals(0, $stat2->getRebateAgVideoAmount());
        $this->assertEquals(0, $stat2->getRebateAgVideoCount());
        $this->assertEquals(0, $stat2->getRebatePTAmount());
        $this->assertEquals(0, $stat2->getRebatePTCount());
        $this->assertEquals(0, $stat2->getRebateLTAmount());
        $this->assertEquals(0, $stat2->getRebateLTCount());
        $this->assertEquals(0, $stat2->getRebateMIAmount());
        $this->assertEquals(0, $stat2->getRebateMICount());
        $this->assertEquals(0, $stat2->getRebateABAmount());
        $this->assertEquals(0, $stat2->getRebateABCount());
        $this->assertEquals(0, $stat2->getRebateMGAmount());
        $this->assertEquals(0, $stat2->getRebateMGCount());
        $this->assertEquals(0, $stat2->getRebateOGAmount());
        $this->assertEquals(0, $stat2->getRebateOGCount());
        $this->assertEquals(0, $stat2->getRebateSBAmount());
        $this->assertEquals(0, $stat2->getRebateSBCount());
        $this->assertEquals(0, $stat2->getRebateGDAmount());
        $this->assertEquals(0, $stat2->getRebateGDCount());
        $this->assertEquals(0, $stat2->getRebateSAAmount());
        $this->assertEquals(0, $stat2->getRebateSACount());
        $this->assertEquals(0, $stat2->getRebateGnsAmount());
        $this->assertEquals(0, $stat2->getRebateGnsCount());
        $this->assertEquals(0, $stat2->getRebateMGJackpotAmount());
        $this->assertEquals(0, $stat2->getRebateMGJackpotCount());
        $this->assertEquals(0, $stat2->getRebateMGSlotsAmount());
        $this->assertEquals(0, $stat2->getRebateMGSlotsCount());
        $this->assertEquals(0, $stat2->getRebateMGFeatureAmount());
        $this->assertEquals(0, $stat2->getRebateMGFeatureCount());
        $this->assertEquals(0, $stat2->getRebateMGTableAmount());
        $this->assertEquals(0, $stat2->getRebateMGTableCount());
        $this->assertEquals(0, $stat2->getRebateMGMobileAmount());
        $this->assertEquals(0, $stat2->getRebateMGMobileCount());
        $this->assertEquals(0, $stat2->getRebateISBAmount());
        $this->assertEquals(0, $stat2->getRebateISBCount());
        $this->assertEquals(0, $stat2->getRebateBBFGAmount());
        $this->assertEquals(0, $stat2->getRebateBBFGCount());
        $this->assertEquals(0, $stat2->getRebateBCAmount());
        $this->assertEquals(0, $stat2->getRebateBCCount());
        $this->assertEquals(0, $stat2->getRebateBBSlotsAmount());
        $this->assertEquals(0, $stat2->getRebateBBSlotsCount());
        $this->assertEquals(0, $stat2->getRebateBBTableAmount());
        $this->assertEquals(0, $stat2->getRebateBBTableCount());
        $this->assertEquals(0, $stat2->getRebateBBArcadeAmount());
        $this->assertEquals(0, $stat2->getRebateBBArcadeCount());
        $this->assertEquals(0, $stat2->getRebateBBScratchAmount());
        $this->assertEquals(0, $stat2->getRebateBBScratchCount());
        $this->assertEquals(0, $stat2->getRebateBBFeatureAmount());
        $this->assertEquals(0, $stat2->getRebateBBFeatureCount());
        $this->assertEquals(0, $stat2->getRebateBBTreasureAmount());
        $this->assertEquals(0, $stat2->getRebateBBTreasureCount());
        $this->assertEquals(0, $stat2->getRebateISBSlotsAmount());
        $this->assertEquals(0, $stat2->getRebateISBSlotsCount());
        $this->assertEquals(0, $stat2->getRebateISBTableAmount());
        $this->assertEquals(0, $stat2->getRebateISBTableCount());
        $this->assertEquals(0, $stat2->getRebateISBJackpotAmount());
        $this->assertEquals(0, $stat2->getRebateISBJackpotCount());
        $this->assertEquals(0, $stat2->getRebateISBPokerAmount());
        $this->assertEquals(0, $stat2->getRebateISBPokerCount());
        $this->assertEquals(0, $stat2->getRebate888FishingAmount());
        $this->assertEquals(0, $stat2->getRebate888FishingCount());
        $this->assertEquals(0, $stat2->getRebatePTSlotsAmount());
        $this->assertEquals(0, $stat2->getRebatePTSlotsCount());
        $this->assertEquals(0, $stat2->getRebatePTTableAmount());
        $this->assertEquals(0, $stat2->getRebatePTTableCount());
        $this->assertEquals(0, $stat2->getRebatePTJackpotAmount());
        $this->assertEquals(0, $stat2->getRebatePTJackpotCount());
        $this->assertEquals(0, $stat2->getRebatePTArcadeAmount());
        $this->assertEquals(0, $stat2->getRebatePTArcadeCount());
        $this->assertEquals(0, $stat2->getRebatePTScratchAmount());
        $this->assertEquals(0, $stat2->getRebatePTScratchCount());
        $this->assertEquals(0, $stat2->getRebatePTPokerAmount());
        $this->assertEquals(0, $stat2->getRebatePTPokerCount());
        $this->assertEquals(0, $stat2->getRebatePTUnclassifiedAmount());
        $this->assertEquals(0, $stat2->getRebatePTUnclassifiedCount());
        $this->assertEquals(0, $stat2->getRebateGOGAmount());
        $this->assertEquals(0, $stat2->getRebateGOGCount());
        $this->assertEquals(0, $stat2->getRebateSk1Amount());
        $this->assertEquals(0, $stat2->getRebateSk1Count());
        $this->assertEquals(0, $stat2->getRebateSk2Amount());
        $this->assertEquals(0, $stat2->getRebateSk2Count());
        $this->assertEquals(0, $stat2->getRebateSk3Amount());
        $this->assertEquals(0, $stat2->getRebateSk3Count());
        $this->assertEquals(0, $stat2->getRebateSk4Amount());
        $this->assertEquals(0, $stat2->getRebateSk4Count());
        $this->assertEquals(0, $stat2->getRebateSk5Amount());
        $this->assertEquals(0, $stat2->getRebateSk5Count());
        $this->assertEquals(0, $stat2->getRebateSk6Amount());
        $this->assertEquals(0, $stat2->getRebateSk6Count());
        $this->assertEquals(0, $stat2->getRebateHBSlotsAmount());
        $this->assertEquals(0, $stat2->getRebateHBSlotsCount());
        $this->assertEquals(0, $stat2->getRebateHBTableAmount());
        $this->assertEquals(0, $stat2->getRebateHBTableCount());
        $this->assertEquals(0, $stat2->getRebateHBPokerAmount());
        $this->assertEquals(0, $stat2->getRebateHBPokerCount());
        $this->assertEquals(0, $stat2->getRebateBGLiveAmount());
        $this->assertEquals(0, $stat2->getRebateBGLiveCount());
        $this->assertEquals(0, $stat2->getRebateFishingMasterAmount());
        $this->assertEquals(0, $stat2->getRebateFishingMasterCount());
        $this->assertEquals(0, $stat2->getRebatePPSlotsAmount());
        $this->assertEquals(0, $stat2->getRebatePPSlotsCount());
        $this->assertEquals(0, $stat2->getRebatePPTableAmount());
        $this->assertEquals(0, $stat2->getRebatePPTableCount());
        $this->assertEquals(0, $stat2->getRebatePPJackpotAmount());
        $this->assertEquals(0, $stat2->getRebatePPJackpotCount());
        $this->assertEquals(0, $stat2->getRebatePPFeatureAmount());
        $this->assertEquals(0, $stat2->getRebatePPFeatureCount());
        $this->assertEquals(0, $stat2->getRebatePTFishingAmount());
        $this->assertEquals(0, $stat2->getRebatePTFishingCount());
        $this->assertEquals(0, $stat2->getRebateGNSSlotsAmount());
        $this->assertEquals(0, $stat2->getRebateGNSSlotsCount());
        $this->assertEquals(0, $stat2->getRebateGNSFishingAmount());
        $this->assertEquals(0, $stat2->getRebateGNSFishingCount());
        $this->assertEquals(0, $stat2->getRebateJDBSlotsAmount());
        $this->assertEquals(0, $stat2->getRebateJDBSlotsCount());
        $this->assertEquals(0, $stat2->getRebateJDBArcadeAmount());
        $this->assertEquals(0, $stat2->getRebateJDBArcadeCount());
        $this->assertEquals(0, $stat2->getRebateJDBFishingAmount());
        $this->assertEquals(0, $stat2->getRebateJDBFishingCount());
        $this->assertEquals(0, $stat2->getRebateAgslotSlotsAmount());
        $this->assertEquals(0, $stat2->getRebateAgslotSlotsCount());
        $this->assertEquals(0, $stat2->getRebateAgslotTableAmount());
        $this->assertEquals(0, $stat2->getRebateAgslotTableCount());
        $this->assertEquals(0, $stat2->getRebateAgslotJackpotAmount());
        $this->assertEquals(0, $stat2->getRebateAgslotJackpotCount());
        $this->assertEquals(0, $stat2->getRebateAgslotFishingAmount());
        $this->assertEquals(0, $stat2->getRebateAgslotFishingCount());
        $this->assertEquals(0, $stat2->getRebateAgslotPokerAmount());
        $this->assertEquals(0, $stat2->getRebateAgslotPokerCount());
        $this->assertEquals(0, $stat2->getRebateMWSlotsAmount());
        $this->assertEquals(0, $stat2->getRebateMWSlotsCount());
        $this->assertEquals(0, $stat2->getRebateMWTableAmount());
        $this->assertEquals(0, $stat2->getRebateMWTableCount());
        $this->assertEquals(0, $stat2->getRebateMWArcadeAmount());
        $this->assertEquals(0, $stat2->getRebateMWArcadeCount());
        $this->assertEquals(0, $stat2->getRebateMWFishingAmount());
        $this->assertEquals(0, $stat2->getRebateMWFishingCount());
        $this->assertEquals(0, $stat2->getRebateINSportAmount());
        $this->assertEquals(0, $stat2->getRebateINSportCount());
        $this->assertEquals(0, $stat2->getRebateRTSlotsAmount());
        $this->assertEquals(0, $stat2->getRebateRTSlotsCount());
        $this->assertEquals(0, $stat2->getRebateRTTableAmount());
        $this->assertEquals(0, $stat2->getRebateRTTableCount());
        $this->assertEquals(0, $stat2->getRebateSGSlotsAmount());
        $this->assertEquals(0, $stat2->getRebateSGSlotsCount());
        $this->assertEquals(0, $stat2->getRebateSGTableAmount());
        $this->assertEquals(0, $stat2->getRebateSGTableCount());
        $this->assertEquals(0, $stat2->getRebateSGJackpotAmount());
        $this->assertEquals(0, $stat2->getRebateSGJackpotCount());
        $this->assertEquals(0, $stat2->getRebateSGArcadeAmount());
        $this->assertEquals(0, $stat2->getRebateSGArcadeCount());
        $this->assertEquals(0, $stat2->getRebateVRVrAmount());
        $this->assertEquals(0, $stat2->getRebateVRVrCount());
        $this->assertEquals(0, $stat2->getRebateVRLottoAmount());
        $this->assertEquals(0, $stat2->getRebateVRLottoCount());
        $this->assertEquals(0, $stat2->getRebateVRMarksixAmount());
        $this->assertEquals(0, $stat2->getRebateVRMarksixCount());
        $this->assertEquals(0, $stat2->getRebatePT2SlotsAmount());
        $this->assertEquals(0, $stat2->getRebatePT2SlotsCount());
        $this->assertEquals(0, $stat2->getRebatePT2JackpotAmount());
        $this->assertEquals(0, $stat2->getRebatePT2JackpotCount());
        $this->assertEquals(0, $stat2->getRebatePT2FishingAmount());
        $this->assertEquals(0, $stat2->getRebatePT2FishingCount());
        $this->assertEquals(0, $stat2->getRebatePT2TableAmount());
        $this->assertEquals(0, $stat2->getRebatePT2TableCount());
        $this->assertEquals(0, $stat2->getRebatePT2FeatureAmount());
        $this->assertEquals(0, $stat2->getRebatePT2FeatureCount());
        $this->assertEquals(0, $stat2->getRebateBngSlotsAmount());
        $this->assertEquals(0, $stat2->getRebateBngSlotsCount());
        $this->assertEquals(0, $stat2->getRebateEVOAmount());
        $this->assertEquals(0, $stat2->getRebateEVOCount());
        $this->assertEquals(0, $stat2->getRebateGNSJackpotAmount());
        $this->assertEquals(0, $stat2->getRebateGNSJackpotCount());
        $this->assertEquals(0, $stat1->getRebateGNSFeatureAmount());
        $this->assertEquals(0, $stat1->getRebateGNSFeatureCount());
        $this->assertEquals(0, $stat2->getRebateKYAmount());
        $this->assertEquals(0, $stat2->getRebateKYCount());
        $this->assertEquals(0, $stat2->getrebateGNSTableGamesAmount());
        $this->assertEquals(0, $stat2->getrebateGNSTableGamesCount());
        $this->assertEquals(20, $stat2->getRebateAmount());
        $this->assertEquals(1, $stat2->getRebateCount());

        // Opcode 不在範圍，不會列入統計
        $repo = $em->getRepository('BBDurianBundle:StatCashRebate');
        $stat = $repo->findOneBy(['at' => new \DateTime('2014-10-12 12:00:00')]);
        $this->assertEmpty($stat);

        $emDefault = $this->getContainer()->get('doctrine.orm.default_entity_manager');
        $repo = $emDefault->getRepository('BBDurianBundle:BackgroundProcess');
        $background = $repo->findOneBy(['name' => 'stat-cash-rebate']);

        // 驗證背景最後執行時間
        $this->assertEquals('2014-10-13 12:00:00', $background->getLastEndTime()->format('Y-m-d H:i:s'));

        $params = [
            '--start-date' => '2014-8-13',
            '--end-date' => '2014-8-13',
            '--wait-sec' => 0.00001,
            '--recover' => true
        ];
        $this->runCommand('durian:stat-cash-rebate', $params);

        $emDefault->refresh($background);
        $this->assertEquals(0, $background->getNum());
        $this->assertEquals('2014-10-13 12:00:00', $background->getLastEndTime()->format('Y-m-d H:i:s'));
    }
}
