<?php

namespace Proxies\__CG__\BB\DurianBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class StatCashOffer extends \BB\DurianBundle\Entity\StatCashOffer implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'id', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'at', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'userId', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'currency', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'domain', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'parentId', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerDepositAmount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerDepositCount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerBackCommissionAmount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerBackCommissionCount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerCompanyDepositAmount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerCompanyDepositCount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerOnlineDepositAmount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerOnlineDepositCount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerActiveAmount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerActiveCount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerRegisterAmount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerRegisterCount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerAmount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerCount');
        }

        return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'id', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'at', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'userId', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'currency', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'domain', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'parentId', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerDepositAmount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerDepositCount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerBackCommissionAmount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerBackCommissionCount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerCompanyDepositAmount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerCompanyDepositCount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerOnlineDepositAmount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerOnlineDepositCount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerActiveAmount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerActiveCount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerRegisterAmount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerRegisterCount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerAmount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashOffer' . "\0" . 'offerCount');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (StatCashOffer $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAt', array());

        return parent::getAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', array());

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency($currency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', array($currency));

        return parent::setCurrency($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', array());

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomain($domain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomain', array($domain));

        return parent::setDomain($domain);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomain', array());

        return parent::getDomain();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentId($parentId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentId', array($parentId));

        return parent::setParentId($parentId);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentId', array());

        return parent::getParentId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferDepositAmount($offerDepositAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferDepositAmount', array($offerDepositAmount));

        return parent::setOfferDepositAmount($offerDepositAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function addOfferDepositAmount($offerDepositAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOfferDepositAmount', array($offerDepositAmount));

        return parent::addOfferDepositAmount($offerDepositAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferDepositAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferDepositAmount', array());

        return parent::getOfferDepositAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferDepositCount($offerDepositCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferDepositCount', array($offerDepositCount));

        return parent::setOfferDepositCount($offerDepositCount);
    }

    /**
     * {@inheritDoc}
     */
    public function addOfferDepositCount($offerDepositCount = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOfferDepositCount', array($offerDepositCount));

        return parent::addOfferDepositCount($offerDepositCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferDepositCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferDepositCount', array());

        return parent::getOfferDepositCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferBackCommissionAmount($offerBackCommissionAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferBackCommissionAmount', array($offerBackCommissionAmount));

        return parent::setOfferBackCommissionAmount($offerBackCommissionAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function addOfferBackCommissionAmount($offerBackCommissionAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOfferBackCommissionAmount', array($offerBackCommissionAmount));

        return parent::addOfferBackCommissionAmount($offerBackCommissionAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferBackCommissionAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferBackCommissionAmount', array());

        return parent::getOfferBackCommissionAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferBackCommissionCount($offerBackCommissionCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferBackCommissionCount', array($offerBackCommissionCount));

        return parent::setOfferBackCommissionCount($offerBackCommissionCount);
    }

    /**
     * {@inheritDoc}
     */
    public function addOfferBackCommissionCount($offerBackCommissionCount = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOfferBackCommissionCount', array($offerBackCommissionCount));

        return parent::addOfferBackCommissionCount($offerBackCommissionCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferBackCommissionCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferBackCommissionCount', array());

        return parent::getOfferBackCommissionCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferCompanyDepositAmount($offerCompanyDepositAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferCompanyDepositAmount', array($offerCompanyDepositAmount));

        return parent::setOfferCompanyDepositAmount($offerCompanyDepositAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function addOfferCompanyDepositAmount($offerCompanyDepositAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOfferCompanyDepositAmount', array($offerCompanyDepositAmount));

        return parent::addOfferCompanyDepositAmount($offerCompanyDepositAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferCompanyDepositAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferCompanyDepositAmount', array());

        return parent::getOfferCompanyDepositAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferCompanyDepositCount($offerCompanyDepositCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferCompanyDepositCount', array($offerCompanyDepositCount));

        return parent::setOfferCompanyDepositCount($offerCompanyDepositCount);
    }

    /**
     * {@inheritDoc}
     */
    public function addOfferCompanyDepositCount($offerCompanyDepositCount = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOfferCompanyDepositCount', array($offerCompanyDepositCount));

        return parent::addOfferCompanyDepositCount($offerCompanyDepositCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferCompanyDepositCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferCompanyDepositCount', array());

        return parent::getOfferCompanyDepositCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferOnlineDepositAmount($offerOnlineDepositAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferOnlineDepositAmount', array($offerOnlineDepositAmount));

        return parent::setOfferOnlineDepositAmount($offerOnlineDepositAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function addOfferOnlineDepositAmount($offerOnlineDepositAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOfferOnlineDepositAmount', array($offerOnlineDepositAmount));

        return parent::addOfferOnlineDepositAmount($offerOnlineDepositAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferOnlineDepositAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferOnlineDepositAmount', array());

        return parent::getOfferOnlineDepositAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferOnlineDepositCount($offerOnlineDepositCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferOnlineDepositCount', array($offerOnlineDepositCount));

        return parent::setOfferOnlineDepositCount($offerOnlineDepositCount);
    }

    /**
     * {@inheritDoc}
     */
    public function addOfferOnlineDepositCount($offerOnlineDepositCount = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOfferOnlineDepositCount', array($offerOnlineDepositCount));

        return parent::addOfferOnlineDepositCount($offerOnlineDepositCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferOnlineDepositCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferOnlineDepositCount', array());

        return parent::getOfferOnlineDepositCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferActiveAmount($offerActiveAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferActiveAmount', array($offerActiveAmount));

        return parent::setOfferActiveAmount($offerActiveAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function addOfferActiveAmount($offerActiveAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOfferActiveAmount', array($offerActiveAmount));

        return parent::addOfferActiveAmount($offerActiveAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferActiveAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferActiveAmount', array());

        return parent::getOfferActiveAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferActiveCount($offerActiveCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferActiveCount', array($offerActiveCount));

        return parent::setOfferActiveCount($offerActiveCount);
    }

    /**
     * {@inheritDoc}
     */
    public function addOfferActiveCount($offerActiveCount = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOfferActiveCount', array($offerActiveCount));

        return parent::addOfferActiveCount($offerActiveCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferActiveCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferActiveCount', array());

        return parent::getOfferActiveCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferRegisterAmount($offerRegisterAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferRegisterAmount', array($offerRegisterAmount));

        return parent::setOfferRegisterAmount($offerRegisterAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function addOfferRegisterAmount($offerRegisterAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOfferRegisterAmount', array($offerRegisterAmount));

        return parent::addOfferRegisterAmount($offerRegisterAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferRegisterAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferRegisterAmount', array());

        return parent::getOfferRegisterAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferRegisterCount($offerRegisterCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferRegisterCount', array($offerRegisterCount));

        return parent::setOfferRegisterCount($offerRegisterCount);
    }

    /**
     * {@inheritDoc}
     */
    public function addOfferRegisterCount($offerRegisterCount = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOfferRegisterCount', array($offerRegisterCount));

        return parent::addOfferRegisterCount($offerRegisterCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferRegisterCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferRegisterCount', array());

        return parent::getOfferRegisterCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferAmount($offerAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferAmount', array($offerAmount));

        return parent::setOfferAmount($offerAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function addOfferAmount($offerAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOfferAmount', array($offerAmount));

        return parent::addOfferAmount($offerAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferAmount', array());

        return parent::getOfferAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferCount($offerCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferCount', array($offerCount));

        return parent::setOfferCount($offerCount);
    }

    /**
     * {@inheritDoc}
     */
    public function addOfferCount($offerCount = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOfferCount', array($offerCount));

        return parent::addOfferCount($offerCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferCount', array());

        return parent::getOfferCount();
    }

}
