<?php

namespace Proxies\__CG__\BB\DurianBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Petition extends \BB\DurianBundle\Entity\Petition implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'id', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'userId', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'domain', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'role', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'oldValue', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'value', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'operator', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'createdAt', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'activeAt', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'untreated', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'confirm', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'cancel', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'version');
        }

        return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'id', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'userId', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'domain', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'role', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'oldValue', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'value', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'operator', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'createdAt', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'activeAt', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'untreated', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'confirm', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'cancel', '' . "\0" . 'BB\\DurianBundle\\Entity\\Petition' . "\0" . 'version');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Petition $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', array());

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDomain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomain', array());

        return parent::getDomain();
    }

    /**
     * {@inheritDoc}
     */
    public function getRole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRole', array());

        return parent::getRole();
    }

    /**
     * {@inheritDoc}
     */
    public function getOldValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOldValue', array());

        return parent::getOldValue();
    }

    /**
     * {@inheritDoc}
     */
    public function getValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValue', array());

        return parent::getValue();
    }

    /**
     * {@inheritDoc}
     */
    public function getOperator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperator', array());

        return parent::getOperator();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getActiveAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActiveAt', array());

        return parent::getActiveAt();
    }

    /**
     * {@inheritDoc}
     */
    public function isUntreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isUntreated', array());

        return parent::isUntreated();
    }

    /**
     * {@inheritDoc}
     */
    public function confirm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'confirm', array());

        return parent::confirm();
    }

    /**
     * {@inheritDoc}
     */
    public function isConfirm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isConfirm', array());

        return parent::isConfirm();
    }

    /**
     * {@inheritDoc}
     */
    public function cancel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'cancel', array());

        return parent::cancel();
    }

    /**
     * {@inheritDoc}
     */
    public function isCancel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCancel', array());

        return parent::isCancel();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
