<?php

namespace Proxies\__CG__\BB\DurianBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CashFakeNegative extends \BB\DurianBundle\Entity\CashFakeNegative implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'userId', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'currency', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'cashFakeId', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'balance', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'negative', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'version', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'entryId', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'at', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'opcode', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'amount', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'entryBalance', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'refId', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'memo');
        }

        return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'userId', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'currency', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'cashFakeId', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'balance', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'negative', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'version', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'entryId', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'at', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'opcode', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'amount', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'entryBalance', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'refId', '' . "\0" . 'BB\\DurianBundle\\Entity\\CashFakeNegative' . "\0" . 'memo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CashFakeNegative $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getUserId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', array());

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCurrency();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', array());

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setCashFakeId($cashFakeId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCashFakeId', array($cashFakeId));

        return parent::setCashFakeId($cashFakeId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCashFakeId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCashFakeId', array());

        return parent::getCashFakeId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBalance($balance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBalance', array($balance));

        return parent::setBalance($balance);
    }

    /**
     * {@inheritDoc}
     */
    public function getBalance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBalance', array());

        return parent::getBalance();
    }

    /**
     * {@inheritDoc}
     */
    public function isNegative()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isNegative', array());

        return parent::isNegative();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersion($version)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersion', array($version));

        return parent::setVersion($version);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', array());

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntryId($entryId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntryId', array($entryId));

        return parent::setEntryId($entryId);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntryId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntryId', array());

        return parent::getEntryId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAt($at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAt', array($at));

        return parent::setAt($at);
    }

    /**
     * {@inheritDoc}
     */
    public function getAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAt', array());

        return parent::getAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpcode($opcode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpcode', array($opcode));

        return parent::setOpcode($opcode);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpcode', array());

        return parent::getOpcode();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmount($amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmount', array($amount));

        return parent::setAmount($amount);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmount', array());

        return parent::getAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntryBalance($entryBalance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntryBalance', array($entryBalance));

        return parent::setEntryBalance($entryBalance);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntryBalance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntryBalance', array());

        return parent::getEntryBalance();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefId($refId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefId', array($refId));

        return parent::setRefId($refId);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefId', array());

        return parent::getRefId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemo($memo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemo', array($memo));

        return parent::setMemo($memo);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemo', array());

        return parent::getMemo();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
