<?php

namespace Proxies\__CG__\BB\DurianBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PaymentWithdrawVerify extends \BB\DurianBundle\Entity\PaymentWithdrawVerify implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\PaymentWithdrawVerify' . "\0" . 'paymentCharge', '' . "\0" . 'BB\\DurianBundle\\Entity\\PaymentWithdrawVerify' . "\0" . 'needVerify', '' . "\0" . 'BB\\DurianBundle\\Entity\\PaymentWithdrawVerify' . "\0" . 'verifyTime', '' . "\0" . 'BB\\DurianBundle\\Entity\\PaymentWithdrawVerify' . "\0" . 'verifyAmount');
        }

        return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\PaymentWithdrawVerify' . "\0" . 'paymentCharge', '' . "\0" . 'BB\\DurianBundle\\Entity\\PaymentWithdrawVerify' . "\0" . 'needVerify', '' . "\0" . 'BB\\DurianBundle\\Entity\\PaymentWithdrawVerify' . "\0" . 'verifyTime', '' . "\0" . 'BB\\DurianBundle\\Entity\\PaymentWithdrawVerify' . "\0" . 'verifyAmount');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PaymentWithdrawVerify $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPaymentCharge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentCharge', array());

        return parent::getPaymentCharge();
    }

    /**
     * {@inheritDoc}
     */
    public function isNeedVerify()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isNeedVerify', array());

        return parent::isNeedVerify();
    }

    /**
     * {@inheritDoc}
     */
    public function setNeedVerify($needVerify)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNeedVerify', array($needVerify));

        return parent::setNeedVerify($needVerify);
    }

    /**
     * {@inheritDoc}
     */
    public function getVerifyTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVerifyTime', array());

        return parent::getVerifyTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setVerifyTime($verifyTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVerifyTime', array($verifyTime));

        return parent::setVerifyTime($verifyTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getVerifyAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVerifyAmount', array());

        return parent::getVerifyAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setVerifyAmount($verifyAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVerifyAmount', array($verifyAmount));

        return parent::setVerifyAmount($verifyAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
