<?php

namespace Proxies\__CG__\BB\DurianBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LogOperation extends \BB\DurianBundle\Entity\LogOperation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\LogOperation' . "\0" . 'id', '' . "\0" . 'BB\\DurianBundle\\Entity\\LogOperation' . "\0" . 'tableName', '' . "\0" . 'BB\\DurianBundle\\Entity\\LogOperation' . "\0" . 'majorKey', '' . "\0" . 'BB\\DurianBundle\\Entity\\LogOperation' . "\0" . 'uri', '' . "\0" . 'BB\\DurianBundle\\Entity\\LogOperation' . "\0" . 'method', '' . "\0" . 'BB\\DurianBundle\\Entity\\LogOperation' . "\0" . 'at', '' . "\0" . 'BB\\DurianBundle\\Entity\\LogOperation' . "\0" . 'serverName', '' . "\0" . 'BB\\DurianBundle\\Entity\\LogOperation' . "\0" . 'clientIp', '' . "\0" . 'BB\\DurianBundle\\Entity\\LogOperation' . "\0" . 'message', '' . "\0" . 'BB\\DurianBundle\\Entity\\LogOperation' . "\0" . 'sessionId');
        }

        return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\LogOperation' . "\0" . 'id', '' . "\0" . 'BB\\DurianBundle\\Entity\\LogOperation' . "\0" . 'tableName', '' . "\0" . 'BB\\DurianBundle\\Entity\\LogOperation' . "\0" . 'majorKey', '' . "\0" . 'BB\\DurianBundle\\Entity\\LogOperation' . "\0" . 'uri', '' . "\0" . 'BB\\DurianBundle\\Entity\\LogOperation' . "\0" . 'method', '' . "\0" . 'BB\\DurianBundle\\Entity\\LogOperation' . "\0" . 'at', '' . "\0" . 'BB\\DurianBundle\\Entity\\LogOperation' . "\0" . 'serverName', '' . "\0" . 'BB\\DurianBundle\\Entity\\LogOperation' . "\0" . 'clientIp', '' . "\0" . 'BB\\DurianBundle\\Entity\\LogOperation' . "\0" . 'message', '' . "\0" . 'BB\\DurianBundle\\Entity\\LogOperation' . "\0" . 'sessionId');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LogOperation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getTableName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTableName', array());

        return parent::getTableName();
    }

    /**
     * {@inheritDoc}
     */
    public function getMajorKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMajorKey', array());

        return parent::getMajorKey();
    }

    /**
     * {@inheritDoc}
     */
    public function getAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAt', array());

        return parent::getAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setAt($at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAt', array($at));

        return parent::setAt($at);
    }

    /**
     * {@inheritDoc}
     */
    public function setMajorKey($majorKeys)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMajorKey', array($majorKeys));

        return parent::setMajorKey($majorKeys);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessage', array());

        return parent::getMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function addMessage($field, $oldValue, $newValue = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMessage', array($field, $oldValue, $newValue));

        return parent::addMessage($field, $oldValue, $newValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMethod', array());

        return parent::getMethod();
    }

    /**
     * {@inheritDoc}
     */
    public function getSessionId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSessionId', array());

        return parent::getSessionId();
    }

    /**
     * {@inheritDoc}
     */
    public function getServerName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServerName', array());

        return parent::getServerName();
    }

    /**
     * {@inheritDoc}
     */
    public function getClientIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientIp', array());

        return parent::getClientIp();
    }

}
