<?php

namespace Proxies\__CG__\BB\DurianBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CreditEntry extends \BB\DurianBundle\Entity\CreditEntry implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'id', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'creditId', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'userId', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'groupNum', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'opcode', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'at', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'periodAt', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'amount', 'balance', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'line', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'totalLine', 'refId', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'memo', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'creditVersion');
        }

        return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'id', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'creditId', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'userId', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'groupNum', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'opcode', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'at', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'periodAt', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'amount', 'balance', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'line', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'totalLine', 'refId', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'memo', '' . "\0" . 'BB\\DurianBundle\\Entity\\CreditEntry' . "\0" . 'creditVersion');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CreditEntry $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreditId($creditId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreditId', array($creditId));

        return parent::setCreditId($creditId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreditId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreditId', array());

        return parent::getCreditId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', array());

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupNum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupNum', array());

        return parent::getGroupNum();
    }

    /**
     * {@inheritDoc}
     */
    public function getOpcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpcode', array());

        return parent::getOpcode();
    }

    /**
     * {@inheritDoc}
     */
    public function getAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmount', array());

        return parent::getAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getBalance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBalance', array());

        return parent::getBalance();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefId($refId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefId', array($refId));

        return parent::setRefId($refId);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefId', array());

        return parent::getRefId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAt($at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAt', array($at));

        return parent::setAt($at);
    }

    /**
     * {@inheritDoc}
     */
    public function getAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAt', array());

        return parent::getAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getMemo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemo', array());

        return parent::getMemo();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemo($memo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemo', array($memo));

        return parent::setMemo($memo);
    }

    /**
     * {@inheritDoc}
     */
    public function setLine($line)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLine', array($line));

        return parent::setLine($line);
    }

    /**
     * {@inheritDoc}
     */
    public function getLine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLine', array());

        return parent::getLine();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalLine($totalLine)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalLine', array($totalLine));

        return parent::setTotalLine($totalLine);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalLine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalLine', array());

        return parent::getTotalLine();
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodAt', array());

        return parent::getPeriodAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreditVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreditVersion', array());

        return parent::getCreditVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreditVersion($creditVersion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreditVersion', array($creditVersion));

        return parent::setCreditVersion($creditVersion);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
