<?php

namespace Proxies\__CG__\BB\DurianBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserHasDepositWithdraw extends \BB\DurianBundle\Entity\UserHasDepositWithdraw implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserHasDepositWithdraw' . "\0" . 'userId', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserHasDepositWithdraw' . "\0" . 'depositAt', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserHasDepositWithdraw' . "\0" . 'withdrawAt', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserHasDepositWithdraw' . "\0" . 'deposit', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserHasDepositWithdraw' . "\0" . 'withdraw', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserHasDepositWithdraw' . "\0" . 'firstDepositAt');
        }

        return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserHasDepositWithdraw' . "\0" . 'userId', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserHasDepositWithdraw' . "\0" . 'depositAt', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserHasDepositWithdraw' . "\0" . 'withdrawAt', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserHasDepositWithdraw' . "\0" . 'deposit', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserHasDepositWithdraw' . "\0" . 'withdraw', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserHasDepositWithdraw' . "\0" . 'firstDepositAt');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UserHasDepositWithdraw $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getUserId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', array());

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDepositAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepositAt', array());

        return parent::getDepositAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepositAt($at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepositAt', array($at));

        return parent::setDepositAt($at);
    }

    /**
     * {@inheritDoc}
     */
    public function getWithdrawAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWithdrawAt', array());

        return parent::getWithdrawAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setWithdrawAt($at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWithdrawAt', array($at));

        return parent::setWithdrawAt($at);
    }

    /**
     * {@inheritDoc}
     */
    public function isDeposited()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDeposited', array());

        return parent::isDeposited();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeposit($deposit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeposit', array($deposit));

        return parent::setDeposit($deposit);
    }

    /**
     * {@inheritDoc}
     */
    public function isWithdrew()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isWithdrew', array());

        return parent::isWithdrew();
    }

    /**
     * {@inheritDoc}
     */
    public function setWithdraw($withdraw)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWithdraw', array($withdraw));

        return parent::setWithdraw($withdraw);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstDepositAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstDepositAt', array());

        return parent::getFirstDepositAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstDepositAt($firstDepositAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstDepositAt', array($firstDepositAt));

        return parent::setFirstDepositAt($firstDepositAt);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
