<?php

namespace Proxies\__CG__\BB\DurianBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CardCharge extends \BB\DurianBundle\Entity\CardCharge implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'id', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'domain', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'orderStrategy', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'depositScMax', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'depositScMin', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'depositCoMax', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'depositCoMin', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'depositSaMax', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'depositSaMin', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'depositAgMax', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'depositAgMin', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'version');
        }

        return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'id', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'domain', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'orderStrategy', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'depositScMax', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'depositScMin', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'depositCoMax', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'depositCoMin', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'depositSaMax', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'depositSaMin', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'depositAgMax', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'depositAgMin', '' . "\0" . 'BB\\DurianBundle\\Entity\\CardCharge' . "\0" . 'version');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CardCharge $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDomain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomain', array());

        return parent::getDomain();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderStrategy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderStrategy', array());

        return parent::getOrderStrategy();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderStrategy($strategy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderStrategy', array($strategy));

        return parent::setOrderStrategy($strategy);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepositScMax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepositScMax', array());

        return parent::getDepositScMax();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepositScMax($depositScMax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepositScMax', array($depositScMax));

        return parent::setDepositScMax($depositScMax);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepositScMin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepositScMin', array());

        return parent::getDepositScMin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepositScMin($depositScMin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepositScMin', array($depositScMin));

        return parent::setDepositScMin($depositScMin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepositCoMax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepositCoMax', array());

        return parent::getDepositCoMax();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepositCoMax($depositCoMax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepositCoMax', array($depositCoMax));

        return parent::setDepositCoMax($depositCoMax);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepositCoMin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepositCoMin', array());

        return parent::getDepositCoMin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepositCoMin($depositCoMin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepositCoMin', array($depositCoMin));

        return parent::setDepositCoMin($depositCoMin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepositSaMax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepositSaMax', array());

        return parent::getDepositSaMax();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepositSaMax($depositSaMax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepositSaMax', array($depositSaMax));

        return parent::setDepositSaMax($depositSaMax);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepositSaMin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepositSaMin', array());

        return parent::getDepositSaMin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepositSaMin($depositSaMin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepositSaMin', array($depositSaMin));

        return parent::setDepositSaMin($depositSaMin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepositAgMax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepositAgMax', array());

        return parent::getDepositAgMax();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepositAgMax($depositAgMax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepositAgMax', array($depositAgMax));

        return parent::setDepositAgMax($depositAgMax);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepositAgMin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepositAgMin', array());

        return parent::getDepositAgMin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepositAgMin($depositAgMin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepositAgMin', array($depositAgMin));

        return parent::setDepositAgMin($depositAgMin);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
