<?php

namespace Proxies\__CG__\BB\DurianBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MerchantSuda extends \BB\DurianBundle\Entity\MerchantSuda implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\MerchantSuda' . "\0" . 'id', '' . "\0" . 'BB\\DurianBundle\\Entity\\MerchantSuda' . "\0" . 'domain', '' . "\0" . 'BB\\DurianBundle\\Entity\\MerchantSuda' . "\0" . 'loginAlias', '' . "\0" . 'BB\\DurianBundle\\Entity\\MerchantSuda' . "\0" . 'alias', '' . "\0" . 'BB\\DurianBundle\\Entity\\MerchantSuda' . "\0" . 'privateKey1', '' . "\0" . 'BB\\DurianBundle\\Entity\\MerchantSuda' . "\0" . 'privateKey2', '' . "\0" . 'BB\\DurianBundle\\Entity\\MerchantSuda' . "\0" . 'type', '' . "\0" . 'BB\\DurianBundle\\Entity\\MerchantSuda' . "\0" . 'enable', '' . "\0" . 'BB\\DurianBundle\\Entity\\MerchantSuda' . "\0" . 'removed', '' . "\0" . 'BB\\DurianBundle\\Entity\\MerchantSuda' . "\0" . 'createdAt');
        }

        return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\MerchantSuda' . "\0" . 'id', '' . "\0" . 'BB\\DurianBundle\\Entity\\MerchantSuda' . "\0" . 'domain', '' . "\0" . 'BB\\DurianBundle\\Entity\\MerchantSuda' . "\0" . 'loginAlias', '' . "\0" . 'BB\\DurianBundle\\Entity\\MerchantSuda' . "\0" . 'alias', '' . "\0" . 'BB\\DurianBundle\\Entity\\MerchantSuda' . "\0" . 'privateKey1', '' . "\0" . 'BB\\DurianBundle\\Entity\\MerchantSuda' . "\0" . 'privateKey2', '' . "\0" . 'BB\\DurianBundle\\Entity\\MerchantSuda' . "\0" . 'type', '' . "\0" . 'BB\\DurianBundle\\Entity\\MerchantSuda' . "\0" . 'enable', '' . "\0" . 'BB\\DurianBundle\\Entity\\MerchantSuda' . "\0" . 'removed', '' . "\0" . 'BB\\DurianBundle\\Entity\\MerchantSuda' . "\0" . 'createdAt');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MerchantSuda $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomain($domain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomain', array($domain));

        return parent::setDomain($domain);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomain', array());

        return parent::getDomain();
    }

    /**
     * {@inheritDoc}
     */
    public function setLoginAlias($str)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLoginAlias', array($str));

        return parent::setLoginAlias($str);
    }

    /**
     * {@inheritDoc}
     */
    public function getLoginAlias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLoginAlias', array());

        return parent::getLoginAlias();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlias($str)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlias', array($str));

        return parent::setAlias($str);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlias', array());

        return parent::getAlias();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrivateKey1($str)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrivateKey1', array($str));

        return parent::setPrivateKey1($str);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrivateKey1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrivateKey1', array());

        return parent::getPrivateKey1();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrivateKey2($str)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrivateKey2', array($str));

        return parent::setPrivateKey2($str);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrivateKey2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrivateKey2', array());

        return parent::getPrivateKey2();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function enable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'enable', array());

        return parent::enable();
    }

    /**
     * {@inheritDoc}
     */
    public function disable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'disable', array());

        return parent::disable();
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', array());

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function remove()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'remove', array());

        return parent::remove();
    }

    /**
     * {@inheritDoc}
     */
    public function recover()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'recover', array());

        return parent::recover();
    }

    /**
     * {@inheritDoc}
     */
    public function isRemoved()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isRemoved', array());

        return parent::isRemoved();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
