<?php

namespace Proxies\__CG__\BB\DurianBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserDetail extends \BB\DurianBundle\Entity\UserDetail implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'user', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'nickname', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'nameReal', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'nameChinese', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'nameEnglish', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'country', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'passport', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'identityCard', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'driverLicense', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'insuranceCard', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'healthCard', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'birthday', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'telephone', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'qqNum', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'note', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'password', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'wechat');
        }

        return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'user', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'nickname', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'nameReal', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'nameChinese', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'nameEnglish', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'country', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'passport', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'identityCard', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'driverLicense', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'insuranceCard', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'healthCard', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'birthday', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'telephone', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'qqNum', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'note', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'password', '' . "\0" . 'BB\\DurianBundle\\Entity\\UserDetail' . "\0" . 'wechat');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UserDetail $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setNickname($nickname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNickname', array($nickname));

        return parent::setNickname($nickname);
    }

    /**
     * {@inheritDoc}
     */
    public function getNickname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNickname', array());

        return parent::getNickname();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameReal($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameReal', array($name));

        return parent::setNameReal($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameReal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameReal', array());

        return parent::getNameReal();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameChinese($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameChinese', array($name));

        return parent::setNameChinese($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameChinese()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameChinese', array());

        return parent::getNameChinese();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameEnglish($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameEnglish', array($name));

        return parent::setNameEnglish($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameEnglish()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameEnglish', array());

        return parent::getNameEnglish();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', array($country));

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', array());

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassport($passport)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassport', array($passport));

        return parent::setPassport($passport);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassport()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassport', array());

        return parent::getPassport();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdentityCard($identityCard)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdentityCard', array($identityCard));

        return parent::setIdentityCard($identityCard);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentityCard()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentityCard', array());

        return parent::getIdentityCard();
    }

    /**
     * {@inheritDoc}
     */
    public function setDriverLicense($driverLicense)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDriverLicense', array($driverLicense));

        return parent::setDriverLicense($driverLicense);
    }

    /**
     * {@inheritDoc}
     */
    public function getDriverLicense()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDriverLicense', array());

        return parent::getDriverLicense();
    }

    /**
     * {@inheritDoc}
     */
    public function setInsuranceCard($insuranceCard)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInsuranceCard', array($insuranceCard));

        return parent::setInsuranceCard($insuranceCard);
    }

    /**
     * {@inheritDoc}
     */
    public function getInsuranceCard()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInsuranceCard', array());

        return parent::getInsuranceCard();
    }

    /**
     * {@inheritDoc}
     */
    public function setHealthCard($healthCard)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHealthCard', array($healthCard));

        return parent::setHealthCard($healthCard);
    }

    /**
     * {@inheritDoc}
     */
    public function getHealthCard()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHealthCard', array());

        return parent::getHealthCard();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthday($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthday', array($date));

        return parent::setBirthday($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthday()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthday', array());

        return parent::getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', array($telephone));

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', array());

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setQQNum($number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQQNum', array($number));

        return parent::setQQNum($number);
    }

    /**
     * {@inheritDoc}
     */
    public function getQQNum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQQNum', array());

        return parent::getQQNum();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote($note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', array($note));

        return parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', array());

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setWechat($wechat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWechat', array($wechat));

        return parent::setWechat($wechat);
    }

    /**
     * {@inheritDoc}
     */
    public function getWechat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWechat', array());

        return parent::getWechat();
    }

    /**
     * {@inheritDoc}
     */
    public function setFromRemoved(\BB\DurianBundle\Entity\RemovedUserDetail $removedUD)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFromRemoved', array($removedUD));

        return parent::setFromRemoved($removedUD);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
