<?php

namespace Proxies\__CG__\BB\DurianBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class StatCashRemit extends \BB\DurianBundle\Entity\StatCashRemit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'id', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'at', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'userId', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'currency', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'domain', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'parentId', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'offerRemitAmount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'offerRemitCount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'offerCompanyRemitAmount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'offerCompanyRemitCount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'remitAmount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'remitCount');
        }

        return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'id', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'at', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'userId', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'currency', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'domain', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'parentId', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'offerRemitAmount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'offerRemitCount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'offerCompanyRemitAmount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'offerCompanyRemitCount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'remitAmount', '' . "\0" . 'BB\\DurianBundle\\Entity\\StatCashRemit' . "\0" . 'remitCount');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (StatCashRemit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAt', array());

        return parent::getAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', array());

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency($currency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', array($currency));

        return parent::setCurrency($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', array());

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomain($domain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomain', array($domain));

        return parent::setDomain($domain);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomain', array());

        return parent::getDomain();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentId($parentId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentId', array($parentId));

        return parent::setParentId($parentId);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentId', array());

        return parent::getParentId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferRemitAmount($offerRemitAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferRemitAmount', array($offerRemitAmount));

        return parent::setOfferRemitAmount($offerRemitAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function addOfferRemitAmount($offerRemitAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOfferRemitAmount', array($offerRemitAmount));

        return parent::addOfferRemitAmount($offerRemitAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferRemitAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferRemitAmount', array());

        return parent::getOfferRemitAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferRemitCount($offerRemitCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferRemitCount', array($offerRemitCount));

        return parent::setOfferRemitCount($offerRemitCount);
    }

    /**
     * {@inheritDoc}
     */
    public function addOfferRemitCount($offerRemitCount = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOfferRemitCount', array($offerRemitCount));

        return parent::addOfferRemitCount($offerRemitCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferRemitCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferRemitCount', array());

        return parent::getOfferRemitCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferCompanyRemitAmount($offerCompanyRemitAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferCompanyRemitAmount', array($offerCompanyRemitAmount));

        return parent::setOfferCompanyRemitAmount($offerCompanyRemitAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function addOfferCompanyRemitAmount($offerCompanyRemitAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOfferCompanyRemitAmount', array($offerCompanyRemitAmount));

        return parent::addOfferCompanyRemitAmount($offerCompanyRemitAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferCompanyRemitAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferCompanyRemitAmount', array());

        return parent::getOfferCompanyRemitAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferCompanyRemitCount($offerCompanyRemitCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferCompanyRemitCount', array($offerCompanyRemitCount));

        return parent::setOfferCompanyRemitCount($offerCompanyRemitCount);
    }

    /**
     * {@inheritDoc}
     */
    public function addOfferCompanyRemitCount($offerCompanyRemitCount = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOfferCompanyRemitCount', array($offerCompanyRemitCount));

        return parent::addOfferCompanyRemitCount($offerCompanyRemitCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferCompanyRemitCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferCompanyRemitCount', array());

        return parent::getOfferCompanyRemitCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemitAmount($remitAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemitAmount', array($remitAmount));

        return parent::setRemitAmount($remitAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function addRemitAmount($remitAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRemitAmount', array($remitAmount));

        return parent::addRemitAmount($remitAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemitAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemitAmount', array());

        return parent::getRemitAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemitCount($remitCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemitCount', array($remitCount));

        return parent::setRemitCount($remitCount);
    }

    /**
     * {@inheritDoc}
     */
    public function addRemitCount($remitCount = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRemitCount', array($remitCount));

        return parent::addRemitCount($remitCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemitCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemitCount', array());

        return parent::getRemitCount();
    }

}
