<?php

namespace Proxies\__CG__\BB\DurianBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BackgroundProcess extends \BB\DurianBundle\Entity\BackgroundProcess implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\BackgroundProcess' . "\0" . 'name', '' . "\0" . 'BB\\DurianBundle\\Entity\\BackgroundProcess' . "\0" . 'enable', '' . "\0" . 'BB\\DurianBundle\\Entity\\BackgroundProcess' . "\0" . 'beginAt', '' . "\0" . 'BB\\DurianBundle\\Entity\\BackgroundProcess' . "\0" . 'endAt', '' . "\0" . 'BB\\DurianBundle\\Entity\\BackgroundProcess' . "\0" . 'lastEndTime', '' . "\0" . 'BB\\DurianBundle\\Entity\\BackgroundProcess' . "\0" . 'memo', '' . "\0" . 'BB\\DurianBundle\\Entity\\BackgroundProcess' . "\0" . 'num', '' . "\0" . 'BB\\DurianBundle\\Entity\\BackgroundProcess' . "\0" . 'msgNum');
        }

        return array('__isInitialized__', '' . "\0" . 'BB\\DurianBundle\\Entity\\BackgroundProcess' . "\0" . 'name', '' . "\0" . 'BB\\DurianBundle\\Entity\\BackgroundProcess' . "\0" . 'enable', '' . "\0" . 'BB\\DurianBundle\\Entity\\BackgroundProcess' . "\0" . 'beginAt', '' . "\0" . 'BB\\DurianBundle\\Entity\\BackgroundProcess' . "\0" . 'endAt', '' . "\0" . 'BB\\DurianBundle\\Entity\\BackgroundProcess' . "\0" . 'lastEndTime', '' . "\0" . 'BB\\DurianBundle\\Entity\\BackgroundProcess' . "\0" . 'memo', '' . "\0" . 'BB\\DurianBundle\\Entity\\BackgroundProcess' . "\0" . 'num', '' . "\0" . 'BB\\DurianBundle\\Entity\\BackgroundProcess' . "\0" . 'msgNum');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BackgroundProcess $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getName()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getName();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function isEnable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnable', array());

        return parent::isEnable();
    }

    /**
     * {@inheritDoc}
     */
    public function setBeginAt(\DateTime $date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBeginAt', array($date));

        return parent::setBeginAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getBeginAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBeginAt', array());

        return parent::getBeginAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndAt(\DateTime $date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndAt', array($date));

        return parent::setEndAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndAt', array());

        return parent::getEndAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemo($memo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemo', array($memo));

        return parent::setMemo($memo);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemo', array());

        return parent::getMemo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNum($num)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNum', array($num));

        return parent::setNum($num);
    }

    /**
     * {@inheritDoc}
     */
    public function getNum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNum', array());

        return parent::getNum();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgNum($msgNum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgNum', array($msgNum));

        return parent::setMsgNum($msgNum);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgNum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgNum', array());

        return parent::getMsgNum();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastEndTime(\DateTime $date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastEndTime', array($date));

        return parent::setLastEndTime($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastEndTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastEndTime', array());

        return parent::getLastEndTime();
    }

}
